// Code generated by counterfeiter. DO NOT EDIT.
package toolsfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/tools"
)

type FakeSmartToolProvider struct {
	RecordToolUsageStub        func(context.Context, []string)
	recordToolUsageMutex       sync.RWMutex
	recordToolUsageArgsForCall []struct {
		arg1 context.Context
		arg2 []string
	}
	SearchToolsWithContextStub        func(context.Context, string, []string, int) (tools.ToolSearchResults, error)
	searchToolsWithContextMutex       sync.RWMutex
	searchToolsWithContextArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []string
		arg4 int
	}
	searchToolsWithContextReturns struct {
		result1 tools.ToolSearchResults
		result2 error
	}
	searchToolsWithContextReturnsOnCall map[int]struct {
		result1 tools.ToolSearchResults
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSmartToolProvider) RecordToolUsage(arg1 context.Context, arg2 []string) {
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.recordToolUsageMutex.Lock()
	fake.recordToolUsageArgsForCall = append(fake.recordToolUsageArgsForCall, struct {
		arg1 context.Context
		arg2 []string
	}{arg1, arg2Copy})
	stub := fake.RecordToolUsageStub
	fake.recordInvocation("RecordToolUsage", []interface{}{arg1, arg2Copy})
	fake.recordToolUsageMutex.Unlock()
	if stub != nil {
		fake.RecordToolUsageStub(arg1, arg2)
	}
}

func (fake *FakeSmartToolProvider) RecordToolUsageCallCount() int {
	fake.recordToolUsageMutex.RLock()
	defer fake.recordToolUsageMutex.RUnlock()
	return len(fake.recordToolUsageArgsForCall)
}

func (fake *FakeSmartToolProvider) RecordToolUsageCalls(stub func(context.Context, []string)) {
	fake.recordToolUsageMutex.Lock()
	defer fake.recordToolUsageMutex.Unlock()
	fake.RecordToolUsageStub = stub
}

func (fake *FakeSmartToolProvider) RecordToolUsageArgsForCall(i int) (context.Context, []string) {
	fake.recordToolUsageMutex.RLock()
	defer fake.recordToolUsageMutex.RUnlock()
	argsForCall := fake.recordToolUsageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSmartToolProvider) SearchToolsWithContext(arg1 context.Context, arg2 string, arg3 []string, arg4 int) (tools.ToolSearchResults, error) {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.searchToolsWithContextMutex.Lock()
	ret, specificReturn := fake.searchToolsWithContextReturnsOnCall[len(fake.searchToolsWithContextArgsForCall)]
	fake.searchToolsWithContextArgsForCall = append(fake.searchToolsWithContextArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []string
		arg4 int
	}{arg1, arg2, arg3Copy, arg4})
	stub := fake.SearchToolsWithContextStub
	fakeReturns := fake.searchToolsWithContextReturns
	fake.recordInvocation("SearchToolsWithContext", []interface{}{arg1, arg2, arg3Copy, arg4})
	fake.searchToolsWithContextMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSmartToolProvider) SearchToolsWithContextCallCount() int {
	fake.searchToolsWithContextMutex.RLock()
	defer fake.searchToolsWithContextMutex.RUnlock()
	return len(fake.searchToolsWithContextArgsForCall)
}

func (fake *FakeSmartToolProvider) SearchToolsWithContextCalls(stub func(context.Context, string, []string, int) (tools.ToolSearchResults, error)) {
	fake.searchToolsWithContextMutex.Lock()
	defer fake.searchToolsWithContextMutex.Unlock()
	fake.SearchToolsWithContextStub = stub
}

func (fake *FakeSmartToolProvider) SearchToolsWithContextArgsForCall(i int) (context.Context, string, []string, int) {
	fake.searchToolsWithContextMutex.RLock()
	defer fake.searchToolsWithContextMutex.RUnlock()
	argsForCall := fake.searchToolsWithContextArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeSmartToolProvider) SearchToolsWithContextReturns(result1 tools.ToolSearchResults, result2 error) {
	fake.searchToolsWithContextMutex.Lock()
	defer fake.searchToolsWithContextMutex.Unlock()
	fake.SearchToolsWithContextStub = nil
	fake.searchToolsWithContextReturns = struct {
		result1 tools.ToolSearchResults
		result2 error
	}{result1, result2}
}

func (fake *FakeSmartToolProvider) SearchToolsWithContextReturnsOnCall(i int, result1 tools.ToolSearchResults, result2 error) {
	fake.searchToolsWithContextMutex.Lock()
	defer fake.searchToolsWithContextMutex.Unlock()
	fake.SearchToolsWithContextStub = nil
	if fake.searchToolsWithContextReturnsOnCall == nil {
		fake.searchToolsWithContextReturnsOnCall = make(map[int]struct {
			result1 tools.ToolSearchResults
			result2 error
		})
	}
	fake.searchToolsWithContextReturnsOnCall[i] = struct {
		result1 tools.ToolSearchResults
		result2 error
	}{result1, result2}
}

func (fake *FakeSmartToolProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSmartToolProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ tools.SmartToolProvider = new(FakeSmartToolProvider)
