// Code generated by counterfeiter. DO NOT EDIT.
package toolsfakes

import (
	"context"
	"sync"

	"trpc.group/trpc-go/trpc-agent-go/tool"
)

type FakeCallableTool struct {
	CallStub        func(context.Context, []byte) (any, error)
	callMutex       sync.RWMutex
	callArgsForCall []struct {
		arg1 context.Context
		arg2 []byte
	}
	callReturns struct {
		result1 any
		result2 error
	}
	callReturnsOnCall map[int]struct {
		result1 any
		result2 error
	}
	DeclarationStub        func() *tool.Declaration
	declarationMutex       sync.RWMutex
	declarationArgsForCall []struct {
	}
	declarationReturns struct {
		result1 *tool.Declaration
	}
	declarationReturnsOnCall map[int]struct {
		result1 *tool.Declaration
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCallableTool) Call(arg1 context.Context, arg2 []byte) (any, error) {
	var arg2Copy []byte
	if arg2 != nil {
		arg2Copy = make([]byte, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.callMutex.Lock()
	ret, specificReturn := fake.callReturnsOnCall[len(fake.callArgsForCall)]
	fake.callArgsForCall = append(fake.callArgsForCall, struct {
		arg1 context.Context
		arg2 []byte
	}{arg1, arg2Copy})
	stub := fake.CallStub
	fakeReturns := fake.callReturns
	fake.recordInvocation("Call", []interface{}{arg1, arg2Copy})
	fake.callMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCallableTool) CallCallCount() int {
	fake.callMutex.RLock()
	defer fake.callMutex.RUnlock()
	return len(fake.callArgsForCall)
}

func (fake *FakeCallableTool) CallCalls(stub func(context.Context, []byte) (any, error)) {
	fake.callMutex.Lock()
	defer fake.callMutex.Unlock()
	fake.CallStub = stub
}

func (fake *FakeCallableTool) CallArgsForCall(i int) (context.Context, []byte) {
	fake.callMutex.RLock()
	defer fake.callMutex.RUnlock()
	argsForCall := fake.callArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCallableTool) CallReturns(result1 any, result2 error) {
	fake.callMutex.Lock()
	defer fake.callMutex.Unlock()
	fake.CallStub = nil
	fake.callReturns = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *FakeCallableTool) CallReturnsOnCall(i int, result1 any, result2 error) {
	fake.callMutex.Lock()
	defer fake.callMutex.Unlock()
	fake.CallStub = nil
	if fake.callReturnsOnCall == nil {
		fake.callReturnsOnCall = make(map[int]struct {
			result1 any
			result2 error
		})
	}
	fake.callReturnsOnCall[i] = struct {
		result1 any
		result2 error
	}{result1, result2}
}

func (fake *FakeCallableTool) Declaration() *tool.Declaration {
	fake.declarationMutex.Lock()
	ret, specificReturn := fake.declarationReturnsOnCall[len(fake.declarationArgsForCall)]
	fake.declarationArgsForCall = append(fake.declarationArgsForCall, struct {
	}{})
	stub := fake.DeclarationStub
	fakeReturns := fake.declarationReturns
	fake.recordInvocation("Declaration", []interface{}{})
	fake.declarationMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCallableTool) DeclarationCallCount() int {
	fake.declarationMutex.RLock()
	defer fake.declarationMutex.RUnlock()
	return len(fake.declarationArgsForCall)
}

func (fake *FakeCallableTool) DeclarationCalls(stub func() *tool.Declaration) {
	fake.declarationMutex.Lock()
	defer fake.declarationMutex.Unlock()
	fake.DeclarationStub = stub
}

func (fake *FakeCallableTool) DeclarationReturns(result1 *tool.Declaration) {
	fake.declarationMutex.Lock()
	defer fake.declarationMutex.Unlock()
	fake.DeclarationStub = nil
	fake.declarationReturns = struct {
		result1 *tool.Declaration
	}{result1}
}

func (fake *FakeCallableTool) DeclarationReturnsOnCall(i int, result1 *tool.Declaration) {
	fake.declarationMutex.Lock()
	defer fake.declarationMutex.Unlock()
	fake.DeclarationStub = nil
	if fake.declarationReturnsOnCall == nil {
		fake.declarationReturnsOnCall = make(map[int]struct {
			result1 *tool.Declaration
		})
	}
	fake.declarationReturnsOnCall[i] = struct {
		result1 *tool.Declaration
	}{result1}
}

func (fake *FakeCallableTool) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCallableTool) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ tool.CallableTool = new(FakeCallableTool)
