// Code generated by counterfeiter. DO NOT EDIT.
package aguifakes

import (
	"sync"

	"github.com/stackgenhq/genie/pkg/messenger/agui"
)

type FakeMessengerBridge struct {
	CompleteThreadStub        func(string)
	completeThreadMutex       sync.RWMutex
	completeThreadArgsForCall []struct {
		arg1 string
	}
	InjectMessageStub        func(string, string, string, chan<- interface{}, interface{}) error
	injectMessageMutex       sync.RWMutex
	injectMessageArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 chan<- interface{}
		arg5 interface{}
	}
	injectMessageReturns struct {
		result1 error
	}
	injectMessageReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMessengerBridge) CompleteThread(arg1 string) {
	fake.completeThreadMutex.Lock()
	fake.completeThreadArgsForCall = append(fake.completeThreadArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.CompleteThreadStub
	fake.recordInvocation("CompleteThread", []interface{}{arg1})
	fake.completeThreadMutex.Unlock()
	if stub != nil {
		fake.CompleteThreadStub(arg1)
	}
}

func (fake *FakeMessengerBridge) CompleteThreadCallCount() int {
	fake.completeThreadMutex.RLock()
	defer fake.completeThreadMutex.RUnlock()
	return len(fake.completeThreadArgsForCall)
}

func (fake *FakeMessengerBridge) CompleteThreadCalls(stub func(string)) {
	fake.completeThreadMutex.Lock()
	defer fake.completeThreadMutex.Unlock()
	fake.CompleteThreadStub = stub
}

func (fake *FakeMessengerBridge) CompleteThreadArgsForCall(i int) string {
	fake.completeThreadMutex.RLock()
	defer fake.completeThreadMutex.RUnlock()
	argsForCall := fake.completeThreadArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMessengerBridge) InjectMessage(arg1 string, arg2 string, arg3 string, arg4 chan<- interface{}, arg5 interface{}) error {
	fake.injectMessageMutex.Lock()
	ret, specificReturn := fake.injectMessageReturnsOnCall[len(fake.injectMessageArgsForCall)]
	fake.injectMessageArgsForCall = append(fake.injectMessageArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 chan<- interface{}
		arg5 interface{}
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.InjectMessageStub
	fakeReturns := fake.injectMessageReturns
	fake.recordInvocation("InjectMessage", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.injectMessageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMessengerBridge) InjectMessageCallCount() int {
	fake.injectMessageMutex.RLock()
	defer fake.injectMessageMutex.RUnlock()
	return len(fake.injectMessageArgsForCall)
}

func (fake *FakeMessengerBridge) InjectMessageCalls(stub func(string, string, string, chan<- interface{}, interface{}) error) {
	fake.injectMessageMutex.Lock()
	defer fake.injectMessageMutex.Unlock()
	fake.InjectMessageStub = stub
}

func (fake *FakeMessengerBridge) InjectMessageArgsForCall(i int) (string, string, string, chan<- interface{}, interface{}) {
	fake.injectMessageMutex.RLock()
	defer fake.injectMessageMutex.RUnlock()
	argsForCall := fake.injectMessageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeMessengerBridge) InjectMessageReturns(result1 error) {
	fake.injectMessageMutex.Lock()
	defer fake.injectMessageMutex.Unlock()
	fake.InjectMessageStub = nil
	fake.injectMessageReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMessengerBridge) InjectMessageReturnsOnCall(i int, result1 error) {
	fake.injectMessageMutex.Lock()
	defer fake.injectMessageMutex.Unlock()
	fake.InjectMessageStub = nil
	if fake.injectMessageReturnsOnCall == nil {
		fake.injectMessageReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.injectMessageReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMessengerBridge) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMessengerBridge) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ agui.MessengerBridge = new(FakeMessengerBridge)
