// Copyright (C) 2026 StackGen, Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by counterfeiter. DO NOT EDIT.
package aguifakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/messenger/agui"
)

type FakeExpert struct {
	HandleStub        func(context.Context, agui.ChatRequest)
	handleMutex       sync.RWMutex
	handleArgsForCall []struct {
		arg1 context.Context
		arg2 agui.ChatRequest
	}
	InjectFeedbackStub        func(context.Context, string, string) error
	injectFeedbackMutex       sync.RWMutex
	injectFeedbackArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	injectFeedbackReturns struct {
		result1 error
	}
	injectFeedbackReturnsOnCall map[int]struct {
		result1 error
	}
	ResumeStub        func(context.Context) string
	resumeMutex       sync.RWMutex
	resumeArgsForCall []struct {
		arg1 context.Context
	}
	resumeReturns struct {
		result1 string
	}
	resumeReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeExpert) Handle(arg1 context.Context, arg2 agui.ChatRequest) {
	fake.handleMutex.Lock()
	fake.handleArgsForCall = append(fake.handleArgsForCall, struct {
		arg1 context.Context
		arg2 agui.ChatRequest
	}{arg1, arg2})
	stub := fake.HandleStub
	fake.recordInvocation("Handle", []interface{}{arg1, arg2})
	fake.handleMutex.Unlock()
	if stub != nil {
		fake.HandleStub(arg1, arg2)
	}
}

func (fake *FakeExpert) HandleCallCount() int {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	return len(fake.handleArgsForCall)
}

func (fake *FakeExpert) HandleCalls(stub func(context.Context, agui.ChatRequest)) {
	fake.handleMutex.Lock()
	defer fake.handleMutex.Unlock()
	fake.HandleStub = stub
}

func (fake *FakeExpert) HandleArgsForCall(i int) (context.Context, agui.ChatRequest) {
	fake.handleMutex.RLock()
	defer fake.handleMutex.RUnlock()
	argsForCall := fake.handleArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeExpert) InjectFeedback(arg1 context.Context, arg2 string, arg3 string) error {
	fake.injectFeedbackMutex.Lock()
	ret, specificReturn := fake.injectFeedbackReturnsOnCall[len(fake.injectFeedbackArgsForCall)]
	fake.injectFeedbackArgsForCall = append(fake.injectFeedbackArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.InjectFeedbackStub
	fakeReturns := fake.injectFeedbackReturns
	fake.recordInvocation("InjectFeedback", []interface{}{arg1, arg2, arg3})
	fake.injectFeedbackMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeExpert) InjectFeedbackCallCount() int {
	fake.injectFeedbackMutex.RLock()
	defer fake.injectFeedbackMutex.RUnlock()
	return len(fake.injectFeedbackArgsForCall)
}

func (fake *FakeExpert) InjectFeedbackCalls(stub func(context.Context, string, string) error) {
	fake.injectFeedbackMutex.Lock()
	defer fake.injectFeedbackMutex.Unlock()
	fake.InjectFeedbackStub = stub
}

func (fake *FakeExpert) InjectFeedbackArgsForCall(i int) (context.Context, string, string) {
	fake.injectFeedbackMutex.RLock()
	defer fake.injectFeedbackMutex.RUnlock()
	argsForCall := fake.injectFeedbackArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeExpert) InjectFeedbackReturns(result1 error) {
	fake.injectFeedbackMutex.Lock()
	defer fake.injectFeedbackMutex.Unlock()
	fake.InjectFeedbackStub = nil
	fake.injectFeedbackReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeExpert) InjectFeedbackReturnsOnCall(i int, result1 error) {
	fake.injectFeedbackMutex.Lock()
	defer fake.injectFeedbackMutex.Unlock()
	fake.InjectFeedbackStub = nil
	if fake.injectFeedbackReturnsOnCall == nil {
		fake.injectFeedbackReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.injectFeedbackReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeExpert) Resume(arg1 context.Context) string {
	fake.resumeMutex.Lock()
	ret, specificReturn := fake.resumeReturnsOnCall[len(fake.resumeArgsForCall)]
	fake.resumeArgsForCall = append(fake.resumeArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ResumeStub
	fakeReturns := fake.resumeReturns
	fake.recordInvocation("Resume", []interface{}{arg1})
	fake.resumeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeExpert) ResumeCallCount() int {
	fake.resumeMutex.RLock()
	defer fake.resumeMutex.RUnlock()
	return len(fake.resumeArgsForCall)
}

func (fake *FakeExpert) ResumeCalls(stub func(context.Context) string) {
	fake.resumeMutex.Lock()
	defer fake.resumeMutex.Unlock()
	fake.ResumeStub = stub
}

func (fake *FakeExpert) ResumeArgsForCall(i int) context.Context {
	fake.resumeMutex.RLock()
	defer fake.resumeMutex.RUnlock()
	argsForCall := fake.resumeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeExpert) ResumeReturns(result1 string) {
	fake.resumeMutex.Lock()
	defer fake.resumeMutex.Unlock()
	fake.ResumeStub = nil
	fake.resumeReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeExpert) ResumeReturnsOnCall(i int, result1 string) {
	fake.resumeMutex.Lock()
	defer fake.resumeMutex.Unlock()
	fake.ResumeStub = nil
	if fake.resumeReturnsOnCall == nil {
		fake.resumeReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.resumeReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeExpert) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeExpert) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ agui.Expert = new(FakeExpert)
