name: Setup code base
description: "Setup the repo"
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        cache: true
        go-version-file: ./go.mod
    - name: Create compilable code
      shell: bash
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin:$PATH:$HOME/.local/bin
        make setup
