// Code generated by counterfeiter. DO NOT EDIT.
package docparserfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/datasource"
	"github.com/stackgenhq/genie/pkg/datasource/docparser"
)

type FakeProvider struct {
	ParseStub        func(context.Context, docparser.ParseRequest) ([]datasource.NormalizedItem, error)
	parseMutex       sync.RWMutex
	parseArgsForCall []struct {
		arg1 context.Context
		arg2 docparser.ParseRequest
	}
	parseReturns struct {
		result1 []datasource.NormalizedItem
		result2 error
	}
	parseReturnsOnCall map[int]struct {
		result1 []datasource.NormalizedItem
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProvider) Parse(arg1 context.Context, arg2 docparser.ParseRequest) ([]datasource.NormalizedItem, error) {
	fake.parseMutex.Lock()
	ret, specificReturn := fake.parseReturnsOnCall[len(fake.parseArgsForCall)]
	fake.parseArgsForCall = append(fake.parseArgsForCall, struct {
		arg1 context.Context
		arg2 docparser.ParseRequest
	}{arg1, arg2})
	stub := fake.ParseStub
	fakeReturns := fake.parseReturns
	fake.recordInvocation("Parse", []interface{}{arg1, arg2})
	fake.parseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProvider) ParseCallCount() int {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	return len(fake.parseArgsForCall)
}

func (fake *FakeProvider) ParseCalls(stub func(context.Context, docparser.ParseRequest) ([]datasource.NormalizedItem, error)) {
	fake.parseMutex.Lock()
	defer fake.parseMutex.Unlock()
	fake.ParseStub = stub
}

func (fake *FakeProvider) ParseArgsForCall(i int) (context.Context, docparser.ParseRequest) {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	argsForCall := fake.parseArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProvider) ParseReturns(result1 []datasource.NormalizedItem, result2 error) {
	fake.parseMutex.Lock()
	defer fake.parseMutex.Unlock()
	fake.ParseStub = nil
	fake.parseReturns = struct {
		result1 []datasource.NormalizedItem
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) ParseReturnsOnCall(i int, result1 []datasource.NormalizedItem, result2 error) {
	fake.parseMutex.Lock()
	defer fake.parseMutex.Unlock()
	fake.ParseStub = nil
	if fake.parseReturnsOnCall == nil {
		fake.parseReturnsOnCall = make(map[int]struct {
			result1 []datasource.NormalizedItem
			result2 error
		})
	}
	fake.parseReturnsOnCall[i] = struct {
		result1 []datasource.NormalizedItem
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ docparser.Provider = new(FakeProvider)
