// Copyright (C) 2026 StackGen, Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by counterfeiter. DO NOT EDIT.
package auditfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/audit"
)

type FakeAuditor struct {
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	LogStub        func(context.Context, audit.LogRequest)
	logMutex       sync.RWMutex
	logArgsForCall []struct {
		arg1 context.Context
		arg2 audit.LogRequest
	}
	RecentStub        func(context.Context, audit.LookupRequest) ([]audit.Event, error)
	recentMutex       sync.RWMutex
	recentArgsForCall []struct {
		arg1 context.Context
		arg2 audit.LookupRequest
	}
	recentReturns struct {
		result1 []audit.Event
		result2 error
	}
	recentReturnsOnCall map[int]struct {
		result1 []audit.Event
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAuditor) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuditor) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeAuditor) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeAuditor) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuditor) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuditor) Log(arg1 context.Context, arg2 audit.LogRequest) {
	fake.logMutex.Lock()
	fake.logArgsForCall = append(fake.logArgsForCall, struct {
		arg1 context.Context
		arg2 audit.LogRequest
	}{arg1, arg2})
	stub := fake.LogStub
	fake.recordInvocation("Log", []interface{}{arg1, arg2})
	fake.logMutex.Unlock()
	if stub != nil {
		fake.LogStub(arg1, arg2)
	}
}

func (fake *FakeAuditor) LogCallCount() int {
	fake.logMutex.RLock()
	defer fake.logMutex.RUnlock()
	return len(fake.logArgsForCall)
}

func (fake *FakeAuditor) LogCalls(stub func(context.Context, audit.LogRequest)) {
	fake.logMutex.Lock()
	defer fake.logMutex.Unlock()
	fake.LogStub = stub
}

func (fake *FakeAuditor) LogArgsForCall(i int) (context.Context, audit.LogRequest) {
	fake.logMutex.RLock()
	defer fake.logMutex.RUnlock()
	argsForCall := fake.logArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAuditor) Recent(arg1 context.Context, arg2 audit.LookupRequest) ([]audit.Event, error) {
	fake.recentMutex.Lock()
	ret, specificReturn := fake.recentReturnsOnCall[len(fake.recentArgsForCall)]
	fake.recentArgsForCall = append(fake.recentArgsForCall, struct {
		arg1 context.Context
		arg2 audit.LookupRequest
	}{arg1, arg2})
	stub := fake.RecentStub
	fakeReturns := fake.recentReturns
	fake.recordInvocation("Recent", []interface{}{arg1, arg2})
	fake.recentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAuditor) RecentCallCount() int {
	fake.recentMutex.RLock()
	defer fake.recentMutex.RUnlock()
	return len(fake.recentArgsForCall)
}

func (fake *FakeAuditor) RecentCalls(stub func(context.Context, audit.LookupRequest) ([]audit.Event, error)) {
	fake.recentMutex.Lock()
	defer fake.recentMutex.Unlock()
	fake.RecentStub = stub
}

func (fake *FakeAuditor) RecentArgsForCall(i int) (context.Context, audit.LookupRequest) {
	fake.recentMutex.RLock()
	defer fake.recentMutex.RUnlock()
	argsForCall := fake.recentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAuditor) RecentReturns(result1 []audit.Event, result2 error) {
	fake.recentMutex.Lock()
	defer fake.recentMutex.Unlock()
	fake.RecentStub = nil
	fake.recentReturns = struct {
		result1 []audit.Event
		result2 error
	}{result1, result2}
}

func (fake *FakeAuditor) RecentReturnsOnCall(i int, result1 []audit.Event, result2 error) {
	fake.recentMutex.Lock()
	defer fake.recentMutex.Unlock()
	fake.RecentStub = nil
	if fake.recentReturnsOnCall == nil {
		fake.recentReturnsOnCall = make(map[int]struct {
			result1 []audit.Event
			result2 error
		})
	}
	fake.recentReturnsOnCall[i] = struct {
		result1 []audit.Event
		result2 error
	}{result1, result2}
}

func (fake *FakeAuditor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAuditor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ audit.Auditor = new(FakeAuditor)
