# qa_test_genie.toml
agent_name = "QA-Agent"

[persona]
file = "qa_persona.md"
disable_resume = true

[[model_config.providers]]
provider = "openai"
model_name = "gpt-4o"
token = "${OPENAI_API_KEY}"

[[notification.slack]]
webhook_url = "https://hooks.slack.com/triggers/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"

[messenger.agui]
port = 9876
