// Copyright (C) StackGen, Inc. All rights reserved.
// SPDX-License-Identifier: BUSL-1.1
//
// Use of this source code is governed by the Business Source License 1.1
// included in the LICENSE-BSL file at the root of this repository.
//
// Change Date: 2029-03-10
// Change License: Apache License, Version 2.0

// Code generated by counterfeiter. DO NOT EDIT.
package halguardfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/halguard"
)

type FakeGuard struct {
	PostCheckStub        func(context.Context, halguard.PostCheckRequest) (halguard.VerificationResult, error)
	postCheckMutex       sync.RWMutex
	postCheckArgsForCall []struct {
		arg1 context.Context
		arg2 halguard.PostCheckRequest
	}
	postCheckReturns struct {
		result1 halguard.VerificationResult
		result2 error
	}
	postCheckReturnsOnCall map[int]struct {
		result1 halguard.VerificationResult
		result2 error
	}
	PreCheckStub        func(context.Context, halguard.PreCheckRequest) (halguard.PreCheckResult, error)
	preCheckMutex       sync.RWMutex
	preCheckArgsForCall []struct {
		arg1 context.Context
		arg2 halguard.PreCheckRequest
	}
	preCheckReturns struct {
		result1 halguard.PreCheckResult
		result2 error
	}
	preCheckReturnsOnCall map[int]struct {
		result1 halguard.PreCheckResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGuard) PostCheck(arg1 context.Context, arg2 halguard.PostCheckRequest) (halguard.VerificationResult, error) {
	fake.postCheckMutex.Lock()
	ret, specificReturn := fake.postCheckReturnsOnCall[len(fake.postCheckArgsForCall)]
	fake.postCheckArgsForCall = append(fake.postCheckArgsForCall, struct {
		arg1 context.Context
		arg2 halguard.PostCheckRequest
	}{arg1, arg2})
	stub := fake.PostCheckStub
	fakeReturns := fake.postCheckReturns
	fake.recordInvocation("PostCheck", []interface{}{arg1, arg2})
	fake.postCheckMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGuard) PostCheckCallCount() int {
	fake.postCheckMutex.RLock()
	defer fake.postCheckMutex.RUnlock()
	return len(fake.postCheckArgsForCall)
}

func (fake *FakeGuard) PostCheckCalls(stub func(context.Context, halguard.PostCheckRequest) (halguard.VerificationResult, error)) {
	fake.postCheckMutex.Lock()
	defer fake.postCheckMutex.Unlock()
	fake.PostCheckStub = stub
}

func (fake *FakeGuard) PostCheckArgsForCall(i int) (context.Context, halguard.PostCheckRequest) {
	fake.postCheckMutex.RLock()
	defer fake.postCheckMutex.RUnlock()
	argsForCall := fake.postCheckArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGuard) PostCheckReturns(result1 halguard.VerificationResult, result2 error) {
	fake.postCheckMutex.Lock()
	defer fake.postCheckMutex.Unlock()
	fake.PostCheckStub = nil
	fake.postCheckReturns = struct {
		result1 halguard.VerificationResult
		result2 error
	}{result1, result2}
}

func (fake *FakeGuard) PostCheckReturnsOnCall(i int, result1 halguard.VerificationResult, result2 error) {
	fake.postCheckMutex.Lock()
	defer fake.postCheckMutex.Unlock()
	fake.PostCheckStub = nil
	if fake.postCheckReturnsOnCall == nil {
		fake.postCheckReturnsOnCall = make(map[int]struct {
			result1 halguard.VerificationResult
			result2 error
		})
	}
	fake.postCheckReturnsOnCall[i] = struct {
		result1 halguard.VerificationResult
		result2 error
	}{result1, result2}
}

func (fake *FakeGuard) PreCheck(arg1 context.Context, arg2 halguard.PreCheckRequest) (halguard.PreCheckResult, error) {
	fake.preCheckMutex.Lock()
	ret, specificReturn := fake.preCheckReturnsOnCall[len(fake.preCheckArgsForCall)]
	fake.preCheckArgsForCall = append(fake.preCheckArgsForCall, struct {
		arg1 context.Context
		arg2 halguard.PreCheckRequest
	}{arg1, arg2})
	stub := fake.PreCheckStub
	fakeReturns := fake.preCheckReturns
	fake.recordInvocation("PreCheck", []interface{}{arg1, arg2})
	fake.preCheckMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGuard) PreCheckCallCount() int {
	fake.preCheckMutex.RLock()
	defer fake.preCheckMutex.RUnlock()
	return len(fake.preCheckArgsForCall)
}

func (fake *FakeGuard) PreCheckCalls(stub func(context.Context, halguard.PreCheckRequest) (halguard.PreCheckResult, error)) {
	fake.preCheckMutex.Lock()
	defer fake.preCheckMutex.Unlock()
	fake.PreCheckStub = stub
}

func (fake *FakeGuard) PreCheckArgsForCall(i int) (context.Context, halguard.PreCheckRequest) {
	fake.preCheckMutex.RLock()
	defer fake.preCheckMutex.RUnlock()
	argsForCall := fake.preCheckArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeGuard) PreCheckReturns(result1 halguard.PreCheckResult, result2 error) {
	fake.preCheckMutex.Lock()
	defer fake.preCheckMutex.Unlock()
	fake.PreCheckStub = nil
	fake.preCheckReturns = struct {
		result1 halguard.PreCheckResult
		result2 error
	}{result1, result2}
}

func (fake *FakeGuard) PreCheckReturnsOnCall(i int, result1 halguard.PreCheckResult, result2 error) {
	fake.preCheckMutex.Lock()
	defer fake.preCheckMutex.Unlock()
	fake.PreCheckStub = nil
	if fake.preCheckReturnsOnCall == nil {
		fake.preCheckReturnsOnCall = make(map[int]struct {
			result1 halguard.PreCheckResult
			result2 error
		})
	}
	fake.preCheckReturnsOnCall[i] = struct {
		result1 halguard.PreCheckResult
		result2 error
	}{result1, result2}
}

func (fake *FakeGuard) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGuard) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ halguard.Guard = new(FakeGuard)
