// Copyright (C) 2026 StackGen, Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by counterfeiter. DO NOT EDIT.
package toolwrapfakes

import (
	"sync"

	"github.com/stackgenhq/genie/pkg/toolwrap"
)

type FakeMiddleware struct {
	WrapStub        func(toolwrap.Handler) toolwrap.Handler
	wrapMutex       sync.RWMutex
	wrapArgsForCall []struct {
		arg1 toolwrap.Handler
	}
	wrapReturns struct {
		result1 toolwrap.Handler
	}
	wrapReturnsOnCall map[int]struct {
		result1 toolwrap.Handler
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMiddleware) Wrap(arg1 toolwrap.Handler) toolwrap.Handler {
	fake.wrapMutex.Lock()
	ret, specificReturn := fake.wrapReturnsOnCall[len(fake.wrapArgsForCall)]
	fake.wrapArgsForCall = append(fake.wrapArgsForCall, struct {
		arg1 toolwrap.Handler
	}{arg1})
	stub := fake.WrapStub
	fakeReturns := fake.wrapReturns
	fake.recordInvocation("Wrap", []interface{}{arg1})
	fake.wrapMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMiddleware) WrapCallCount() int {
	fake.wrapMutex.RLock()
	defer fake.wrapMutex.RUnlock()
	return len(fake.wrapArgsForCall)
}

func (fake *FakeMiddleware) WrapCalls(stub func(toolwrap.Handler) toolwrap.Handler) {
	fake.wrapMutex.Lock()
	defer fake.wrapMutex.Unlock()
	fake.WrapStub = stub
}

func (fake *FakeMiddleware) WrapArgsForCall(i int) toolwrap.Handler {
	fake.wrapMutex.RLock()
	defer fake.wrapMutex.RUnlock()
	argsForCall := fake.wrapArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMiddleware) WrapReturns(result1 toolwrap.Handler) {
	fake.wrapMutex.Lock()
	defer fake.wrapMutex.Unlock()
	fake.WrapStub = nil
	fake.wrapReturns = struct {
		result1 toolwrap.Handler
	}{result1}
}

func (fake *FakeMiddleware) WrapReturnsOnCall(i int, result1 toolwrap.Handler) {
	fake.wrapMutex.Lock()
	defer fake.wrapMutex.Unlock()
	fake.WrapStub = nil
	if fake.wrapReturnsOnCall == nil {
		fake.wrapReturnsOnCall = make(map[int]struct {
			result1 toolwrap.Handler
		})
	}
	fake.wrapReturnsOnCall[i] = struct {
		result1 toolwrap.Handler
	}{result1}
}

func (fake *FakeMiddleware) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMiddleware) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ toolwrap.Middleware = new(FakeMiddleware)
