// Code generated by counterfeiter. DO NOT EDIT.
package mcpfakes

import (
	"context"
	"sync"

	mcpa "github.com/mark3labs/mcp-go/mcp"
	"github.com/stackgenhq/genie/pkg/mcp"
)

type FakeMCPCaller struct {
	CallToolStub        func(context.Context, mcpa.CallToolRequest) (*mcpa.CallToolResult, error)
	callToolMutex       sync.RWMutex
	callToolArgsForCall []struct {
		arg1 context.Context
		arg2 mcpa.CallToolRequest
	}
	callToolReturns struct {
		result1 *mcpa.CallToolResult
		result2 error
	}
	callToolReturnsOnCall map[int]struct {
		result1 *mcpa.CallToolResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMCPCaller) CallTool(arg1 context.Context, arg2 mcpa.CallToolRequest) (*mcpa.CallToolResult, error) {
	fake.callToolMutex.Lock()
	ret, specificReturn := fake.callToolReturnsOnCall[len(fake.callToolArgsForCall)]
	fake.callToolArgsForCall = append(fake.callToolArgsForCall, struct {
		arg1 context.Context
		arg2 mcpa.CallToolRequest
	}{arg1, arg2})
	stub := fake.CallToolStub
	fakeReturns := fake.callToolReturns
	fake.recordInvocation("CallTool", []interface{}{arg1, arg2})
	fake.callToolMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMCPCaller) CallToolCallCount() int {
	fake.callToolMutex.RLock()
	defer fake.callToolMutex.RUnlock()
	return len(fake.callToolArgsForCall)
}

func (fake *FakeMCPCaller) CallToolCalls(stub func(context.Context, mcpa.CallToolRequest) (*mcpa.CallToolResult, error)) {
	fake.callToolMutex.Lock()
	defer fake.callToolMutex.Unlock()
	fake.CallToolStub = stub
}

func (fake *FakeMCPCaller) CallToolArgsForCall(i int) (context.Context, mcpa.CallToolRequest) {
	fake.callToolMutex.RLock()
	defer fake.callToolMutex.RUnlock()
	argsForCall := fake.callToolArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMCPCaller) CallToolReturns(result1 *mcpa.CallToolResult, result2 error) {
	fake.callToolMutex.Lock()
	defer fake.callToolMutex.Unlock()
	fake.CallToolStub = nil
	fake.callToolReturns = struct {
		result1 *mcpa.CallToolResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMCPCaller) CallToolReturnsOnCall(i int, result1 *mcpa.CallToolResult, result2 error) {
	fake.callToolMutex.Lock()
	defer fake.callToolMutex.Unlock()
	fake.CallToolStub = nil
	if fake.callToolReturnsOnCall == nil {
		fake.callToolReturnsOnCall = make(map[int]struct {
			result1 *mcpa.CallToolResult
			result2 error
		})
	}
	fake.callToolReturnsOnCall[i] = struct {
		result1 *mcpa.CallToolResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMCPCaller) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMCPCaller) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ mcp.MCPCaller = new(FakeMCPCaller)
