// Code generated by counterfeiter. DO NOT EDIT.
package mcpfakes

import (
	"context"
	"sync"

	mcpa "github.com/mark3labs/mcp-go/mcp"
	"github.com/stackgenhq/genie/pkg/mcp"
)

type FakeMCPResourceReader struct {
	ListResourcesStub        func(context.Context, mcpa.ListResourcesRequest) (*mcpa.ListResourcesResult, error)
	listResourcesMutex       sync.RWMutex
	listResourcesArgsForCall []struct {
		arg1 context.Context
		arg2 mcpa.ListResourcesRequest
	}
	listResourcesReturns struct {
		result1 *mcpa.ListResourcesResult
		result2 error
	}
	listResourcesReturnsOnCall map[int]struct {
		result1 *mcpa.ListResourcesResult
		result2 error
	}
	ReadResourceStub        func(context.Context, mcpa.ReadResourceRequest) (*mcpa.ReadResourceResult, error)
	readResourceMutex       sync.RWMutex
	readResourceArgsForCall []struct {
		arg1 context.Context
		arg2 mcpa.ReadResourceRequest
	}
	readResourceReturns struct {
		result1 *mcpa.ReadResourceResult
		result2 error
	}
	readResourceReturnsOnCall map[int]struct {
		result1 *mcpa.ReadResourceResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMCPResourceReader) ListResources(arg1 context.Context, arg2 mcpa.ListResourcesRequest) (*mcpa.ListResourcesResult, error) {
	fake.listResourcesMutex.Lock()
	ret, specificReturn := fake.listResourcesReturnsOnCall[len(fake.listResourcesArgsForCall)]
	fake.listResourcesArgsForCall = append(fake.listResourcesArgsForCall, struct {
		arg1 context.Context
		arg2 mcpa.ListResourcesRequest
	}{arg1, arg2})
	stub := fake.ListResourcesStub
	fakeReturns := fake.listResourcesReturns
	fake.recordInvocation("ListResources", []interface{}{arg1, arg2})
	fake.listResourcesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMCPResourceReader) ListResourcesCallCount() int {
	fake.listResourcesMutex.RLock()
	defer fake.listResourcesMutex.RUnlock()
	return len(fake.listResourcesArgsForCall)
}

func (fake *FakeMCPResourceReader) ListResourcesCalls(stub func(context.Context, mcpa.ListResourcesRequest) (*mcpa.ListResourcesResult, error)) {
	fake.listResourcesMutex.Lock()
	defer fake.listResourcesMutex.Unlock()
	fake.ListResourcesStub = stub
}

func (fake *FakeMCPResourceReader) ListResourcesArgsForCall(i int) (context.Context, mcpa.ListResourcesRequest) {
	fake.listResourcesMutex.RLock()
	defer fake.listResourcesMutex.RUnlock()
	argsForCall := fake.listResourcesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMCPResourceReader) ListResourcesReturns(result1 *mcpa.ListResourcesResult, result2 error) {
	fake.listResourcesMutex.Lock()
	defer fake.listResourcesMutex.Unlock()
	fake.ListResourcesStub = nil
	fake.listResourcesReturns = struct {
		result1 *mcpa.ListResourcesResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMCPResourceReader) ListResourcesReturnsOnCall(i int, result1 *mcpa.ListResourcesResult, result2 error) {
	fake.listResourcesMutex.Lock()
	defer fake.listResourcesMutex.Unlock()
	fake.ListResourcesStub = nil
	if fake.listResourcesReturnsOnCall == nil {
		fake.listResourcesReturnsOnCall = make(map[int]struct {
			result1 *mcpa.ListResourcesResult
			result2 error
		})
	}
	fake.listResourcesReturnsOnCall[i] = struct {
		result1 *mcpa.ListResourcesResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMCPResourceReader) ReadResource(arg1 context.Context, arg2 mcpa.ReadResourceRequest) (*mcpa.ReadResourceResult, error) {
	fake.readResourceMutex.Lock()
	ret, specificReturn := fake.readResourceReturnsOnCall[len(fake.readResourceArgsForCall)]
	fake.readResourceArgsForCall = append(fake.readResourceArgsForCall, struct {
		arg1 context.Context
		arg2 mcpa.ReadResourceRequest
	}{arg1, arg2})
	stub := fake.ReadResourceStub
	fakeReturns := fake.readResourceReturns
	fake.recordInvocation("ReadResource", []interface{}{arg1, arg2})
	fake.readResourceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMCPResourceReader) ReadResourceCallCount() int {
	fake.readResourceMutex.RLock()
	defer fake.readResourceMutex.RUnlock()
	return len(fake.readResourceArgsForCall)
}

func (fake *FakeMCPResourceReader) ReadResourceCalls(stub func(context.Context, mcpa.ReadResourceRequest) (*mcpa.ReadResourceResult, error)) {
	fake.readResourceMutex.Lock()
	defer fake.readResourceMutex.Unlock()
	fake.ReadResourceStub = stub
}

func (fake *FakeMCPResourceReader) ReadResourceArgsForCall(i int) (context.Context, mcpa.ReadResourceRequest) {
	fake.readResourceMutex.RLock()
	defer fake.readResourceMutex.RUnlock()
	argsForCall := fake.readResourceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMCPResourceReader) ReadResourceReturns(result1 *mcpa.ReadResourceResult, result2 error) {
	fake.readResourceMutex.Lock()
	defer fake.readResourceMutex.Unlock()
	fake.ReadResourceStub = nil
	fake.readResourceReturns = struct {
		result1 *mcpa.ReadResourceResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMCPResourceReader) ReadResourceReturnsOnCall(i int, result1 *mcpa.ReadResourceResult, result2 error) {
	fake.readResourceMutex.Lock()
	defer fake.readResourceMutex.Unlock()
	fake.ReadResourceStub = nil
	if fake.readResourceReturnsOnCall == nil {
		fake.readResourceReturnsOnCall = make(map[int]struct {
			result1 *mcpa.ReadResourceResult
			result2 error
		})
	}
	fake.readResourceReturnsOnCall[i] = struct {
		result1 *mcpa.ReadResourceResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMCPResourceReader) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMCPResourceReader) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ mcp.MCPResourceReader = new(FakeMCPResourceReader)
