// Copyright (C) 2026 StackGen, Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by counterfeiter. DO NOT EDIT.
package scmfakes

import (
	"context"
	"sync"

	scma "github.com/drone/go-scm/scm"
	"github.com/stackgenhq/genie/pkg/tools/scm"
)

type FakeService struct {
	CreatePullRequestStub        func(context.Context, string, *scma.PullRequestInput) (*scma.PullRequest, error)
	createPullRequestMutex       sync.RWMutex
	createPullRequestArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 *scma.PullRequestInput
	}
	createPullRequestReturns struct {
		result1 *scma.PullRequest
		result2 error
	}
	createPullRequestReturnsOnCall map[int]struct {
		result1 *scma.PullRequest
		result2 error
	}
	CreatePullRequestCommentStub        func(context.Context, string, int, *scma.CommentInput) (*scma.Comment, error)
	createPullRequestCommentMutex       sync.RWMutex
	createPullRequestCommentArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
		arg4 *scma.CommentInput
	}
	createPullRequestCommentReturns struct {
		result1 *scma.Comment
		result2 error
	}
	createPullRequestCommentReturnsOnCall map[int]struct {
		result1 *scma.Comment
		result2 error
	}
	FindRepoStub        func(context.Context, string) (*scma.Repository, error)
	findRepoMutex       sync.RWMutex
	findRepoArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	findRepoReturns struct {
		result1 *scma.Repository
		result2 error
	}
	findRepoReturnsOnCall map[int]struct {
		result1 *scma.Repository
		result2 error
	}
	GetPullRequestStub        func(context.Context, string, int) (*scma.PullRequest, error)
	getPullRequestMutex       sync.RWMutex
	getPullRequestArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}
	getPullRequestReturns struct {
		result1 *scma.PullRequest
		result2 error
	}
	getPullRequestReturnsOnCall map[int]struct {
		result1 *scma.PullRequest
		result2 error
	}
	ListPullRequestChangesStub        func(context.Context, string, int, scma.ListOptions) ([]*scma.Change, error)
	listPullRequestChangesMutex       sync.RWMutex
	listPullRequestChangesArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
		arg4 scma.ListOptions
	}
	listPullRequestChangesReturns struct {
		result1 []*scma.Change
		result2 error
	}
	listPullRequestChangesReturnsOnCall map[int]struct {
		result1 []*scma.Change
		result2 error
	}
	ListPullRequestCommentsStub        func(context.Context, string, int, scma.ListOptions) ([]*scma.Comment, error)
	listPullRequestCommentsMutex       sync.RWMutex
	listPullRequestCommentsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
		arg4 scma.ListOptions
	}
	listPullRequestCommentsReturns struct {
		result1 []*scma.Comment
		result2 error
	}
	listPullRequestCommentsReturnsOnCall map[int]struct {
		result1 []*scma.Comment
		result2 error
	}
	ListPullRequestCommitsStub        func(context.Context, string, int, scma.ListOptions) ([]*scma.Commit, error)
	listPullRequestCommitsMutex       sync.RWMutex
	listPullRequestCommitsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
		arg4 scma.ListOptions
	}
	listPullRequestCommitsReturns struct {
		result1 []*scma.Commit
		result2 error
	}
	listPullRequestCommitsReturnsOnCall map[int]struct {
		result1 []*scma.Commit
		result2 error
	}
	ListPullRequestsStub        func(context.Context, string, scma.PullRequestListOptions) ([]*scma.PullRequest, error)
	listPullRequestsMutex       sync.RWMutex
	listPullRequestsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 scma.PullRequestListOptions
	}
	listPullRequestsReturns struct {
		result1 []*scma.PullRequest
		result2 error
	}
	listPullRequestsReturnsOnCall map[int]struct {
		result1 []*scma.PullRequest
		result2 error
	}
	ListReposStub        func(context.Context, scma.ListOptions) ([]*scma.Repository, error)
	listReposMutex       sync.RWMutex
	listReposArgsForCall []struct {
		arg1 context.Context
		arg2 scma.ListOptions
	}
	listReposReturns struct {
		result1 []*scma.Repository
		result2 error
	}
	listReposReturnsOnCall map[int]struct {
		result1 []*scma.Repository
		result2 error
	}
	MergePullRequestStub        func(context.Context, string, int) error
	mergePullRequestMutex       sync.RWMutex
	mergePullRequestArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}
	mergePullRequestReturns struct {
		result1 error
	}
	mergePullRequestReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateStub        func(context.Context) error
	validateMutex       sync.RWMutex
	validateArgsForCall []struct {
		arg1 context.Context
	}
	validateReturns struct {
		result1 error
	}
	validateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeService) CreatePullRequest(arg1 context.Context, arg2 string, arg3 *scma.PullRequestInput) (*scma.PullRequest, error) {
	fake.createPullRequestMutex.Lock()
	ret, specificReturn := fake.createPullRequestReturnsOnCall[len(fake.createPullRequestArgsForCall)]
	fake.createPullRequestArgsForCall = append(fake.createPullRequestArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 *scma.PullRequestInput
	}{arg1, arg2, arg3})
	stub := fake.CreatePullRequestStub
	fakeReturns := fake.createPullRequestReturns
	fake.recordInvocation("CreatePullRequest", []interface{}{arg1, arg2, arg3})
	fake.createPullRequestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) CreatePullRequestCallCount() int {
	fake.createPullRequestMutex.RLock()
	defer fake.createPullRequestMutex.RUnlock()
	return len(fake.createPullRequestArgsForCall)
}

func (fake *FakeService) CreatePullRequestCalls(stub func(context.Context, string, *scma.PullRequestInput) (*scma.PullRequest, error)) {
	fake.createPullRequestMutex.Lock()
	defer fake.createPullRequestMutex.Unlock()
	fake.CreatePullRequestStub = stub
}

func (fake *FakeService) CreatePullRequestArgsForCall(i int) (context.Context, string, *scma.PullRequestInput) {
	fake.createPullRequestMutex.RLock()
	defer fake.createPullRequestMutex.RUnlock()
	argsForCall := fake.createPullRequestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) CreatePullRequestReturns(result1 *scma.PullRequest, result2 error) {
	fake.createPullRequestMutex.Lock()
	defer fake.createPullRequestMutex.Unlock()
	fake.CreatePullRequestStub = nil
	fake.createPullRequestReturns = struct {
		result1 *scma.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeService) CreatePullRequestReturnsOnCall(i int, result1 *scma.PullRequest, result2 error) {
	fake.createPullRequestMutex.Lock()
	defer fake.createPullRequestMutex.Unlock()
	fake.CreatePullRequestStub = nil
	if fake.createPullRequestReturnsOnCall == nil {
		fake.createPullRequestReturnsOnCall = make(map[int]struct {
			result1 *scma.PullRequest
			result2 error
		})
	}
	fake.createPullRequestReturnsOnCall[i] = struct {
		result1 *scma.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeService) CreatePullRequestComment(arg1 context.Context, arg2 string, arg3 int, arg4 *scma.CommentInput) (*scma.Comment, error) {
	fake.createPullRequestCommentMutex.Lock()
	ret, specificReturn := fake.createPullRequestCommentReturnsOnCall[len(fake.createPullRequestCommentArgsForCall)]
	fake.createPullRequestCommentArgsForCall = append(fake.createPullRequestCommentArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
		arg4 *scma.CommentInput
	}{arg1, arg2, arg3, arg4})
	stub := fake.CreatePullRequestCommentStub
	fakeReturns := fake.createPullRequestCommentReturns
	fake.recordInvocation("CreatePullRequestComment", []interface{}{arg1, arg2, arg3, arg4})
	fake.createPullRequestCommentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) CreatePullRequestCommentCallCount() int {
	fake.createPullRequestCommentMutex.RLock()
	defer fake.createPullRequestCommentMutex.RUnlock()
	return len(fake.createPullRequestCommentArgsForCall)
}

func (fake *FakeService) CreatePullRequestCommentCalls(stub func(context.Context, string, int, *scma.CommentInput) (*scma.Comment, error)) {
	fake.createPullRequestCommentMutex.Lock()
	defer fake.createPullRequestCommentMutex.Unlock()
	fake.CreatePullRequestCommentStub = stub
}

func (fake *FakeService) CreatePullRequestCommentArgsForCall(i int) (context.Context, string, int, *scma.CommentInput) {
	fake.createPullRequestCommentMutex.RLock()
	defer fake.createPullRequestCommentMutex.RUnlock()
	argsForCall := fake.createPullRequestCommentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeService) CreatePullRequestCommentReturns(result1 *scma.Comment, result2 error) {
	fake.createPullRequestCommentMutex.Lock()
	defer fake.createPullRequestCommentMutex.Unlock()
	fake.CreatePullRequestCommentStub = nil
	fake.createPullRequestCommentReturns = struct {
		result1 *scma.Comment
		result2 error
	}{result1, result2}
}

func (fake *FakeService) CreatePullRequestCommentReturnsOnCall(i int, result1 *scma.Comment, result2 error) {
	fake.createPullRequestCommentMutex.Lock()
	defer fake.createPullRequestCommentMutex.Unlock()
	fake.CreatePullRequestCommentStub = nil
	if fake.createPullRequestCommentReturnsOnCall == nil {
		fake.createPullRequestCommentReturnsOnCall = make(map[int]struct {
			result1 *scma.Comment
			result2 error
		})
	}
	fake.createPullRequestCommentReturnsOnCall[i] = struct {
		result1 *scma.Comment
		result2 error
	}{result1, result2}
}

func (fake *FakeService) FindRepo(arg1 context.Context, arg2 string) (*scma.Repository, error) {
	fake.findRepoMutex.Lock()
	ret, specificReturn := fake.findRepoReturnsOnCall[len(fake.findRepoArgsForCall)]
	fake.findRepoArgsForCall = append(fake.findRepoArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.FindRepoStub
	fakeReturns := fake.findRepoReturns
	fake.recordInvocation("FindRepo", []interface{}{arg1, arg2})
	fake.findRepoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) FindRepoCallCount() int {
	fake.findRepoMutex.RLock()
	defer fake.findRepoMutex.RUnlock()
	return len(fake.findRepoArgsForCall)
}

func (fake *FakeService) FindRepoCalls(stub func(context.Context, string) (*scma.Repository, error)) {
	fake.findRepoMutex.Lock()
	defer fake.findRepoMutex.Unlock()
	fake.FindRepoStub = stub
}

func (fake *FakeService) FindRepoArgsForCall(i int) (context.Context, string) {
	fake.findRepoMutex.RLock()
	defer fake.findRepoMutex.RUnlock()
	argsForCall := fake.findRepoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) FindRepoReturns(result1 *scma.Repository, result2 error) {
	fake.findRepoMutex.Lock()
	defer fake.findRepoMutex.Unlock()
	fake.FindRepoStub = nil
	fake.findRepoReturns = struct {
		result1 *scma.Repository
		result2 error
	}{result1, result2}
}

func (fake *FakeService) FindRepoReturnsOnCall(i int, result1 *scma.Repository, result2 error) {
	fake.findRepoMutex.Lock()
	defer fake.findRepoMutex.Unlock()
	fake.FindRepoStub = nil
	if fake.findRepoReturnsOnCall == nil {
		fake.findRepoReturnsOnCall = make(map[int]struct {
			result1 *scma.Repository
			result2 error
		})
	}
	fake.findRepoReturnsOnCall[i] = struct {
		result1 *scma.Repository
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetPullRequest(arg1 context.Context, arg2 string, arg3 int) (*scma.PullRequest, error) {
	fake.getPullRequestMutex.Lock()
	ret, specificReturn := fake.getPullRequestReturnsOnCall[len(fake.getPullRequestArgsForCall)]
	fake.getPullRequestArgsForCall = append(fake.getPullRequestArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.GetPullRequestStub
	fakeReturns := fake.getPullRequestReturns
	fake.recordInvocation("GetPullRequest", []interface{}{arg1, arg2, arg3})
	fake.getPullRequestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) GetPullRequestCallCount() int {
	fake.getPullRequestMutex.RLock()
	defer fake.getPullRequestMutex.RUnlock()
	return len(fake.getPullRequestArgsForCall)
}

func (fake *FakeService) GetPullRequestCalls(stub func(context.Context, string, int) (*scma.PullRequest, error)) {
	fake.getPullRequestMutex.Lock()
	defer fake.getPullRequestMutex.Unlock()
	fake.GetPullRequestStub = stub
}

func (fake *FakeService) GetPullRequestArgsForCall(i int) (context.Context, string, int) {
	fake.getPullRequestMutex.RLock()
	defer fake.getPullRequestMutex.RUnlock()
	argsForCall := fake.getPullRequestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) GetPullRequestReturns(result1 *scma.PullRequest, result2 error) {
	fake.getPullRequestMutex.Lock()
	defer fake.getPullRequestMutex.Unlock()
	fake.GetPullRequestStub = nil
	fake.getPullRequestReturns = struct {
		result1 *scma.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetPullRequestReturnsOnCall(i int, result1 *scma.PullRequest, result2 error) {
	fake.getPullRequestMutex.Lock()
	defer fake.getPullRequestMutex.Unlock()
	fake.GetPullRequestStub = nil
	if fake.getPullRequestReturnsOnCall == nil {
		fake.getPullRequestReturnsOnCall = make(map[int]struct {
			result1 *scma.PullRequest
			result2 error
		})
	}
	fake.getPullRequestReturnsOnCall[i] = struct {
		result1 *scma.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListPullRequestChanges(arg1 context.Context, arg2 string, arg3 int, arg4 scma.ListOptions) ([]*scma.Change, error) {
	fake.listPullRequestChangesMutex.Lock()
	ret, specificReturn := fake.listPullRequestChangesReturnsOnCall[len(fake.listPullRequestChangesArgsForCall)]
	fake.listPullRequestChangesArgsForCall = append(fake.listPullRequestChangesArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
		arg4 scma.ListOptions
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListPullRequestChangesStub
	fakeReturns := fake.listPullRequestChangesReturns
	fake.recordInvocation("ListPullRequestChanges", []interface{}{arg1, arg2, arg3, arg4})
	fake.listPullRequestChangesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ListPullRequestChangesCallCount() int {
	fake.listPullRequestChangesMutex.RLock()
	defer fake.listPullRequestChangesMutex.RUnlock()
	return len(fake.listPullRequestChangesArgsForCall)
}

func (fake *FakeService) ListPullRequestChangesCalls(stub func(context.Context, string, int, scma.ListOptions) ([]*scma.Change, error)) {
	fake.listPullRequestChangesMutex.Lock()
	defer fake.listPullRequestChangesMutex.Unlock()
	fake.ListPullRequestChangesStub = stub
}

func (fake *FakeService) ListPullRequestChangesArgsForCall(i int) (context.Context, string, int, scma.ListOptions) {
	fake.listPullRequestChangesMutex.RLock()
	defer fake.listPullRequestChangesMutex.RUnlock()
	argsForCall := fake.listPullRequestChangesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeService) ListPullRequestChangesReturns(result1 []*scma.Change, result2 error) {
	fake.listPullRequestChangesMutex.Lock()
	defer fake.listPullRequestChangesMutex.Unlock()
	fake.ListPullRequestChangesStub = nil
	fake.listPullRequestChangesReturns = struct {
		result1 []*scma.Change
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListPullRequestChangesReturnsOnCall(i int, result1 []*scma.Change, result2 error) {
	fake.listPullRequestChangesMutex.Lock()
	defer fake.listPullRequestChangesMutex.Unlock()
	fake.ListPullRequestChangesStub = nil
	if fake.listPullRequestChangesReturnsOnCall == nil {
		fake.listPullRequestChangesReturnsOnCall = make(map[int]struct {
			result1 []*scma.Change
			result2 error
		})
	}
	fake.listPullRequestChangesReturnsOnCall[i] = struct {
		result1 []*scma.Change
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListPullRequestComments(arg1 context.Context, arg2 string, arg3 int, arg4 scma.ListOptions) ([]*scma.Comment, error) {
	fake.listPullRequestCommentsMutex.Lock()
	ret, specificReturn := fake.listPullRequestCommentsReturnsOnCall[len(fake.listPullRequestCommentsArgsForCall)]
	fake.listPullRequestCommentsArgsForCall = append(fake.listPullRequestCommentsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
		arg4 scma.ListOptions
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListPullRequestCommentsStub
	fakeReturns := fake.listPullRequestCommentsReturns
	fake.recordInvocation("ListPullRequestComments", []interface{}{arg1, arg2, arg3, arg4})
	fake.listPullRequestCommentsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ListPullRequestCommentsCallCount() int {
	fake.listPullRequestCommentsMutex.RLock()
	defer fake.listPullRequestCommentsMutex.RUnlock()
	return len(fake.listPullRequestCommentsArgsForCall)
}

func (fake *FakeService) ListPullRequestCommentsCalls(stub func(context.Context, string, int, scma.ListOptions) ([]*scma.Comment, error)) {
	fake.listPullRequestCommentsMutex.Lock()
	defer fake.listPullRequestCommentsMutex.Unlock()
	fake.ListPullRequestCommentsStub = stub
}

func (fake *FakeService) ListPullRequestCommentsArgsForCall(i int) (context.Context, string, int, scma.ListOptions) {
	fake.listPullRequestCommentsMutex.RLock()
	defer fake.listPullRequestCommentsMutex.RUnlock()
	argsForCall := fake.listPullRequestCommentsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeService) ListPullRequestCommentsReturns(result1 []*scma.Comment, result2 error) {
	fake.listPullRequestCommentsMutex.Lock()
	defer fake.listPullRequestCommentsMutex.Unlock()
	fake.ListPullRequestCommentsStub = nil
	fake.listPullRequestCommentsReturns = struct {
		result1 []*scma.Comment
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListPullRequestCommentsReturnsOnCall(i int, result1 []*scma.Comment, result2 error) {
	fake.listPullRequestCommentsMutex.Lock()
	defer fake.listPullRequestCommentsMutex.Unlock()
	fake.ListPullRequestCommentsStub = nil
	if fake.listPullRequestCommentsReturnsOnCall == nil {
		fake.listPullRequestCommentsReturnsOnCall = make(map[int]struct {
			result1 []*scma.Comment
			result2 error
		})
	}
	fake.listPullRequestCommentsReturnsOnCall[i] = struct {
		result1 []*scma.Comment
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListPullRequestCommits(arg1 context.Context, arg2 string, arg3 int, arg4 scma.ListOptions) ([]*scma.Commit, error) {
	fake.listPullRequestCommitsMutex.Lock()
	ret, specificReturn := fake.listPullRequestCommitsReturnsOnCall[len(fake.listPullRequestCommitsArgsForCall)]
	fake.listPullRequestCommitsArgsForCall = append(fake.listPullRequestCommitsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
		arg4 scma.ListOptions
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListPullRequestCommitsStub
	fakeReturns := fake.listPullRequestCommitsReturns
	fake.recordInvocation("ListPullRequestCommits", []interface{}{arg1, arg2, arg3, arg4})
	fake.listPullRequestCommitsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ListPullRequestCommitsCallCount() int {
	fake.listPullRequestCommitsMutex.RLock()
	defer fake.listPullRequestCommitsMutex.RUnlock()
	return len(fake.listPullRequestCommitsArgsForCall)
}

func (fake *FakeService) ListPullRequestCommitsCalls(stub func(context.Context, string, int, scma.ListOptions) ([]*scma.Commit, error)) {
	fake.listPullRequestCommitsMutex.Lock()
	defer fake.listPullRequestCommitsMutex.Unlock()
	fake.ListPullRequestCommitsStub = stub
}

func (fake *FakeService) ListPullRequestCommitsArgsForCall(i int) (context.Context, string, int, scma.ListOptions) {
	fake.listPullRequestCommitsMutex.RLock()
	defer fake.listPullRequestCommitsMutex.RUnlock()
	argsForCall := fake.listPullRequestCommitsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeService) ListPullRequestCommitsReturns(result1 []*scma.Commit, result2 error) {
	fake.listPullRequestCommitsMutex.Lock()
	defer fake.listPullRequestCommitsMutex.Unlock()
	fake.ListPullRequestCommitsStub = nil
	fake.listPullRequestCommitsReturns = struct {
		result1 []*scma.Commit
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListPullRequestCommitsReturnsOnCall(i int, result1 []*scma.Commit, result2 error) {
	fake.listPullRequestCommitsMutex.Lock()
	defer fake.listPullRequestCommitsMutex.Unlock()
	fake.ListPullRequestCommitsStub = nil
	if fake.listPullRequestCommitsReturnsOnCall == nil {
		fake.listPullRequestCommitsReturnsOnCall = make(map[int]struct {
			result1 []*scma.Commit
			result2 error
		})
	}
	fake.listPullRequestCommitsReturnsOnCall[i] = struct {
		result1 []*scma.Commit
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListPullRequests(arg1 context.Context, arg2 string, arg3 scma.PullRequestListOptions) ([]*scma.PullRequest, error) {
	fake.listPullRequestsMutex.Lock()
	ret, specificReturn := fake.listPullRequestsReturnsOnCall[len(fake.listPullRequestsArgsForCall)]
	fake.listPullRequestsArgsForCall = append(fake.listPullRequestsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 scma.PullRequestListOptions
	}{arg1, arg2, arg3})
	stub := fake.ListPullRequestsStub
	fakeReturns := fake.listPullRequestsReturns
	fake.recordInvocation("ListPullRequests", []interface{}{arg1, arg2, arg3})
	fake.listPullRequestsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ListPullRequestsCallCount() int {
	fake.listPullRequestsMutex.RLock()
	defer fake.listPullRequestsMutex.RUnlock()
	return len(fake.listPullRequestsArgsForCall)
}

func (fake *FakeService) ListPullRequestsCalls(stub func(context.Context, string, scma.PullRequestListOptions) ([]*scma.PullRequest, error)) {
	fake.listPullRequestsMutex.Lock()
	defer fake.listPullRequestsMutex.Unlock()
	fake.ListPullRequestsStub = stub
}

func (fake *FakeService) ListPullRequestsArgsForCall(i int) (context.Context, string, scma.PullRequestListOptions) {
	fake.listPullRequestsMutex.RLock()
	defer fake.listPullRequestsMutex.RUnlock()
	argsForCall := fake.listPullRequestsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) ListPullRequestsReturns(result1 []*scma.PullRequest, result2 error) {
	fake.listPullRequestsMutex.Lock()
	defer fake.listPullRequestsMutex.Unlock()
	fake.ListPullRequestsStub = nil
	fake.listPullRequestsReturns = struct {
		result1 []*scma.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListPullRequestsReturnsOnCall(i int, result1 []*scma.PullRequest, result2 error) {
	fake.listPullRequestsMutex.Lock()
	defer fake.listPullRequestsMutex.Unlock()
	fake.ListPullRequestsStub = nil
	if fake.listPullRequestsReturnsOnCall == nil {
		fake.listPullRequestsReturnsOnCall = make(map[int]struct {
			result1 []*scma.PullRequest
			result2 error
		})
	}
	fake.listPullRequestsReturnsOnCall[i] = struct {
		result1 []*scma.PullRequest
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListRepos(arg1 context.Context, arg2 scma.ListOptions) ([]*scma.Repository, error) {
	fake.listReposMutex.Lock()
	ret, specificReturn := fake.listReposReturnsOnCall[len(fake.listReposArgsForCall)]
	fake.listReposArgsForCall = append(fake.listReposArgsForCall, struct {
		arg1 context.Context
		arg2 scma.ListOptions
	}{arg1, arg2})
	stub := fake.ListReposStub
	fakeReturns := fake.listReposReturns
	fake.recordInvocation("ListRepos", []interface{}{arg1, arg2})
	fake.listReposMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ListReposCallCount() int {
	fake.listReposMutex.RLock()
	defer fake.listReposMutex.RUnlock()
	return len(fake.listReposArgsForCall)
}

func (fake *FakeService) ListReposCalls(stub func(context.Context, scma.ListOptions) ([]*scma.Repository, error)) {
	fake.listReposMutex.Lock()
	defer fake.listReposMutex.Unlock()
	fake.ListReposStub = stub
}

func (fake *FakeService) ListReposArgsForCall(i int) (context.Context, scma.ListOptions) {
	fake.listReposMutex.RLock()
	defer fake.listReposMutex.RUnlock()
	argsForCall := fake.listReposArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) ListReposReturns(result1 []*scma.Repository, result2 error) {
	fake.listReposMutex.Lock()
	defer fake.listReposMutex.Unlock()
	fake.ListReposStub = nil
	fake.listReposReturns = struct {
		result1 []*scma.Repository
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListReposReturnsOnCall(i int, result1 []*scma.Repository, result2 error) {
	fake.listReposMutex.Lock()
	defer fake.listReposMutex.Unlock()
	fake.ListReposStub = nil
	if fake.listReposReturnsOnCall == nil {
		fake.listReposReturnsOnCall = make(map[int]struct {
			result1 []*scma.Repository
			result2 error
		})
	}
	fake.listReposReturnsOnCall[i] = struct {
		result1 []*scma.Repository
		result2 error
	}{result1, result2}
}

func (fake *FakeService) MergePullRequest(arg1 context.Context, arg2 string, arg3 int) error {
	fake.mergePullRequestMutex.Lock()
	ret, specificReturn := fake.mergePullRequestReturnsOnCall[len(fake.mergePullRequestArgsForCall)]
	fake.mergePullRequestArgsForCall = append(fake.mergePullRequestArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.MergePullRequestStub
	fakeReturns := fake.mergePullRequestReturns
	fake.recordInvocation("MergePullRequest", []interface{}{arg1, arg2, arg3})
	fake.mergePullRequestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) MergePullRequestCallCount() int {
	fake.mergePullRequestMutex.RLock()
	defer fake.mergePullRequestMutex.RUnlock()
	return len(fake.mergePullRequestArgsForCall)
}

func (fake *FakeService) MergePullRequestCalls(stub func(context.Context, string, int) error) {
	fake.mergePullRequestMutex.Lock()
	defer fake.mergePullRequestMutex.Unlock()
	fake.MergePullRequestStub = stub
}

func (fake *FakeService) MergePullRequestArgsForCall(i int) (context.Context, string, int) {
	fake.mergePullRequestMutex.RLock()
	defer fake.mergePullRequestMutex.RUnlock()
	argsForCall := fake.mergePullRequestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) MergePullRequestReturns(result1 error) {
	fake.mergePullRequestMutex.Lock()
	defer fake.mergePullRequestMutex.Unlock()
	fake.MergePullRequestStub = nil
	fake.mergePullRequestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) MergePullRequestReturnsOnCall(i int, result1 error) {
	fake.mergePullRequestMutex.Lock()
	defer fake.mergePullRequestMutex.Unlock()
	fake.MergePullRequestStub = nil
	if fake.mergePullRequestReturnsOnCall == nil {
		fake.mergePullRequestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.mergePullRequestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) Validate(arg1 context.Context) error {
	fake.validateMutex.Lock()
	ret, specificReturn := fake.validateReturnsOnCall[len(fake.validateArgsForCall)]
	fake.validateArgsForCall = append(fake.validateArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ValidateStub
	fakeReturns := fake.validateReturns
	fake.recordInvocation("Validate", []interface{}{arg1})
	fake.validateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) ValidateCallCount() int {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	return len(fake.validateArgsForCall)
}

func (fake *FakeService) ValidateCalls(stub func(context.Context) error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = stub
}

func (fake *FakeService) ValidateArgsForCall(i int) context.Context {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	argsForCall := fake.validateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) ValidateReturns(result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	fake.validateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) ValidateReturnsOnCall(i int, result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	if fake.validateReturnsOnCall == nil {
		fake.validateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ scm.Service = new(FakeService)
