// Copyright (C) 2026 StackGen, Inc. All rights reserved.
// SPDX-License-Identifier: BUSL-1.1
//
// Use of this source code is governed by the Business Source License 1.1
// included in the LICENSE-BSL file at the root of this repository.
//

package memory

import (
	"context"
	"encoding/json"
	"fmt"
	"math"
	"sort"
	"time"

	"trpc.group/trpc-go/trpc-agent-go/memory"
	"trpc.group/trpc-go/trpc-agent-go/memory/inmemory"
)

// EpisodeStatus records how an agent node terminated.
type EpisodeStatus string

const (
	// EpisodeSuccess means the agent completed its subgoal.
	EpisodeSuccess EpisodeStatus = "success"
	// EpisodeFailure means the agent failed its subgoal.
	EpisodeFailure EpisodeStatus = "failure"
	// EpisodeExpand means the agent decomposed into sub-tasks.
	EpisodeExpand EpisodeStatus = "expand"
	// EpisodePending means the episode is awaiting human validation.
	// Episodes are initially stored as pending until a user reacts
	// (e.g. 👍 upgrades to success, 👎 downgrades to failure).
	EpisodePending EpisodeStatus = "pending"
)

// Episode records a single subgoal-level experience for episodic memory.
// Each episode stores the goal, the full text trajectory, and the termination status.
// This granularity enables targeted in-context example retrieval per the paper.
type Episode struct {
	Goal       string        `json:"goal"`
	Trajectory string        `json:"trajectory"`
	Status     EpisodeStatus `json:"status"`

	// Reflection is a verbal summary of why the episode succeeded or failed.
	// For failures, this is generated by the FailureReflector. For successes,
	// this is typically empty (the trajectory serves as the reference).
	Reflection string `json:"reflection,omitempty"`

	// Importance is an LLM-assigned 1-10 score indicating how significant
	// this experience is. Higher scores indicate novel or critical lessons.
	// Zero means no importance was assigned (backward-compatible default).
	Importance int `json:"importance,omitempty"`

	// CreatedAt records when the episode was stored. Used for recency-weighted
	// retrieval: newer episodes receive higher scores via exponential decay.
	CreatedAt time.Time `json:"created_at"`
}

// episodeTopicPrefix is used to tag episodes with their status in memory.Service topics.
const episodeTopicPrefix = "reactree:episode:"

//go:generate go tool counterfeiter -generate

// EpisodicMemory stores and retrieves past subgoal-level experiences.
// Implementations can use embedding similarity (e.g., Sentence-BERT)
// to find the most relevant past experiences for a given goal.
//
//counterfeiter:generate . EpisodicMemory
type EpisodicMemory interface {
	// Store saves a completed episode into the memory.
	Store(ctx context.Context, episode Episode)

	// Retrieve finds the top-k most similar episodes for the given goal.
	Retrieve(ctx context.Context, goal string, k int) []Episode

	// RetrieveWeighted finds episodes for the given goal and ranks them
	// using a weighted score combining recency (exponential decay) and
	// importance. Returns the top-k highest-scoring episodes.
	RetrieveWeighted(ctx context.Context, goal string, k int) []Episode
}

// serviceEpisodicMemory delegates to trpc-agent-go's memory.Service.
// Episodes are serialized as JSON content with the goal as the search key.
// The status is stored as a topic for potential filtering.
type serviceEpisodicMemory struct {
	svc     memory.Service
	userKey memory.UserKey
}

// EpisodicMemoryConfig holds configuration for creating a memory.Service-backed
// EpisodicMemory implementation.
type EpisodicMemoryConfig struct {
	// Service is the trpc-agent-go memory.Service backend.
	Service memory.Service

	// AppName identifies the application for memory scoping.
	AppName string

	// UserID identifies the user/session for memory scoping.
	UserID string
}

// WithUserID returns a copy of the config with the UserID set to the given value.
// This enables creating per-sender episodic memory from a shared base config.
func (cfg EpisodicMemoryConfig) WithUserID(userID string) EpisodicMemoryConfig {
	cfg.UserID = userID
	return cfg
}

func DefaultEpisodicMemoryConfig() EpisodicMemoryConfig {
	return EpisodicMemoryConfig{
		AppName: "reactree",
		UserID:  "default",
		Service: inmemory.NewMemoryService(),
	}
}

// NewServiceEpisodicMemory creates an EpisodicMemory backed by memory.Service.
// Episodes are stored as JSON-serialized content and searched by goal text.
func (cfg EpisodicMemoryConfig) NewEpisodicMemory() EpisodicMemory {
	return &serviceEpisodicMemory{
		svc: cfg.Service,
		userKey: memory.UserKey{
			AppName: cfg.AppName,
			UserID:  cfg.UserID,
		},
	}
}

// Store serializes the episode as JSON and calls memory.Service.AddMemory.
// The episode status is passed as a topic for downstream filtering.
// If CreatedAt is zero, it is set to the current time.
func (s *serviceEpisodicMemory) Store(ctx context.Context, episode Episode) {
	if episode.CreatedAt.IsZero() {
		episode.CreatedAt = time.Now()
	}

	content, err := json.Marshal(episode)
	if err != nil {
		return // Best-effort; don't fail the tree run for a memory write error
	}

	topics := []string{
		episodeTopicPrefix + string(episode.Status),
	}

	_ = s.svc.AddMemory(ctx, s.userKey, string(content), topics)
}

// Retrieve searches memory.Service with the goal text and deserializes
// matching entries back into Episode structs.
func (s *serviceEpisodicMemory) Retrieve(ctx context.Context, goal string, k int) []Episode {
	return s.retrieveEpisodes(ctx, goal, k, false)
}

// RetrieveWeighted searches for episodes and ranks them using a weighted
// score combining recency decay and importance.
func (s *serviceEpisodicMemory) RetrieveWeighted(ctx context.Context, goal string, k int) []Episode {
	return s.retrieveEpisodes(ctx, goal, k, true)
}

// retrieveEpisodes is the shared implementation for Retrieve and RetrieveWeighted.
// When weighted is true, episodes are scored and sorted using a weighted sum
// (0.6*recency + 0.4*importance).
func (s *serviceEpisodicMemory) retrieveEpisodes(ctx context.Context, goal string, k int, weighted bool) []Episode {
	entries, err := s.svc.SearchMemories(ctx, s.userKey, goal)
	if err != nil || len(entries) == 0 {
		return nil
	}

	// Parse all matching entries into episodes (don't limit yet for weighted scoring).
	episodes := make([]Episode, 0, len(entries))
	for _, entry := range entries {
		if entry == nil || entry.Memory == nil {
			continue
		}

		var ep Episode
		if err := json.Unmarshal([]byte(entry.Memory.Memory), &ep); err != nil {
			// Fallback: treat the raw memory content as the trajectory
			ep = Episode{
				Goal:       goal,
				Trajectory: entry.Memory.Memory,
				Status:     statusFromTopics(entry.Memory.Topics),
			}
		}

		// Backfill CreatedAt from memory.Entry if the episode was stored
		// before the CreatedAt field was added.
		if ep.CreatedAt.IsZero() && entry.CreatedAt != (time.Time{}) {
			ep.CreatedAt = entry.CreatedAt
		}

		episodes = append(episodes, ep)
	}

	if !weighted {
		if len(episodes) > k {
			episodes = episodes[:k]
		}
		return episodes
	}

	// Weighted scoring: sort using a weighted sum of recency and importance, return top-k.
	now := time.Now()
	scoreEpisode := func(ep Episode) float64 {
		recency := recencyScore(now, ep.CreatedAt)
		importance := normalizedImportance(ep.Importance)
		// Combined score: 60% recency + 40% importance.
		// Recency dominates so recent failures/successes are prioritized,
		// but high-importance episodes still surface even when older.
		return 0.6*recency + 0.4*importance
	}

	sort.Slice(episodes, func(i, j int) bool {
		return scoreEpisode(episodes[i]) > scoreEpisode(episodes[j])
	})

	if len(episodes) > k {
		episodes = episodes[:k]
	}
	return episodes
}

// statusFromTopics extracts the EpisodeStatus from memory topics.
func statusFromTopics(topics []string) EpisodeStatus {
	for _, t := range topics {
		if len(t) > len(episodeTopicPrefix) {
			status := EpisodeStatus(t[len(episodeTopicPrefix):])
			switch status {
			case EpisodeSuccess, EpisodeFailure, EpisodeExpand, EpisodePending:
				return status
			}
		}
	}
	return EpisodeSuccess // Default
}

// noOpEpisodicMemory is a true no-op implementation of EpisodicMemory.
// Store is a no-op and Retrieve/RetrieveWeighted always return nil.
type noOpEpisodicMemory struct{}

func (noOpEpisodicMemory) Store(_ context.Context, _ Episode)                    {}
func (noOpEpisodicMemory) Retrieve(_ context.Context, _ string, _ int) []Episode { return nil }
func (noOpEpisodicMemory) RetrieveWeighted(_ context.Context, _ string, _ int) []Episode {
	return nil
}

// NewNoOpEpisodicMemory creates an episodic memory that does nothing.
// Store is a no-op and Retrieve/RetrieveWeighted always return nil. This is
// suitable for initial use cases that don't yet have an experience corpus,
// and avoids the overhead of constructing a real memory.Service backend.
func NewNoOpEpisodicMemory() EpisodicMemory {
	return noOpEpisodicMemory{}
}

// String formats an episode for inclusion in an LLM prompt.
// Failure episodes include the reflection; successes show the trajectory.
func (ep Episode) String() string {
	if ep.Status == EpisodeFailure && ep.Reflection != "" {
		return fmt.Sprintf("### ⚠️ Previous Failure: %s\n%s", ep.Goal, ep.Reflection)
	}
	return fmt.Sprintf("### Goal: %s (outcome: %s)\n%s", ep.Goal, ep.Status, ep.Trajectory)
}

// recencyDecayRate controls how fast episodes lose relevance over time.
// With λ=0.01, an episode decays to:
//   - 79% after 1 day (24h)
//   - 49% after 3 days
//   - 19% after 7 days
//   - 3% after 14 days
//   - ~0% after 30 days
const recencyDecayRate = 0.01

// recencyScore computes an exponential decay score for an episode based on
// how many hours have elapsed since it was created. Score is in [0, 1].
func recencyScore(now time.Time, createdAt time.Time) float64 {
	if createdAt.IsZero() {
		return 0.5 // Unknown age → neutral score
	}
	hours := now.Sub(createdAt).Hours()
	if hours < 0 {
		hours = 0
	}
	return math.Exp(-recencyDecayRate * hours)
}

// normalizedImportance converts a 1-10 importance score to a [0, 1] float.
// Zero importance (unscored) is treated as a neutral 0.5.
func normalizedImportance(importance int) float64 {
	if importance <= 0 {
		return 0.5 // Unscored episodes get a neutral weight
	}
	if importance > 10 {
		importance = 10
	}
	return float64(importance) / 10.0
}
