// Code generated by counterfeiter. DO NOT EDIT.
package slacktoolsfakes

import (
	"context"
	"sync"

	"github.com/appcd-dev/genie/pkg/tools/slacktools"
)

type FakeService struct {
	GetChannelInfoStub        func(context.Context, string) (*slacktools.ChannelInfo, error)
	getChannelInfoMutex       sync.RWMutex
	getChannelInfoArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getChannelInfoReturns struct {
		result1 *slacktools.ChannelInfo
		result2 error
	}
	getChannelInfoReturnsOnCall map[int]struct {
		result1 *slacktools.ChannelInfo
		result2 error
	}
	ListChannelsStub        func(context.Context, int) ([]slacktools.ChannelInfo, error)
	listChannelsMutex       sync.RWMutex
	listChannelsArgsForCall []struct {
		arg1 context.Context
		arg2 int
	}
	listChannelsReturns struct {
		result1 []slacktools.ChannelInfo
		result2 error
	}
	listChannelsReturnsOnCall map[int]struct {
		result1 []slacktools.ChannelInfo
		result2 error
	}
	ListUsersStub        func(context.Context) ([]slacktools.UserInfo, error)
	listUsersMutex       sync.RWMutex
	listUsersArgsForCall []struct {
		arg1 context.Context
	}
	listUsersReturns struct {
		result1 []slacktools.UserInfo
		result2 error
	}
	listUsersReturnsOnCall map[int]struct {
		result1 []slacktools.UserInfo
		result2 error
	}
	PostMessageStub        func(context.Context, string, string) error
	postMessageMutex       sync.RWMutex
	postMessageArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	postMessageReturns struct {
		result1 error
	}
	postMessageReturnsOnCall map[int]struct {
		result1 error
	}
	ReadChannelHistoryStub        func(context.Context, string, int) ([]slacktools.Message, error)
	readChannelHistoryMutex       sync.RWMutex
	readChannelHistoryArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}
	readChannelHistoryReturns struct {
		result1 []slacktools.Message
		result2 error
	}
	readChannelHistoryReturnsOnCall map[int]struct {
		result1 []slacktools.Message
		result2 error
	}
	SearchMessagesStub        func(context.Context, string, int) ([]slacktools.MessageResult, error)
	searchMessagesMutex       sync.RWMutex
	searchMessagesArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}
	searchMessagesReturns struct {
		result1 []slacktools.MessageResult
		result2 error
	}
	searchMessagesReturnsOnCall map[int]struct {
		result1 []slacktools.MessageResult
		result2 error
	}
	ValidateStub        func(context.Context) error
	validateMutex       sync.RWMutex
	validateArgsForCall []struct {
		arg1 context.Context
	}
	validateReturns struct {
		result1 error
	}
	validateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeService) GetChannelInfo(arg1 context.Context, arg2 string) (*slacktools.ChannelInfo, error) {
	fake.getChannelInfoMutex.Lock()
	ret, specificReturn := fake.getChannelInfoReturnsOnCall[len(fake.getChannelInfoArgsForCall)]
	fake.getChannelInfoArgsForCall = append(fake.getChannelInfoArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetChannelInfoStub
	fakeReturns := fake.getChannelInfoReturns
	fake.recordInvocation("GetChannelInfo", []interface{}{arg1, arg2})
	fake.getChannelInfoMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) GetChannelInfoCallCount() int {
	fake.getChannelInfoMutex.RLock()
	defer fake.getChannelInfoMutex.RUnlock()
	return len(fake.getChannelInfoArgsForCall)
}

func (fake *FakeService) GetChannelInfoCalls(stub func(context.Context, string) (*slacktools.ChannelInfo, error)) {
	fake.getChannelInfoMutex.Lock()
	defer fake.getChannelInfoMutex.Unlock()
	fake.GetChannelInfoStub = stub
}

func (fake *FakeService) GetChannelInfoArgsForCall(i int) (context.Context, string) {
	fake.getChannelInfoMutex.RLock()
	defer fake.getChannelInfoMutex.RUnlock()
	argsForCall := fake.getChannelInfoArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) GetChannelInfoReturns(result1 *slacktools.ChannelInfo, result2 error) {
	fake.getChannelInfoMutex.Lock()
	defer fake.getChannelInfoMutex.Unlock()
	fake.GetChannelInfoStub = nil
	fake.getChannelInfoReturns = struct {
		result1 *slacktools.ChannelInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetChannelInfoReturnsOnCall(i int, result1 *slacktools.ChannelInfo, result2 error) {
	fake.getChannelInfoMutex.Lock()
	defer fake.getChannelInfoMutex.Unlock()
	fake.GetChannelInfoStub = nil
	if fake.getChannelInfoReturnsOnCall == nil {
		fake.getChannelInfoReturnsOnCall = make(map[int]struct {
			result1 *slacktools.ChannelInfo
			result2 error
		})
	}
	fake.getChannelInfoReturnsOnCall[i] = struct {
		result1 *slacktools.ChannelInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListChannels(arg1 context.Context, arg2 int) ([]slacktools.ChannelInfo, error) {
	fake.listChannelsMutex.Lock()
	ret, specificReturn := fake.listChannelsReturnsOnCall[len(fake.listChannelsArgsForCall)]
	fake.listChannelsArgsForCall = append(fake.listChannelsArgsForCall, struct {
		arg1 context.Context
		arg2 int
	}{arg1, arg2})
	stub := fake.ListChannelsStub
	fakeReturns := fake.listChannelsReturns
	fake.recordInvocation("ListChannels", []interface{}{arg1, arg2})
	fake.listChannelsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ListChannelsCallCount() int {
	fake.listChannelsMutex.RLock()
	defer fake.listChannelsMutex.RUnlock()
	return len(fake.listChannelsArgsForCall)
}

func (fake *FakeService) ListChannelsCalls(stub func(context.Context, int) ([]slacktools.ChannelInfo, error)) {
	fake.listChannelsMutex.Lock()
	defer fake.listChannelsMutex.Unlock()
	fake.ListChannelsStub = stub
}

func (fake *FakeService) ListChannelsArgsForCall(i int) (context.Context, int) {
	fake.listChannelsMutex.RLock()
	defer fake.listChannelsMutex.RUnlock()
	argsForCall := fake.listChannelsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) ListChannelsReturns(result1 []slacktools.ChannelInfo, result2 error) {
	fake.listChannelsMutex.Lock()
	defer fake.listChannelsMutex.Unlock()
	fake.ListChannelsStub = nil
	fake.listChannelsReturns = struct {
		result1 []slacktools.ChannelInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListChannelsReturnsOnCall(i int, result1 []slacktools.ChannelInfo, result2 error) {
	fake.listChannelsMutex.Lock()
	defer fake.listChannelsMutex.Unlock()
	fake.ListChannelsStub = nil
	if fake.listChannelsReturnsOnCall == nil {
		fake.listChannelsReturnsOnCall = make(map[int]struct {
			result1 []slacktools.ChannelInfo
			result2 error
		})
	}
	fake.listChannelsReturnsOnCall[i] = struct {
		result1 []slacktools.ChannelInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListUsers(arg1 context.Context) ([]slacktools.UserInfo, error) {
	fake.listUsersMutex.Lock()
	ret, specificReturn := fake.listUsersReturnsOnCall[len(fake.listUsersArgsForCall)]
	fake.listUsersArgsForCall = append(fake.listUsersArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ListUsersStub
	fakeReturns := fake.listUsersReturns
	fake.recordInvocation("ListUsers", []interface{}{arg1})
	fake.listUsersMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ListUsersCallCount() int {
	fake.listUsersMutex.RLock()
	defer fake.listUsersMutex.RUnlock()
	return len(fake.listUsersArgsForCall)
}

func (fake *FakeService) ListUsersCalls(stub func(context.Context) ([]slacktools.UserInfo, error)) {
	fake.listUsersMutex.Lock()
	defer fake.listUsersMutex.Unlock()
	fake.ListUsersStub = stub
}

func (fake *FakeService) ListUsersArgsForCall(i int) context.Context {
	fake.listUsersMutex.RLock()
	defer fake.listUsersMutex.RUnlock()
	argsForCall := fake.listUsersArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) ListUsersReturns(result1 []slacktools.UserInfo, result2 error) {
	fake.listUsersMutex.Lock()
	defer fake.listUsersMutex.Unlock()
	fake.ListUsersStub = nil
	fake.listUsersReturns = struct {
		result1 []slacktools.UserInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListUsersReturnsOnCall(i int, result1 []slacktools.UserInfo, result2 error) {
	fake.listUsersMutex.Lock()
	defer fake.listUsersMutex.Unlock()
	fake.ListUsersStub = nil
	if fake.listUsersReturnsOnCall == nil {
		fake.listUsersReturnsOnCall = make(map[int]struct {
			result1 []slacktools.UserInfo
			result2 error
		})
	}
	fake.listUsersReturnsOnCall[i] = struct {
		result1 []slacktools.UserInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeService) PostMessage(arg1 context.Context, arg2 string, arg3 string) error {
	fake.postMessageMutex.Lock()
	ret, specificReturn := fake.postMessageReturnsOnCall[len(fake.postMessageArgsForCall)]
	fake.postMessageArgsForCall = append(fake.postMessageArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.PostMessageStub
	fakeReturns := fake.postMessageReturns
	fake.recordInvocation("PostMessage", []interface{}{arg1, arg2, arg3})
	fake.postMessageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) PostMessageCallCount() int {
	fake.postMessageMutex.RLock()
	defer fake.postMessageMutex.RUnlock()
	return len(fake.postMessageArgsForCall)
}

func (fake *FakeService) PostMessageCalls(stub func(context.Context, string, string) error) {
	fake.postMessageMutex.Lock()
	defer fake.postMessageMutex.Unlock()
	fake.PostMessageStub = stub
}

func (fake *FakeService) PostMessageArgsForCall(i int) (context.Context, string, string) {
	fake.postMessageMutex.RLock()
	defer fake.postMessageMutex.RUnlock()
	argsForCall := fake.postMessageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) PostMessageReturns(result1 error) {
	fake.postMessageMutex.Lock()
	defer fake.postMessageMutex.Unlock()
	fake.PostMessageStub = nil
	fake.postMessageReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) PostMessageReturnsOnCall(i int, result1 error) {
	fake.postMessageMutex.Lock()
	defer fake.postMessageMutex.Unlock()
	fake.PostMessageStub = nil
	if fake.postMessageReturnsOnCall == nil {
		fake.postMessageReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.postMessageReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) ReadChannelHistory(arg1 context.Context, arg2 string, arg3 int) ([]slacktools.Message, error) {
	fake.readChannelHistoryMutex.Lock()
	ret, specificReturn := fake.readChannelHistoryReturnsOnCall[len(fake.readChannelHistoryArgsForCall)]
	fake.readChannelHistoryArgsForCall = append(fake.readChannelHistoryArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.ReadChannelHistoryStub
	fakeReturns := fake.readChannelHistoryReturns
	fake.recordInvocation("ReadChannelHistory", []interface{}{arg1, arg2, arg3})
	fake.readChannelHistoryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ReadChannelHistoryCallCount() int {
	fake.readChannelHistoryMutex.RLock()
	defer fake.readChannelHistoryMutex.RUnlock()
	return len(fake.readChannelHistoryArgsForCall)
}

func (fake *FakeService) ReadChannelHistoryCalls(stub func(context.Context, string, int) ([]slacktools.Message, error)) {
	fake.readChannelHistoryMutex.Lock()
	defer fake.readChannelHistoryMutex.Unlock()
	fake.ReadChannelHistoryStub = stub
}

func (fake *FakeService) ReadChannelHistoryArgsForCall(i int) (context.Context, string, int) {
	fake.readChannelHistoryMutex.RLock()
	defer fake.readChannelHistoryMutex.RUnlock()
	argsForCall := fake.readChannelHistoryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) ReadChannelHistoryReturns(result1 []slacktools.Message, result2 error) {
	fake.readChannelHistoryMutex.Lock()
	defer fake.readChannelHistoryMutex.Unlock()
	fake.ReadChannelHistoryStub = nil
	fake.readChannelHistoryReturns = struct {
		result1 []slacktools.Message
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ReadChannelHistoryReturnsOnCall(i int, result1 []slacktools.Message, result2 error) {
	fake.readChannelHistoryMutex.Lock()
	defer fake.readChannelHistoryMutex.Unlock()
	fake.ReadChannelHistoryStub = nil
	if fake.readChannelHistoryReturnsOnCall == nil {
		fake.readChannelHistoryReturnsOnCall = make(map[int]struct {
			result1 []slacktools.Message
			result2 error
		})
	}
	fake.readChannelHistoryReturnsOnCall[i] = struct {
		result1 []slacktools.Message
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SearchMessages(arg1 context.Context, arg2 string, arg3 int) ([]slacktools.MessageResult, error) {
	fake.searchMessagesMutex.Lock()
	ret, specificReturn := fake.searchMessagesReturnsOnCall[len(fake.searchMessagesArgsForCall)]
	fake.searchMessagesArgsForCall = append(fake.searchMessagesArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.SearchMessagesStub
	fakeReturns := fake.searchMessagesReturns
	fake.recordInvocation("SearchMessages", []interface{}{arg1, arg2, arg3})
	fake.searchMessagesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) SearchMessagesCallCount() int {
	fake.searchMessagesMutex.RLock()
	defer fake.searchMessagesMutex.RUnlock()
	return len(fake.searchMessagesArgsForCall)
}

func (fake *FakeService) SearchMessagesCalls(stub func(context.Context, string, int) ([]slacktools.MessageResult, error)) {
	fake.searchMessagesMutex.Lock()
	defer fake.searchMessagesMutex.Unlock()
	fake.SearchMessagesStub = stub
}

func (fake *FakeService) SearchMessagesArgsForCall(i int) (context.Context, string, int) {
	fake.searchMessagesMutex.RLock()
	defer fake.searchMessagesMutex.RUnlock()
	argsForCall := fake.searchMessagesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) SearchMessagesReturns(result1 []slacktools.MessageResult, result2 error) {
	fake.searchMessagesMutex.Lock()
	defer fake.searchMessagesMutex.Unlock()
	fake.SearchMessagesStub = nil
	fake.searchMessagesReturns = struct {
		result1 []slacktools.MessageResult
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SearchMessagesReturnsOnCall(i int, result1 []slacktools.MessageResult, result2 error) {
	fake.searchMessagesMutex.Lock()
	defer fake.searchMessagesMutex.Unlock()
	fake.SearchMessagesStub = nil
	if fake.searchMessagesReturnsOnCall == nil {
		fake.searchMessagesReturnsOnCall = make(map[int]struct {
			result1 []slacktools.MessageResult
			result2 error
		})
	}
	fake.searchMessagesReturnsOnCall[i] = struct {
		result1 []slacktools.MessageResult
		result2 error
	}{result1, result2}
}

func (fake *FakeService) Validate(arg1 context.Context) error {
	fake.validateMutex.Lock()
	ret, specificReturn := fake.validateReturnsOnCall[len(fake.validateArgsForCall)]
	fake.validateArgsForCall = append(fake.validateArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ValidateStub
	fakeReturns := fake.validateReturns
	fake.recordInvocation("Validate", []interface{}{arg1})
	fake.validateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) ValidateCallCount() int {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	return len(fake.validateArgsForCall)
}

func (fake *FakeService) ValidateCalls(stub func(context.Context) error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = stub
}

func (fake *FakeService) ValidateArgsForCall(i int) context.Context {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	argsForCall := fake.validateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) ValidateReturns(result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	fake.validateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) ValidateReturnsOnCall(i int, result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	if fake.validateReturnsOnCall == nil {
		fake.validateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ slacktools.Service = new(FakeService)
