// Code generated by counterfeiter. DO NOT EDIT.
package memoryfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/reactree/memory"
)

type FakeEpisodeSummarizer struct {
	SummarizeStub        func(context.Context, []memory.Episode) string
	summarizeMutex       sync.RWMutex
	summarizeArgsForCall []struct {
		arg1 context.Context
		arg2 []memory.Episode
	}
	summarizeReturns struct {
		result1 string
	}
	summarizeReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeEpisodeSummarizer) Summarize(arg1 context.Context, arg2 []memory.Episode) string {
	var arg2Copy []memory.Episode
	if arg2 != nil {
		arg2Copy = make([]memory.Episode, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.summarizeMutex.Lock()
	ret, specificReturn := fake.summarizeReturnsOnCall[len(fake.summarizeArgsForCall)]
	fake.summarizeArgsForCall = append(fake.summarizeArgsForCall, struct {
		arg1 context.Context
		arg2 []memory.Episode
	}{arg1, arg2Copy})
	stub := fake.SummarizeStub
	fakeReturns := fake.summarizeReturns
	fake.recordInvocation("Summarize", []interface{}{arg1, arg2Copy})
	fake.summarizeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeEpisodeSummarizer) SummarizeCallCount() int {
	fake.summarizeMutex.RLock()
	defer fake.summarizeMutex.RUnlock()
	return len(fake.summarizeArgsForCall)
}

func (fake *FakeEpisodeSummarizer) SummarizeCalls(stub func(context.Context, []memory.Episode) string) {
	fake.summarizeMutex.Lock()
	defer fake.summarizeMutex.Unlock()
	fake.SummarizeStub = stub
}

func (fake *FakeEpisodeSummarizer) SummarizeArgsForCall(i int) (context.Context, []memory.Episode) {
	fake.summarizeMutex.RLock()
	defer fake.summarizeMutex.RUnlock()
	argsForCall := fake.summarizeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeEpisodeSummarizer) SummarizeReturns(result1 string) {
	fake.summarizeMutex.Lock()
	defer fake.summarizeMutex.Unlock()
	fake.SummarizeStub = nil
	fake.summarizeReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeEpisodeSummarizer) SummarizeReturnsOnCall(i int, result1 string) {
	fake.summarizeMutex.Lock()
	defer fake.summarizeMutex.Unlock()
	fake.SummarizeStub = nil
	if fake.summarizeReturnsOnCall == nil {
		fake.summarizeReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.summarizeReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeEpisodeSummarizer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeEpisodeSummarizer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ memory.EpisodeSummarizer = new(FakeEpisodeSummarizer)
