// Copyright (C) StackGen, Inc. All rights reserved.
// SPDX-License-Identifier: BUSL-1.1
//
// Use of this source code is governed by the Business Source License 1.1
// included in the LICENSE-BSL file at the root of this repository.
//
// Change Date: 2029-03-10
// Change License: Apache License, Version 2.0

// Code generated by counterfeiter. DO NOT EDIT.
package memoryfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/reactree/memory"
)

type FakeEpisodicMemory struct {
	RetrieveStub        func(context.Context, string, int) []memory.Episode
	retrieveMutex       sync.RWMutex
	retrieveArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}
	retrieveReturns struct {
		result1 []memory.Episode
	}
	retrieveReturnsOnCall map[int]struct {
		result1 []memory.Episode
	}
	StoreStub        func(context.Context, memory.Episode)
	storeMutex       sync.RWMutex
	storeArgsForCall []struct {
		arg1 context.Context
		arg2 memory.Episode
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeEpisodicMemory) Retrieve(arg1 context.Context, arg2 string, arg3 int) []memory.Episode {
	fake.retrieveMutex.Lock()
	ret, specificReturn := fake.retrieveReturnsOnCall[len(fake.retrieveArgsForCall)]
	fake.retrieveArgsForCall = append(fake.retrieveArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.RetrieveStub
	fakeReturns := fake.retrieveReturns
	fake.recordInvocation("Retrieve", []interface{}{arg1, arg2, arg3})
	fake.retrieveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeEpisodicMemory) RetrieveCallCount() int {
	fake.retrieveMutex.RLock()
	defer fake.retrieveMutex.RUnlock()
	return len(fake.retrieveArgsForCall)
}

func (fake *FakeEpisodicMemory) RetrieveCalls(stub func(context.Context, string, int) []memory.Episode) {
	fake.retrieveMutex.Lock()
	defer fake.retrieveMutex.Unlock()
	fake.RetrieveStub = stub
}

func (fake *FakeEpisodicMemory) RetrieveArgsForCall(i int) (context.Context, string, int) {
	fake.retrieveMutex.RLock()
	defer fake.retrieveMutex.RUnlock()
	argsForCall := fake.retrieveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeEpisodicMemory) RetrieveReturns(result1 []memory.Episode) {
	fake.retrieveMutex.Lock()
	defer fake.retrieveMutex.Unlock()
	fake.RetrieveStub = nil
	fake.retrieveReturns = struct {
		result1 []memory.Episode
	}{result1}
}

func (fake *FakeEpisodicMemory) RetrieveReturnsOnCall(i int, result1 []memory.Episode) {
	fake.retrieveMutex.Lock()
	defer fake.retrieveMutex.Unlock()
	fake.RetrieveStub = nil
	if fake.retrieveReturnsOnCall == nil {
		fake.retrieveReturnsOnCall = make(map[int]struct {
			result1 []memory.Episode
		})
	}
	fake.retrieveReturnsOnCall[i] = struct {
		result1 []memory.Episode
	}{result1}
}

func (fake *FakeEpisodicMemory) Store(arg1 context.Context, arg2 memory.Episode) {
	fake.storeMutex.Lock()
	fake.storeArgsForCall = append(fake.storeArgsForCall, struct {
		arg1 context.Context
		arg2 memory.Episode
	}{arg1, arg2})
	stub := fake.StoreStub
	fake.recordInvocation("Store", []interface{}{arg1, arg2})
	fake.storeMutex.Unlock()
	if stub != nil {
		fake.StoreStub(arg1, arg2)
	}
}

func (fake *FakeEpisodicMemory) StoreCallCount() int {
	fake.storeMutex.RLock()
	defer fake.storeMutex.RUnlock()
	return len(fake.storeArgsForCall)
}

func (fake *FakeEpisodicMemory) StoreCalls(stub func(context.Context, memory.Episode)) {
	fake.storeMutex.Lock()
	defer fake.storeMutex.Unlock()
	fake.StoreStub = stub
}

func (fake *FakeEpisodicMemory) StoreArgsForCall(i int) (context.Context, memory.Episode) {
	fake.storeMutex.RLock()
	defer fake.storeMutex.RUnlock()
	argsForCall := fake.storeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeEpisodicMemory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeEpisodicMemory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ memory.EpisodicMemory = new(FakeEpisodicMemory)
