// Code generated by counterfeiter. DO NOT EDIT.
package memoryfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/reactree/memory"
)

type FakeWisdomStore struct {
	RetrieveWisdomStub        func(context.Context, int) []memory.WisdomNote
	retrieveWisdomMutex       sync.RWMutex
	retrieveWisdomArgsForCall []struct {
		arg1 context.Context
		arg2 int
	}
	retrieveWisdomReturns struct {
		result1 []memory.WisdomNote
	}
	retrieveWisdomReturnsOnCall map[int]struct {
		result1 []memory.WisdomNote
	}
	StoreWisdomStub        func(context.Context, memory.WisdomNote)
	storeWisdomMutex       sync.RWMutex
	storeWisdomArgsForCall []struct {
		arg1 context.Context
		arg2 memory.WisdomNote
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeWisdomStore) RetrieveWisdom(arg1 context.Context, arg2 int) []memory.WisdomNote {
	fake.retrieveWisdomMutex.Lock()
	ret, specificReturn := fake.retrieveWisdomReturnsOnCall[len(fake.retrieveWisdomArgsForCall)]
	fake.retrieveWisdomArgsForCall = append(fake.retrieveWisdomArgsForCall, struct {
		arg1 context.Context
		arg2 int
	}{arg1, arg2})
	stub := fake.RetrieveWisdomStub
	fakeReturns := fake.retrieveWisdomReturns
	fake.recordInvocation("RetrieveWisdom", []interface{}{arg1, arg2})
	fake.retrieveWisdomMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWisdomStore) RetrieveWisdomCallCount() int {
	fake.retrieveWisdomMutex.RLock()
	defer fake.retrieveWisdomMutex.RUnlock()
	return len(fake.retrieveWisdomArgsForCall)
}

func (fake *FakeWisdomStore) RetrieveWisdomCalls(stub func(context.Context, int) []memory.WisdomNote) {
	fake.retrieveWisdomMutex.Lock()
	defer fake.retrieveWisdomMutex.Unlock()
	fake.RetrieveWisdomStub = stub
}

func (fake *FakeWisdomStore) RetrieveWisdomArgsForCall(i int) (context.Context, int) {
	fake.retrieveWisdomMutex.RLock()
	defer fake.retrieveWisdomMutex.RUnlock()
	argsForCall := fake.retrieveWisdomArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeWisdomStore) RetrieveWisdomReturns(result1 []memory.WisdomNote) {
	fake.retrieveWisdomMutex.Lock()
	defer fake.retrieveWisdomMutex.Unlock()
	fake.RetrieveWisdomStub = nil
	fake.retrieveWisdomReturns = struct {
		result1 []memory.WisdomNote
	}{result1}
}

func (fake *FakeWisdomStore) RetrieveWisdomReturnsOnCall(i int, result1 []memory.WisdomNote) {
	fake.retrieveWisdomMutex.Lock()
	defer fake.retrieveWisdomMutex.Unlock()
	fake.RetrieveWisdomStub = nil
	if fake.retrieveWisdomReturnsOnCall == nil {
		fake.retrieveWisdomReturnsOnCall = make(map[int]struct {
			result1 []memory.WisdomNote
		})
	}
	fake.retrieveWisdomReturnsOnCall[i] = struct {
		result1 []memory.WisdomNote
	}{result1}
}

func (fake *FakeWisdomStore) StoreWisdom(arg1 context.Context, arg2 memory.WisdomNote) {
	fake.storeWisdomMutex.Lock()
	fake.storeWisdomArgsForCall = append(fake.storeWisdomArgsForCall, struct {
		arg1 context.Context
		arg2 memory.WisdomNote
	}{arg1, arg2})
	stub := fake.StoreWisdomStub
	fake.recordInvocation("StoreWisdom", []interface{}{arg1, arg2})
	fake.storeWisdomMutex.Unlock()
	if stub != nil {
		fake.StoreWisdomStub(arg1, arg2)
	}
}

func (fake *FakeWisdomStore) StoreWisdomCallCount() int {
	fake.storeWisdomMutex.RLock()
	defer fake.storeWisdomMutex.RUnlock()
	return len(fake.storeWisdomArgsForCall)
}

func (fake *FakeWisdomStore) StoreWisdomCalls(stub func(context.Context, memory.WisdomNote)) {
	fake.storeWisdomMutex.Lock()
	defer fake.storeWisdomMutex.Unlock()
	fake.StoreWisdomStub = stub
}

func (fake *FakeWisdomStore) StoreWisdomArgsForCall(i int) (context.Context, memory.WisdomNote) {
	fake.storeWisdomMutex.RLock()
	defer fake.storeWisdomMutex.RUnlock()
	argsForCall := fake.storeWisdomArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeWisdomStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeWisdomStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ memory.WisdomStore = new(FakeWisdomStore)
