// Code generated by counterfeiter. DO NOT EDIT.
package memoryfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/reactree/memory"
)

type FakePlanAdvisor struct {
	AdviseStub        func(context.Context, memory.PlanAdvisoryRequest) memory.PlanAdvisoryResult
	adviseMutex       sync.RWMutex
	adviseArgsForCall []struct {
		arg1 context.Context
		arg2 memory.PlanAdvisoryRequest
	}
	adviseReturns struct {
		result1 memory.PlanAdvisoryResult
	}
	adviseReturnsOnCall map[int]struct {
		result1 memory.PlanAdvisoryResult
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePlanAdvisor) Advise(arg1 context.Context, arg2 memory.PlanAdvisoryRequest) memory.PlanAdvisoryResult {
	fake.adviseMutex.Lock()
	ret, specificReturn := fake.adviseReturnsOnCall[len(fake.adviseArgsForCall)]
	fake.adviseArgsForCall = append(fake.adviseArgsForCall, struct {
		arg1 context.Context
		arg2 memory.PlanAdvisoryRequest
	}{arg1, arg2})
	stub := fake.AdviseStub
	fakeReturns := fake.adviseReturns
	fake.recordInvocation("Advise", []interface{}{arg1, arg2})
	fake.adviseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePlanAdvisor) AdviseCallCount() int {
	fake.adviseMutex.RLock()
	defer fake.adviseMutex.RUnlock()
	return len(fake.adviseArgsForCall)
}

func (fake *FakePlanAdvisor) AdviseCalls(stub func(context.Context, memory.PlanAdvisoryRequest) memory.PlanAdvisoryResult) {
	fake.adviseMutex.Lock()
	defer fake.adviseMutex.Unlock()
	fake.AdviseStub = stub
}

func (fake *FakePlanAdvisor) AdviseArgsForCall(i int) (context.Context, memory.PlanAdvisoryRequest) {
	fake.adviseMutex.RLock()
	defer fake.adviseMutex.RUnlock()
	argsForCall := fake.adviseArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePlanAdvisor) AdviseReturns(result1 memory.PlanAdvisoryResult) {
	fake.adviseMutex.Lock()
	defer fake.adviseMutex.Unlock()
	fake.AdviseStub = nil
	fake.adviseReturns = struct {
		result1 memory.PlanAdvisoryResult
	}{result1}
}

func (fake *FakePlanAdvisor) AdviseReturnsOnCall(i int, result1 memory.PlanAdvisoryResult) {
	fake.adviseMutex.Lock()
	defer fake.adviseMutex.Unlock()
	fake.AdviseStub = nil
	if fake.adviseReturnsOnCall == nil {
		fake.adviseReturnsOnCall = make(map[int]struct {
			result1 memory.PlanAdvisoryResult
		})
	}
	fake.adviseReturnsOnCall[i] = struct {
		result1 memory.PlanAdvisoryResult
	}{result1}
}

func (fake *FakePlanAdvisor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePlanAdvisor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ memory.PlanAdvisor = new(FakePlanAdvisor)
