// Code generated by counterfeiter. DO NOT EDIT.
package memoryfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/reactree/memory"
)

type FakeImportanceScorer struct {
	ScoreStub        func(context.Context, memory.ImportanceScoringRequest) int
	scoreMutex       sync.RWMutex
	scoreArgsForCall []struct {
		arg1 context.Context
		arg2 memory.ImportanceScoringRequest
	}
	scoreReturns struct {
		result1 int
	}
	scoreReturnsOnCall map[int]struct {
		result1 int
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeImportanceScorer) Score(arg1 context.Context, arg2 memory.ImportanceScoringRequest) int {
	fake.scoreMutex.Lock()
	ret, specificReturn := fake.scoreReturnsOnCall[len(fake.scoreArgsForCall)]
	fake.scoreArgsForCall = append(fake.scoreArgsForCall, struct {
		arg1 context.Context
		arg2 memory.ImportanceScoringRequest
	}{arg1, arg2})
	stub := fake.ScoreStub
	fakeReturns := fake.scoreReturns
	fake.recordInvocation("Score", []interface{}{arg1, arg2})
	fake.scoreMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImportanceScorer) ScoreCallCount() int {
	fake.scoreMutex.RLock()
	defer fake.scoreMutex.RUnlock()
	return len(fake.scoreArgsForCall)
}

func (fake *FakeImportanceScorer) ScoreCalls(stub func(context.Context, memory.ImportanceScoringRequest) int) {
	fake.scoreMutex.Lock()
	defer fake.scoreMutex.Unlock()
	fake.ScoreStub = stub
}

func (fake *FakeImportanceScorer) ScoreArgsForCall(i int) (context.Context, memory.ImportanceScoringRequest) {
	fake.scoreMutex.RLock()
	defer fake.scoreMutex.RUnlock()
	argsForCall := fake.scoreArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeImportanceScorer) ScoreReturns(result1 int) {
	fake.scoreMutex.Lock()
	defer fake.scoreMutex.Unlock()
	fake.ScoreStub = nil
	fake.scoreReturns = struct {
		result1 int
	}{result1}
}

func (fake *FakeImportanceScorer) ScoreReturnsOnCall(i int, result1 int) {
	fake.scoreMutex.Lock()
	defer fake.scoreMutex.Unlock()
	fake.ScoreStub = nil
	if fake.scoreReturnsOnCall == nil {
		fake.scoreReturnsOnCall = make(map[int]struct {
			result1 int
		})
	}
	fake.scoreReturnsOnCall[i] = struct {
		result1 int
	}{result1}
}

func (fake *FakeImportanceScorer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeImportanceScorer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ memory.ImportanceScorer = new(FakeImportanceScorer)
