// Code generated by counterfeiter. DO NOT EDIT.
package memoryfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/reactree/memory"
)

type FakeFailureReflector struct {
	ReflectStub        func(context.Context, memory.FailureReflectionRequest) string
	reflectMutex       sync.RWMutex
	reflectArgsForCall []struct {
		arg1 context.Context
		arg2 memory.FailureReflectionRequest
	}
	reflectReturns struct {
		result1 string
	}
	reflectReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFailureReflector) Reflect(arg1 context.Context, arg2 memory.FailureReflectionRequest) string {
	fake.reflectMutex.Lock()
	ret, specificReturn := fake.reflectReturnsOnCall[len(fake.reflectArgsForCall)]
	fake.reflectArgsForCall = append(fake.reflectArgsForCall, struct {
		arg1 context.Context
		arg2 memory.FailureReflectionRequest
	}{arg1, arg2})
	stub := fake.ReflectStub
	fakeReturns := fake.reflectReturns
	fake.recordInvocation("Reflect", []interface{}{arg1, arg2})
	fake.reflectMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFailureReflector) ReflectCallCount() int {
	fake.reflectMutex.RLock()
	defer fake.reflectMutex.RUnlock()
	return len(fake.reflectArgsForCall)
}

func (fake *FakeFailureReflector) ReflectCalls(stub func(context.Context, memory.FailureReflectionRequest) string) {
	fake.reflectMutex.Lock()
	defer fake.reflectMutex.Unlock()
	fake.ReflectStub = stub
}

func (fake *FakeFailureReflector) ReflectArgsForCall(i int) (context.Context, memory.FailureReflectionRequest) {
	fake.reflectMutex.RLock()
	defer fake.reflectMutex.RUnlock()
	argsForCall := fake.reflectArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeFailureReflector) ReflectReturns(result1 string) {
	fake.reflectMutex.Lock()
	defer fake.reflectMutex.Unlock()
	fake.ReflectStub = nil
	fake.reflectReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeFailureReflector) ReflectReturnsOnCall(i int, result1 string) {
	fake.reflectMutex.Lock()
	defer fake.reflectMutex.Unlock()
	fake.ReflectStub = nil
	if fake.reflectReturnsOnCall == nil {
		fake.reflectReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.reflectReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeFailureReflector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFailureReflector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ memory.FailureReflector = new(FakeFailureReflector)
