// Code generated by counterfeiter. DO NOT EDIT.
package expertfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/expert"
)

type FakeExpert struct {
	DoStub        func(context.Context, expert.Request) (expert.Response, error)
	doMutex       sync.RWMutex
	doArgsForCall []struct {
		arg1 context.Context
		arg2 expert.Request
	}
	doReturns struct {
		result1 expert.Response
		result2 error
	}
	doReturnsOnCall map[int]struct {
		result1 expert.Response
		result2 error
	}
	GetBioStub        func() expert.ExpertBio
	getBioMutex       sync.RWMutex
	getBioArgsForCall []struct {
	}
	getBioReturns struct {
		result1 expert.ExpertBio
	}
	getBioReturnsOnCall map[int]struct {
		result1 expert.ExpertBio
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeExpert) Do(arg1 context.Context, arg2 expert.Request) (expert.Response, error) {
	fake.doMutex.Lock()
	ret, specificReturn := fake.doReturnsOnCall[len(fake.doArgsForCall)]
	fake.doArgsForCall = append(fake.doArgsForCall, struct {
		arg1 context.Context
		arg2 expert.Request
	}{arg1, arg2})
	stub := fake.DoStub
	fakeReturns := fake.doReturns
	fake.recordInvocation("Do", []interface{}{arg1, arg2})
	fake.doMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeExpert) DoCallCount() int {
	fake.doMutex.RLock()
	defer fake.doMutex.RUnlock()
	return len(fake.doArgsForCall)
}

func (fake *FakeExpert) DoCalls(stub func(context.Context, expert.Request) (expert.Response, error)) {
	fake.doMutex.Lock()
	defer fake.doMutex.Unlock()
	fake.DoStub = stub
}

func (fake *FakeExpert) DoArgsForCall(i int) (context.Context, expert.Request) {
	fake.doMutex.RLock()
	defer fake.doMutex.RUnlock()
	argsForCall := fake.doArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeExpert) DoReturns(result1 expert.Response, result2 error) {
	fake.doMutex.Lock()
	defer fake.doMutex.Unlock()
	fake.DoStub = nil
	fake.doReturns = struct {
		result1 expert.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeExpert) DoReturnsOnCall(i int, result1 expert.Response, result2 error) {
	fake.doMutex.Lock()
	defer fake.doMutex.Unlock()
	fake.DoStub = nil
	if fake.doReturnsOnCall == nil {
		fake.doReturnsOnCall = make(map[int]struct {
			result1 expert.Response
			result2 error
		})
	}
	fake.doReturnsOnCall[i] = struct {
		result1 expert.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeExpert) GetBio() expert.ExpertBio {
	fake.getBioMutex.Lock()
	ret, specificReturn := fake.getBioReturnsOnCall[len(fake.getBioArgsForCall)]
	fake.getBioArgsForCall = append(fake.getBioArgsForCall, struct {
	}{})
	stub := fake.GetBioStub
	fakeReturns := fake.getBioReturns
	fake.recordInvocation("GetBio", []interface{}{})
	fake.getBioMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeExpert) GetBioCallCount() int {
	fake.getBioMutex.RLock()
	defer fake.getBioMutex.RUnlock()
	return len(fake.getBioArgsForCall)
}

func (fake *FakeExpert) GetBioCalls(stub func() expert.ExpertBio) {
	fake.getBioMutex.Lock()
	defer fake.getBioMutex.Unlock()
	fake.GetBioStub = stub
}

func (fake *FakeExpert) GetBioReturns(result1 expert.ExpertBio) {
	fake.getBioMutex.Lock()
	defer fake.getBioMutex.Unlock()
	fake.GetBioStub = nil
	fake.getBioReturns = struct {
		result1 expert.ExpertBio
	}{result1}
}

func (fake *FakeExpert) GetBioReturnsOnCall(i int, result1 expert.ExpertBio) {
	fake.getBioMutex.Lock()
	defer fake.getBioMutex.Unlock()
	fake.GetBioStub = nil
	if fake.getBioReturnsOnCall == nil {
		fake.getBioReturnsOnCall = make(map[int]struct {
			result1 expert.ExpertBio
		})
	}
	fake.getBioReturnsOnCall[i] = struct {
		result1 expert.ExpertBio
	}{result1}
}

func (fake *FakeExpert) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeExpert) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ expert.Expert = new(FakeExpert)
