// Code generated by counterfeiter. DO NOT EDIT.
package messengerfakes

import (
	"context"
	"sync"

	"github.com/appcd-dev/genie/pkg/messenger"
)

type FakeMessenger struct {
	ConnectStub        func(context.Context) error
	connectMutex       sync.RWMutex
	connectArgsForCall []struct {
		arg1 context.Context
	}
	connectReturns struct {
		result1 error
	}
	connectReturnsOnCall map[int]struct {
		result1 error
	}
	DisconnectStub        func(context.Context) error
	disconnectMutex       sync.RWMutex
	disconnectArgsForCall []struct {
		arg1 context.Context
	}
	disconnectReturns struct {
		result1 error
	}
	disconnectReturnsOnCall map[int]struct {
		result1 error
	}
	FormatApprovalStub        func(messenger.SendRequest, messenger.ApprovalInfo) messenger.SendRequest
	formatApprovalMutex       sync.RWMutex
	formatApprovalArgsForCall []struct {
		arg1 messenger.SendRequest
		arg2 messenger.ApprovalInfo
	}
	formatApprovalReturns struct {
		result1 messenger.SendRequest
	}
	formatApprovalReturnsOnCall map[int]struct {
		result1 messenger.SendRequest
	}
	FormatClarificationStub        func(messenger.SendRequest, messenger.ClarificationInfo) messenger.SendRequest
	formatClarificationMutex       sync.RWMutex
	formatClarificationArgsForCall []struct {
		arg1 messenger.SendRequest
		arg2 messenger.ClarificationInfo
	}
	formatClarificationReturns struct {
		result1 messenger.SendRequest
	}
	formatClarificationReturnsOnCall map[int]struct {
		result1 messenger.SendRequest
	}
	PlatformStub        func() messenger.Platform
	platformMutex       sync.RWMutex
	platformArgsForCall []struct {
	}
	platformReturns struct {
		result1 messenger.Platform
	}
	platformReturnsOnCall map[int]struct {
		result1 messenger.Platform
	}
	ReceiveStub        func(context.Context) (<-chan messenger.IncomingMessage, error)
	receiveMutex       sync.RWMutex
	receiveArgsForCall []struct {
		arg1 context.Context
	}
	receiveReturns struct {
		result1 <-chan messenger.IncomingMessage
		result2 error
	}
	receiveReturnsOnCall map[int]struct {
		result1 <-chan messenger.IncomingMessage
		result2 error
	}
	SendStub        func(context.Context, messenger.SendRequest) (messenger.SendResponse, error)
	sendMutex       sync.RWMutex
	sendArgsForCall []struct {
		arg1 context.Context
		arg2 messenger.SendRequest
	}
	sendReturns struct {
		result1 messenger.SendResponse
		result2 error
	}
	sendReturnsOnCall map[int]struct {
		result1 messenger.SendResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMessenger) Connect(arg1 context.Context) error {
	fake.connectMutex.Lock()
	ret, specificReturn := fake.connectReturnsOnCall[len(fake.connectArgsForCall)]
	fake.connectArgsForCall = append(fake.connectArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ConnectStub
	fakeReturns := fake.connectReturns
	fake.recordInvocation("Connect", []interface{}{arg1})
	fake.connectMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMessenger) ConnectCallCount() int {
	fake.connectMutex.RLock()
	defer fake.connectMutex.RUnlock()
	return len(fake.connectArgsForCall)
}

func (fake *FakeMessenger) ConnectCalls(stub func(context.Context) error) {
	fake.connectMutex.Lock()
	defer fake.connectMutex.Unlock()
	fake.ConnectStub = stub
}

func (fake *FakeMessenger) ConnectArgsForCall(i int) context.Context {
	fake.connectMutex.RLock()
	defer fake.connectMutex.RUnlock()
	argsForCall := fake.connectArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMessenger) ConnectReturns(result1 error) {
	fake.connectMutex.Lock()
	defer fake.connectMutex.Unlock()
	fake.ConnectStub = nil
	fake.connectReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMessenger) ConnectReturnsOnCall(i int, result1 error) {
	fake.connectMutex.Lock()
	defer fake.connectMutex.Unlock()
	fake.ConnectStub = nil
	if fake.connectReturnsOnCall == nil {
		fake.connectReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.connectReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMessenger) Disconnect(arg1 context.Context) error {
	fake.disconnectMutex.Lock()
	ret, specificReturn := fake.disconnectReturnsOnCall[len(fake.disconnectArgsForCall)]
	fake.disconnectArgsForCall = append(fake.disconnectArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.DisconnectStub
	fakeReturns := fake.disconnectReturns
	fake.recordInvocation("Disconnect", []interface{}{arg1})
	fake.disconnectMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMessenger) DisconnectCallCount() int {
	fake.disconnectMutex.RLock()
	defer fake.disconnectMutex.RUnlock()
	return len(fake.disconnectArgsForCall)
}

func (fake *FakeMessenger) DisconnectCalls(stub func(context.Context) error) {
	fake.disconnectMutex.Lock()
	defer fake.disconnectMutex.Unlock()
	fake.DisconnectStub = stub
}

func (fake *FakeMessenger) DisconnectArgsForCall(i int) context.Context {
	fake.disconnectMutex.RLock()
	defer fake.disconnectMutex.RUnlock()
	argsForCall := fake.disconnectArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMessenger) DisconnectReturns(result1 error) {
	fake.disconnectMutex.Lock()
	defer fake.disconnectMutex.Unlock()
	fake.DisconnectStub = nil
	fake.disconnectReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMessenger) DisconnectReturnsOnCall(i int, result1 error) {
	fake.disconnectMutex.Lock()
	defer fake.disconnectMutex.Unlock()
	fake.DisconnectStub = nil
	if fake.disconnectReturnsOnCall == nil {
		fake.disconnectReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.disconnectReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMessenger) FormatApproval(arg1 messenger.SendRequest, arg2 messenger.ApprovalInfo) messenger.SendRequest {
	fake.formatApprovalMutex.Lock()
	ret, specificReturn := fake.formatApprovalReturnsOnCall[len(fake.formatApprovalArgsForCall)]
	fake.formatApprovalArgsForCall = append(fake.formatApprovalArgsForCall, struct {
		arg1 messenger.SendRequest
		arg2 messenger.ApprovalInfo
	}{arg1, arg2})
	stub := fake.FormatApprovalStub
	fakeReturns := fake.formatApprovalReturns
	fake.recordInvocation("FormatApproval", []interface{}{arg1, arg2})
	fake.formatApprovalMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMessenger) FormatApprovalCallCount() int {
	fake.formatApprovalMutex.RLock()
	defer fake.formatApprovalMutex.RUnlock()
	return len(fake.formatApprovalArgsForCall)
}

func (fake *FakeMessenger) FormatApprovalCalls(stub func(messenger.SendRequest, messenger.ApprovalInfo) messenger.SendRequest) {
	fake.formatApprovalMutex.Lock()
	defer fake.formatApprovalMutex.Unlock()
	fake.FormatApprovalStub = stub
}

func (fake *FakeMessenger) FormatApprovalArgsForCall(i int) (messenger.SendRequest, messenger.ApprovalInfo) {
	fake.formatApprovalMutex.RLock()
	defer fake.formatApprovalMutex.RUnlock()
	argsForCall := fake.formatApprovalArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMessenger) FormatApprovalReturns(result1 messenger.SendRequest) {
	fake.formatApprovalMutex.Lock()
	defer fake.formatApprovalMutex.Unlock()
	fake.FormatApprovalStub = nil
	fake.formatApprovalReturns = struct {
		result1 messenger.SendRequest
	}{result1}
}

func (fake *FakeMessenger) FormatApprovalReturnsOnCall(i int, result1 messenger.SendRequest) {
	fake.formatApprovalMutex.Lock()
	defer fake.formatApprovalMutex.Unlock()
	fake.FormatApprovalStub = nil
	if fake.formatApprovalReturnsOnCall == nil {
		fake.formatApprovalReturnsOnCall = make(map[int]struct {
			result1 messenger.SendRequest
		})
	}
	fake.formatApprovalReturnsOnCall[i] = struct {
		result1 messenger.SendRequest
	}{result1}
}

func (fake *FakeMessenger) FormatClarification(arg1 messenger.SendRequest, arg2 messenger.ClarificationInfo) messenger.SendRequest {
	fake.formatClarificationMutex.Lock()
	ret, specificReturn := fake.formatClarificationReturnsOnCall[len(fake.formatClarificationArgsForCall)]
	fake.formatClarificationArgsForCall = append(fake.formatClarificationArgsForCall, struct {
		arg1 messenger.SendRequest
		arg2 messenger.ClarificationInfo
	}{arg1, arg2})
	stub := fake.FormatClarificationStub
	fakeReturns := fake.formatClarificationReturns
	fake.recordInvocation("FormatClarification", []interface{}{arg1, arg2})
	fake.formatClarificationMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMessenger) FormatClarificationCallCount() int {
	fake.formatClarificationMutex.RLock()
	defer fake.formatClarificationMutex.RUnlock()
	return len(fake.formatClarificationArgsForCall)
}

func (fake *FakeMessenger) FormatClarificationCalls(stub func(messenger.SendRequest, messenger.ClarificationInfo) messenger.SendRequest) {
	fake.formatClarificationMutex.Lock()
	defer fake.formatClarificationMutex.Unlock()
	fake.FormatClarificationStub = stub
}

func (fake *FakeMessenger) FormatClarificationArgsForCall(i int) (messenger.SendRequest, messenger.ClarificationInfo) {
	fake.formatClarificationMutex.RLock()
	defer fake.formatClarificationMutex.RUnlock()
	argsForCall := fake.formatClarificationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMessenger) FormatClarificationReturns(result1 messenger.SendRequest) {
	fake.formatClarificationMutex.Lock()
	defer fake.formatClarificationMutex.Unlock()
	fake.FormatClarificationStub = nil
	fake.formatClarificationReturns = struct {
		result1 messenger.SendRequest
	}{result1}
}

func (fake *FakeMessenger) FormatClarificationReturnsOnCall(i int, result1 messenger.SendRequest) {
	fake.formatClarificationMutex.Lock()
	defer fake.formatClarificationMutex.Unlock()
	fake.FormatClarificationStub = nil
	if fake.formatClarificationReturnsOnCall == nil {
		fake.formatClarificationReturnsOnCall = make(map[int]struct {
			result1 messenger.SendRequest
		})
	}
	fake.formatClarificationReturnsOnCall[i] = struct {
		result1 messenger.SendRequest
	}{result1}
}

func (fake *FakeMessenger) Platform() messenger.Platform {
	fake.platformMutex.Lock()
	ret, specificReturn := fake.platformReturnsOnCall[len(fake.platformArgsForCall)]
	fake.platformArgsForCall = append(fake.platformArgsForCall, struct {
	}{})
	stub := fake.PlatformStub
	fakeReturns := fake.platformReturns
	fake.recordInvocation("Platform", []interface{}{})
	fake.platformMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMessenger) PlatformCallCount() int {
	fake.platformMutex.RLock()
	defer fake.platformMutex.RUnlock()
	return len(fake.platformArgsForCall)
}

func (fake *FakeMessenger) PlatformCalls(stub func() messenger.Platform) {
	fake.platformMutex.Lock()
	defer fake.platformMutex.Unlock()
	fake.PlatformStub = stub
}

func (fake *FakeMessenger) PlatformReturns(result1 messenger.Platform) {
	fake.platformMutex.Lock()
	defer fake.platformMutex.Unlock()
	fake.PlatformStub = nil
	fake.platformReturns = struct {
		result1 messenger.Platform
	}{result1}
}

func (fake *FakeMessenger) PlatformReturnsOnCall(i int, result1 messenger.Platform) {
	fake.platformMutex.Lock()
	defer fake.platformMutex.Unlock()
	fake.PlatformStub = nil
	if fake.platformReturnsOnCall == nil {
		fake.platformReturnsOnCall = make(map[int]struct {
			result1 messenger.Platform
		})
	}
	fake.platformReturnsOnCall[i] = struct {
		result1 messenger.Platform
	}{result1}
}

func (fake *FakeMessenger) Receive(arg1 context.Context) (<-chan messenger.IncomingMessage, error) {
	fake.receiveMutex.Lock()
	ret, specificReturn := fake.receiveReturnsOnCall[len(fake.receiveArgsForCall)]
	fake.receiveArgsForCall = append(fake.receiveArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ReceiveStub
	fakeReturns := fake.receiveReturns
	fake.recordInvocation("Receive", []interface{}{arg1})
	fake.receiveMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMessenger) ReceiveCallCount() int {
	fake.receiveMutex.RLock()
	defer fake.receiveMutex.RUnlock()
	return len(fake.receiveArgsForCall)
}

func (fake *FakeMessenger) ReceiveCalls(stub func(context.Context) (<-chan messenger.IncomingMessage, error)) {
	fake.receiveMutex.Lock()
	defer fake.receiveMutex.Unlock()
	fake.ReceiveStub = stub
}

func (fake *FakeMessenger) ReceiveArgsForCall(i int) context.Context {
	fake.receiveMutex.RLock()
	defer fake.receiveMutex.RUnlock()
	argsForCall := fake.receiveArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMessenger) ReceiveReturns(result1 <-chan messenger.IncomingMessage, result2 error) {
	fake.receiveMutex.Lock()
	defer fake.receiveMutex.Unlock()
	fake.ReceiveStub = nil
	fake.receiveReturns = struct {
		result1 <-chan messenger.IncomingMessage
		result2 error
	}{result1, result2}
}

func (fake *FakeMessenger) ReceiveReturnsOnCall(i int, result1 <-chan messenger.IncomingMessage, result2 error) {
	fake.receiveMutex.Lock()
	defer fake.receiveMutex.Unlock()
	fake.ReceiveStub = nil
	if fake.receiveReturnsOnCall == nil {
		fake.receiveReturnsOnCall = make(map[int]struct {
			result1 <-chan messenger.IncomingMessage
			result2 error
		})
	}
	fake.receiveReturnsOnCall[i] = struct {
		result1 <-chan messenger.IncomingMessage
		result2 error
	}{result1, result2}
}

func (fake *FakeMessenger) Send(arg1 context.Context, arg2 messenger.SendRequest) (messenger.SendResponse, error) {
	fake.sendMutex.Lock()
	ret, specificReturn := fake.sendReturnsOnCall[len(fake.sendArgsForCall)]
	fake.sendArgsForCall = append(fake.sendArgsForCall, struct {
		arg1 context.Context
		arg2 messenger.SendRequest
	}{arg1, arg2})
	stub := fake.SendStub
	fakeReturns := fake.sendReturns
	fake.recordInvocation("Send", []interface{}{arg1, arg2})
	fake.sendMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMessenger) SendCallCount() int {
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	return len(fake.sendArgsForCall)
}

func (fake *FakeMessenger) SendCalls(stub func(context.Context, messenger.SendRequest) (messenger.SendResponse, error)) {
	fake.sendMutex.Lock()
	defer fake.sendMutex.Unlock()
	fake.SendStub = stub
}

func (fake *FakeMessenger) SendArgsForCall(i int) (context.Context, messenger.SendRequest) {
	fake.sendMutex.RLock()
	defer fake.sendMutex.RUnlock()
	argsForCall := fake.sendArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMessenger) SendReturns(result1 messenger.SendResponse, result2 error) {
	fake.sendMutex.Lock()
	defer fake.sendMutex.Unlock()
	fake.SendStub = nil
	fake.sendReturns = struct {
		result1 messenger.SendResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeMessenger) SendReturnsOnCall(i int, result1 messenger.SendResponse, result2 error) {
	fake.sendMutex.Lock()
	defer fake.sendMutex.Unlock()
	fake.SendStub = nil
	if fake.sendReturnsOnCall == nil {
		fake.sendReturnsOnCall = make(map[int]struct {
			result1 messenger.SendResponse
			result2 error
		})
	}
	fake.sendReturnsOnCall[i] = struct {
		result1 messenger.SendResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeMessenger) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMessenger) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ messenger.Messenger = new(FakeMessenger)
