// Code generated by counterfeiter. DO NOT EDIT.
package messengerfakes

import (
	"context"
	"sync"

	"github.com/appcd-dev/genie/pkg/messenger"
)

type FakeMessageLedger struct {
	RecordStub        func(context.Context, string, string, string, string)
	recordMutex       sync.RWMutex
	recordArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMessageLedger) Record(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 string) {
	fake.recordMutex.Lock()
	fake.recordArgsForCall = append(fake.recordArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.RecordStub
	fake.recordInvocation("Record", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.recordMutex.Unlock()
	if stub != nil {
		fake.RecordStub(arg1, arg2, arg3, arg4, arg5)
	}
}

func (fake *FakeMessageLedger) RecordCallCount() int {
	fake.recordMutex.RLock()
	defer fake.recordMutex.RUnlock()
	return len(fake.recordArgsForCall)
}

func (fake *FakeMessageLedger) RecordCalls(stub func(context.Context, string, string, string, string)) {
	fake.recordMutex.Lock()
	defer fake.recordMutex.Unlock()
	fake.RecordStub = stub
}

func (fake *FakeMessageLedger) RecordArgsForCall(i int) (context.Context, string, string, string, string) {
	fake.recordMutex.RLock()
	defer fake.recordMutex.RUnlock()
	argsForCall := fake.recordArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeMessageLedger) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMessageLedger) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ messenger.MessageLedger = new(FakeMessageLedger)
