// Code generated by counterfeiter. DO NOT EDIT.
package hubspotfakes

import (
	"context"
	"sync"

	"github.com/appcd-dev/genie/pkg/tools/hubspot"
)

type FakeService struct {
	CreateContactStub        func(context.Context, map[string]string) (*hubspot.Contact, error)
	createContactMutex       sync.RWMutex
	createContactArgsForCall []struct {
		arg1 context.Context
		arg2 map[string]string
	}
	createContactReturns struct {
		result1 *hubspot.Contact
		result2 error
	}
	createContactReturnsOnCall map[int]struct {
		result1 *hubspot.Contact
		result2 error
	}
	CreateDealStub        func(context.Context, map[string]string) (*hubspot.Deal, error)
	createDealMutex       sync.RWMutex
	createDealArgsForCall []struct {
		arg1 context.Context
		arg2 map[string]string
	}
	createDealReturns struct {
		result1 *hubspot.Deal
		result2 error
	}
	createDealReturnsOnCall map[int]struct {
		result1 *hubspot.Deal
		result2 error
	}
	GetCompanyStub        func(context.Context, string) (*hubspot.Company, error)
	getCompanyMutex       sync.RWMutex
	getCompanyArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getCompanyReturns struct {
		result1 *hubspot.Company
		result2 error
	}
	getCompanyReturnsOnCall map[int]struct {
		result1 *hubspot.Company
		result2 error
	}
	GetContactStub        func(context.Context, string) (*hubspot.Contact, error)
	getContactMutex       sync.RWMutex
	getContactArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getContactReturns struct {
		result1 *hubspot.Contact
		result2 error
	}
	getContactReturnsOnCall map[int]struct {
		result1 *hubspot.Contact
		result2 error
	}
	GetDealStub        func(context.Context, string) (*hubspot.Deal, error)
	getDealMutex       sync.RWMutex
	getDealArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getDealReturns struct {
		result1 *hubspot.Deal
		result2 error
	}
	getDealReturnsOnCall map[int]struct {
		result1 *hubspot.Deal
		result2 error
	}
	ListPipelinesStub        func(context.Context) ([]hubspot.Pipeline, error)
	listPipelinesMutex       sync.RWMutex
	listPipelinesArgsForCall []struct {
		arg1 context.Context
	}
	listPipelinesReturns struct {
		result1 []hubspot.Pipeline
		result2 error
	}
	listPipelinesReturnsOnCall map[int]struct {
		result1 []hubspot.Pipeline
		result2 error
	}
	SearchCompaniesStub        func(context.Context, string, int) ([]hubspot.Company, error)
	searchCompaniesMutex       sync.RWMutex
	searchCompaniesArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}
	searchCompaniesReturns struct {
		result1 []hubspot.Company
		result2 error
	}
	searchCompaniesReturnsOnCall map[int]struct {
		result1 []hubspot.Company
		result2 error
	}
	SearchContactsStub        func(context.Context, string, int) ([]hubspot.Contact, error)
	searchContactsMutex       sync.RWMutex
	searchContactsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}
	searchContactsReturns struct {
		result1 []hubspot.Contact
		result2 error
	}
	searchContactsReturnsOnCall map[int]struct {
		result1 []hubspot.Contact
		result2 error
	}
	SearchDealsStub        func(context.Context, string, int) ([]hubspot.Deal, error)
	searchDealsMutex       sync.RWMutex
	searchDealsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}
	searchDealsReturns struct {
		result1 []hubspot.Deal
		result2 error
	}
	searchDealsReturnsOnCall map[int]struct {
		result1 []hubspot.Deal
		result2 error
	}
	UpdateContactStub        func(context.Context, string, map[string]string) error
	updateContactMutex       sync.RWMutex
	updateContactArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 map[string]string
	}
	updateContactReturns struct {
		result1 error
	}
	updateContactReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateStub        func(context.Context) error
	validateMutex       sync.RWMutex
	validateArgsForCall []struct {
		arg1 context.Context
	}
	validateReturns struct {
		result1 error
	}
	validateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeService) CreateContact(arg1 context.Context, arg2 map[string]string) (*hubspot.Contact, error) {
	fake.createContactMutex.Lock()
	ret, specificReturn := fake.createContactReturnsOnCall[len(fake.createContactArgsForCall)]
	fake.createContactArgsForCall = append(fake.createContactArgsForCall, struct {
		arg1 context.Context
		arg2 map[string]string
	}{arg1, arg2})
	stub := fake.CreateContactStub
	fakeReturns := fake.createContactReturns
	fake.recordInvocation("CreateContact", []interface{}{arg1, arg2})
	fake.createContactMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) CreateContactCallCount() int {
	fake.createContactMutex.RLock()
	defer fake.createContactMutex.RUnlock()
	return len(fake.createContactArgsForCall)
}

func (fake *FakeService) CreateContactCalls(stub func(context.Context, map[string]string) (*hubspot.Contact, error)) {
	fake.createContactMutex.Lock()
	defer fake.createContactMutex.Unlock()
	fake.CreateContactStub = stub
}

func (fake *FakeService) CreateContactArgsForCall(i int) (context.Context, map[string]string) {
	fake.createContactMutex.RLock()
	defer fake.createContactMutex.RUnlock()
	argsForCall := fake.createContactArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) CreateContactReturns(result1 *hubspot.Contact, result2 error) {
	fake.createContactMutex.Lock()
	defer fake.createContactMutex.Unlock()
	fake.CreateContactStub = nil
	fake.createContactReturns = struct {
		result1 *hubspot.Contact
		result2 error
	}{result1, result2}
}

func (fake *FakeService) CreateContactReturnsOnCall(i int, result1 *hubspot.Contact, result2 error) {
	fake.createContactMutex.Lock()
	defer fake.createContactMutex.Unlock()
	fake.CreateContactStub = nil
	if fake.createContactReturnsOnCall == nil {
		fake.createContactReturnsOnCall = make(map[int]struct {
			result1 *hubspot.Contact
			result2 error
		})
	}
	fake.createContactReturnsOnCall[i] = struct {
		result1 *hubspot.Contact
		result2 error
	}{result1, result2}
}

func (fake *FakeService) CreateDeal(arg1 context.Context, arg2 map[string]string) (*hubspot.Deal, error) {
	fake.createDealMutex.Lock()
	ret, specificReturn := fake.createDealReturnsOnCall[len(fake.createDealArgsForCall)]
	fake.createDealArgsForCall = append(fake.createDealArgsForCall, struct {
		arg1 context.Context
		arg2 map[string]string
	}{arg1, arg2})
	stub := fake.CreateDealStub
	fakeReturns := fake.createDealReturns
	fake.recordInvocation("CreateDeal", []interface{}{arg1, arg2})
	fake.createDealMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) CreateDealCallCount() int {
	fake.createDealMutex.RLock()
	defer fake.createDealMutex.RUnlock()
	return len(fake.createDealArgsForCall)
}

func (fake *FakeService) CreateDealCalls(stub func(context.Context, map[string]string) (*hubspot.Deal, error)) {
	fake.createDealMutex.Lock()
	defer fake.createDealMutex.Unlock()
	fake.CreateDealStub = stub
}

func (fake *FakeService) CreateDealArgsForCall(i int) (context.Context, map[string]string) {
	fake.createDealMutex.RLock()
	defer fake.createDealMutex.RUnlock()
	argsForCall := fake.createDealArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) CreateDealReturns(result1 *hubspot.Deal, result2 error) {
	fake.createDealMutex.Lock()
	defer fake.createDealMutex.Unlock()
	fake.CreateDealStub = nil
	fake.createDealReturns = struct {
		result1 *hubspot.Deal
		result2 error
	}{result1, result2}
}

func (fake *FakeService) CreateDealReturnsOnCall(i int, result1 *hubspot.Deal, result2 error) {
	fake.createDealMutex.Lock()
	defer fake.createDealMutex.Unlock()
	fake.CreateDealStub = nil
	if fake.createDealReturnsOnCall == nil {
		fake.createDealReturnsOnCall = make(map[int]struct {
			result1 *hubspot.Deal
			result2 error
		})
	}
	fake.createDealReturnsOnCall[i] = struct {
		result1 *hubspot.Deal
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetCompany(arg1 context.Context, arg2 string) (*hubspot.Company, error) {
	fake.getCompanyMutex.Lock()
	ret, specificReturn := fake.getCompanyReturnsOnCall[len(fake.getCompanyArgsForCall)]
	fake.getCompanyArgsForCall = append(fake.getCompanyArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetCompanyStub
	fakeReturns := fake.getCompanyReturns
	fake.recordInvocation("GetCompany", []interface{}{arg1, arg2})
	fake.getCompanyMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) GetCompanyCallCount() int {
	fake.getCompanyMutex.RLock()
	defer fake.getCompanyMutex.RUnlock()
	return len(fake.getCompanyArgsForCall)
}

func (fake *FakeService) GetCompanyCalls(stub func(context.Context, string) (*hubspot.Company, error)) {
	fake.getCompanyMutex.Lock()
	defer fake.getCompanyMutex.Unlock()
	fake.GetCompanyStub = stub
}

func (fake *FakeService) GetCompanyArgsForCall(i int) (context.Context, string) {
	fake.getCompanyMutex.RLock()
	defer fake.getCompanyMutex.RUnlock()
	argsForCall := fake.getCompanyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) GetCompanyReturns(result1 *hubspot.Company, result2 error) {
	fake.getCompanyMutex.Lock()
	defer fake.getCompanyMutex.Unlock()
	fake.GetCompanyStub = nil
	fake.getCompanyReturns = struct {
		result1 *hubspot.Company
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetCompanyReturnsOnCall(i int, result1 *hubspot.Company, result2 error) {
	fake.getCompanyMutex.Lock()
	defer fake.getCompanyMutex.Unlock()
	fake.GetCompanyStub = nil
	if fake.getCompanyReturnsOnCall == nil {
		fake.getCompanyReturnsOnCall = make(map[int]struct {
			result1 *hubspot.Company
			result2 error
		})
	}
	fake.getCompanyReturnsOnCall[i] = struct {
		result1 *hubspot.Company
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetContact(arg1 context.Context, arg2 string) (*hubspot.Contact, error) {
	fake.getContactMutex.Lock()
	ret, specificReturn := fake.getContactReturnsOnCall[len(fake.getContactArgsForCall)]
	fake.getContactArgsForCall = append(fake.getContactArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetContactStub
	fakeReturns := fake.getContactReturns
	fake.recordInvocation("GetContact", []interface{}{arg1, arg2})
	fake.getContactMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) GetContactCallCount() int {
	fake.getContactMutex.RLock()
	defer fake.getContactMutex.RUnlock()
	return len(fake.getContactArgsForCall)
}

func (fake *FakeService) GetContactCalls(stub func(context.Context, string) (*hubspot.Contact, error)) {
	fake.getContactMutex.Lock()
	defer fake.getContactMutex.Unlock()
	fake.GetContactStub = stub
}

func (fake *FakeService) GetContactArgsForCall(i int) (context.Context, string) {
	fake.getContactMutex.RLock()
	defer fake.getContactMutex.RUnlock()
	argsForCall := fake.getContactArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) GetContactReturns(result1 *hubspot.Contact, result2 error) {
	fake.getContactMutex.Lock()
	defer fake.getContactMutex.Unlock()
	fake.GetContactStub = nil
	fake.getContactReturns = struct {
		result1 *hubspot.Contact
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetContactReturnsOnCall(i int, result1 *hubspot.Contact, result2 error) {
	fake.getContactMutex.Lock()
	defer fake.getContactMutex.Unlock()
	fake.GetContactStub = nil
	if fake.getContactReturnsOnCall == nil {
		fake.getContactReturnsOnCall = make(map[int]struct {
			result1 *hubspot.Contact
			result2 error
		})
	}
	fake.getContactReturnsOnCall[i] = struct {
		result1 *hubspot.Contact
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetDeal(arg1 context.Context, arg2 string) (*hubspot.Deal, error) {
	fake.getDealMutex.Lock()
	ret, specificReturn := fake.getDealReturnsOnCall[len(fake.getDealArgsForCall)]
	fake.getDealArgsForCall = append(fake.getDealArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetDealStub
	fakeReturns := fake.getDealReturns
	fake.recordInvocation("GetDeal", []interface{}{arg1, arg2})
	fake.getDealMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) GetDealCallCount() int {
	fake.getDealMutex.RLock()
	defer fake.getDealMutex.RUnlock()
	return len(fake.getDealArgsForCall)
}

func (fake *FakeService) GetDealCalls(stub func(context.Context, string) (*hubspot.Deal, error)) {
	fake.getDealMutex.Lock()
	defer fake.getDealMutex.Unlock()
	fake.GetDealStub = stub
}

func (fake *FakeService) GetDealArgsForCall(i int) (context.Context, string) {
	fake.getDealMutex.RLock()
	defer fake.getDealMutex.RUnlock()
	argsForCall := fake.getDealArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) GetDealReturns(result1 *hubspot.Deal, result2 error) {
	fake.getDealMutex.Lock()
	defer fake.getDealMutex.Unlock()
	fake.GetDealStub = nil
	fake.getDealReturns = struct {
		result1 *hubspot.Deal
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetDealReturnsOnCall(i int, result1 *hubspot.Deal, result2 error) {
	fake.getDealMutex.Lock()
	defer fake.getDealMutex.Unlock()
	fake.GetDealStub = nil
	if fake.getDealReturnsOnCall == nil {
		fake.getDealReturnsOnCall = make(map[int]struct {
			result1 *hubspot.Deal
			result2 error
		})
	}
	fake.getDealReturnsOnCall[i] = struct {
		result1 *hubspot.Deal
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListPipelines(arg1 context.Context) ([]hubspot.Pipeline, error) {
	fake.listPipelinesMutex.Lock()
	ret, specificReturn := fake.listPipelinesReturnsOnCall[len(fake.listPipelinesArgsForCall)]
	fake.listPipelinesArgsForCall = append(fake.listPipelinesArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ListPipelinesStub
	fakeReturns := fake.listPipelinesReturns
	fake.recordInvocation("ListPipelines", []interface{}{arg1})
	fake.listPipelinesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ListPipelinesCallCount() int {
	fake.listPipelinesMutex.RLock()
	defer fake.listPipelinesMutex.RUnlock()
	return len(fake.listPipelinesArgsForCall)
}

func (fake *FakeService) ListPipelinesCalls(stub func(context.Context) ([]hubspot.Pipeline, error)) {
	fake.listPipelinesMutex.Lock()
	defer fake.listPipelinesMutex.Unlock()
	fake.ListPipelinesStub = stub
}

func (fake *FakeService) ListPipelinesArgsForCall(i int) context.Context {
	fake.listPipelinesMutex.RLock()
	defer fake.listPipelinesMutex.RUnlock()
	argsForCall := fake.listPipelinesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) ListPipelinesReturns(result1 []hubspot.Pipeline, result2 error) {
	fake.listPipelinesMutex.Lock()
	defer fake.listPipelinesMutex.Unlock()
	fake.ListPipelinesStub = nil
	fake.listPipelinesReturns = struct {
		result1 []hubspot.Pipeline
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListPipelinesReturnsOnCall(i int, result1 []hubspot.Pipeline, result2 error) {
	fake.listPipelinesMutex.Lock()
	defer fake.listPipelinesMutex.Unlock()
	fake.ListPipelinesStub = nil
	if fake.listPipelinesReturnsOnCall == nil {
		fake.listPipelinesReturnsOnCall = make(map[int]struct {
			result1 []hubspot.Pipeline
			result2 error
		})
	}
	fake.listPipelinesReturnsOnCall[i] = struct {
		result1 []hubspot.Pipeline
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SearchCompanies(arg1 context.Context, arg2 string, arg3 int) ([]hubspot.Company, error) {
	fake.searchCompaniesMutex.Lock()
	ret, specificReturn := fake.searchCompaniesReturnsOnCall[len(fake.searchCompaniesArgsForCall)]
	fake.searchCompaniesArgsForCall = append(fake.searchCompaniesArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.SearchCompaniesStub
	fakeReturns := fake.searchCompaniesReturns
	fake.recordInvocation("SearchCompanies", []interface{}{arg1, arg2, arg3})
	fake.searchCompaniesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) SearchCompaniesCallCount() int {
	fake.searchCompaniesMutex.RLock()
	defer fake.searchCompaniesMutex.RUnlock()
	return len(fake.searchCompaniesArgsForCall)
}

func (fake *FakeService) SearchCompaniesCalls(stub func(context.Context, string, int) ([]hubspot.Company, error)) {
	fake.searchCompaniesMutex.Lock()
	defer fake.searchCompaniesMutex.Unlock()
	fake.SearchCompaniesStub = stub
}

func (fake *FakeService) SearchCompaniesArgsForCall(i int) (context.Context, string, int) {
	fake.searchCompaniesMutex.RLock()
	defer fake.searchCompaniesMutex.RUnlock()
	argsForCall := fake.searchCompaniesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) SearchCompaniesReturns(result1 []hubspot.Company, result2 error) {
	fake.searchCompaniesMutex.Lock()
	defer fake.searchCompaniesMutex.Unlock()
	fake.SearchCompaniesStub = nil
	fake.searchCompaniesReturns = struct {
		result1 []hubspot.Company
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SearchCompaniesReturnsOnCall(i int, result1 []hubspot.Company, result2 error) {
	fake.searchCompaniesMutex.Lock()
	defer fake.searchCompaniesMutex.Unlock()
	fake.SearchCompaniesStub = nil
	if fake.searchCompaniesReturnsOnCall == nil {
		fake.searchCompaniesReturnsOnCall = make(map[int]struct {
			result1 []hubspot.Company
			result2 error
		})
	}
	fake.searchCompaniesReturnsOnCall[i] = struct {
		result1 []hubspot.Company
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SearchContacts(arg1 context.Context, arg2 string, arg3 int) ([]hubspot.Contact, error) {
	fake.searchContactsMutex.Lock()
	ret, specificReturn := fake.searchContactsReturnsOnCall[len(fake.searchContactsArgsForCall)]
	fake.searchContactsArgsForCall = append(fake.searchContactsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.SearchContactsStub
	fakeReturns := fake.searchContactsReturns
	fake.recordInvocation("SearchContacts", []interface{}{arg1, arg2, arg3})
	fake.searchContactsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) SearchContactsCallCount() int {
	fake.searchContactsMutex.RLock()
	defer fake.searchContactsMutex.RUnlock()
	return len(fake.searchContactsArgsForCall)
}

func (fake *FakeService) SearchContactsCalls(stub func(context.Context, string, int) ([]hubspot.Contact, error)) {
	fake.searchContactsMutex.Lock()
	defer fake.searchContactsMutex.Unlock()
	fake.SearchContactsStub = stub
}

func (fake *FakeService) SearchContactsArgsForCall(i int) (context.Context, string, int) {
	fake.searchContactsMutex.RLock()
	defer fake.searchContactsMutex.RUnlock()
	argsForCall := fake.searchContactsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) SearchContactsReturns(result1 []hubspot.Contact, result2 error) {
	fake.searchContactsMutex.Lock()
	defer fake.searchContactsMutex.Unlock()
	fake.SearchContactsStub = nil
	fake.searchContactsReturns = struct {
		result1 []hubspot.Contact
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SearchContactsReturnsOnCall(i int, result1 []hubspot.Contact, result2 error) {
	fake.searchContactsMutex.Lock()
	defer fake.searchContactsMutex.Unlock()
	fake.SearchContactsStub = nil
	if fake.searchContactsReturnsOnCall == nil {
		fake.searchContactsReturnsOnCall = make(map[int]struct {
			result1 []hubspot.Contact
			result2 error
		})
	}
	fake.searchContactsReturnsOnCall[i] = struct {
		result1 []hubspot.Contact
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SearchDeals(arg1 context.Context, arg2 string, arg3 int) ([]hubspot.Deal, error) {
	fake.searchDealsMutex.Lock()
	ret, specificReturn := fake.searchDealsReturnsOnCall[len(fake.searchDealsArgsForCall)]
	fake.searchDealsArgsForCall = append(fake.searchDealsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.SearchDealsStub
	fakeReturns := fake.searchDealsReturns
	fake.recordInvocation("SearchDeals", []interface{}{arg1, arg2, arg3})
	fake.searchDealsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) SearchDealsCallCount() int {
	fake.searchDealsMutex.RLock()
	defer fake.searchDealsMutex.RUnlock()
	return len(fake.searchDealsArgsForCall)
}

func (fake *FakeService) SearchDealsCalls(stub func(context.Context, string, int) ([]hubspot.Deal, error)) {
	fake.searchDealsMutex.Lock()
	defer fake.searchDealsMutex.Unlock()
	fake.SearchDealsStub = stub
}

func (fake *FakeService) SearchDealsArgsForCall(i int) (context.Context, string, int) {
	fake.searchDealsMutex.RLock()
	defer fake.searchDealsMutex.RUnlock()
	argsForCall := fake.searchDealsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) SearchDealsReturns(result1 []hubspot.Deal, result2 error) {
	fake.searchDealsMutex.Lock()
	defer fake.searchDealsMutex.Unlock()
	fake.SearchDealsStub = nil
	fake.searchDealsReturns = struct {
		result1 []hubspot.Deal
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SearchDealsReturnsOnCall(i int, result1 []hubspot.Deal, result2 error) {
	fake.searchDealsMutex.Lock()
	defer fake.searchDealsMutex.Unlock()
	fake.SearchDealsStub = nil
	if fake.searchDealsReturnsOnCall == nil {
		fake.searchDealsReturnsOnCall = make(map[int]struct {
			result1 []hubspot.Deal
			result2 error
		})
	}
	fake.searchDealsReturnsOnCall[i] = struct {
		result1 []hubspot.Deal
		result2 error
	}{result1, result2}
}

func (fake *FakeService) UpdateContact(arg1 context.Context, arg2 string, arg3 map[string]string) error {
	fake.updateContactMutex.Lock()
	ret, specificReturn := fake.updateContactReturnsOnCall[len(fake.updateContactArgsForCall)]
	fake.updateContactArgsForCall = append(fake.updateContactArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 map[string]string
	}{arg1, arg2, arg3})
	stub := fake.UpdateContactStub
	fakeReturns := fake.updateContactReturns
	fake.recordInvocation("UpdateContact", []interface{}{arg1, arg2, arg3})
	fake.updateContactMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) UpdateContactCallCount() int {
	fake.updateContactMutex.RLock()
	defer fake.updateContactMutex.RUnlock()
	return len(fake.updateContactArgsForCall)
}

func (fake *FakeService) UpdateContactCalls(stub func(context.Context, string, map[string]string) error) {
	fake.updateContactMutex.Lock()
	defer fake.updateContactMutex.Unlock()
	fake.UpdateContactStub = stub
}

func (fake *FakeService) UpdateContactArgsForCall(i int) (context.Context, string, map[string]string) {
	fake.updateContactMutex.RLock()
	defer fake.updateContactMutex.RUnlock()
	argsForCall := fake.updateContactArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) UpdateContactReturns(result1 error) {
	fake.updateContactMutex.Lock()
	defer fake.updateContactMutex.Unlock()
	fake.UpdateContactStub = nil
	fake.updateContactReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) UpdateContactReturnsOnCall(i int, result1 error) {
	fake.updateContactMutex.Lock()
	defer fake.updateContactMutex.Unlock()
	fake.UpdateContactStub = nil
	if fake.updateContactReturnsOnCall == nil {
		fake.updateContactReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateContactReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) Validate(arg1 context.Context) error {
	fake.validateMutex.Lock()
	ret, specificReturn := fake.validateReturnsOnCall[len(fake.validateArgsForCall)]
	fake.validateArgsForCall = append(fake.validateArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ValidateStub
	fakeReturns := fake.validateReturns
	fake.recordInvocation("Validate", []interface{}{arg1})
	fake.validateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) ValidateCallCount() int {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	return len(fake.validateArgsForCall)
}

func (fake *FakeService) ValidateCalls(stub func(context.Context) error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = stub
}

func (fake *FakeService) ValidateArgsForCall(i int) context.Context {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	argsForCall := fake.validateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) ValidateReturns(result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	fake.validateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) ValidateReturnsOnCall(i int, result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	if fake.validateReturnsOnCall == nil {
		fake.validateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ hubspot.Service = new(FakeService)
