// Code generated by counterfeiter. DO NOT EDIT.
package snowflakefakes

import (
	"context"
	"sync"

	"github.com/appcd-dev/genie/pkg/tools/snowflake"
)

type FakeService struct {
	DescribeTableStub        func(context.Context, string, string, string) ([]snowflake.ColumnInfo, error)
	describeTableMutex       sync.RWMutex
	describeTableArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	describeTableReturns struct {
		result1 []snowflake.ColumnInfo
		result2 error
	}
	describeTableReturnsOnCall map[int]struct {
		result1 []snowflake.ColumnInfo
		result2 error
	}
	ListDatabasesStub        func(context.Context) ([]string, error)
	listDatabasesMutex       sync.RWMutex
	listDatabasesArgsForCall []struct {
		arg1 context.Context
	}
	listDatabasesReturns struct {
		result1 []string
		result2 error
	}
	listDatabasesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	ListSchemasStub        func(context.Context, string) ([]string, error)
	listSchemasMutex       sync.RWMutex
	listSchemasArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	listSchemasReturns struct {
		result1 []string
		result2 error
	}
	listSchemasReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	ListTablesStub        func(context.Context, string, string) ([]snowflake.TableInfo, error)
	listTablesMutex       sync.RWMutex
	listTablesArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	listTablesReturns struct {
		result1 []snowflake.TableInfo
		result2 error
	}
	listTablesReturnsOnCall map[int]struct {
		result1 []snowflake.TableInfo
		result2 error
	}
	QueryStub        func(context.Context, string) (*snowflake.QueryResult, error)
	queryMutex       sync.RWMutex
	queryArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	queryReturns struct {
		result1 *snowflake.QueryResult
		result2 error
	}
	queryReturnsOnCall map[int]struct {
		result1 *snowflake.QueryResult
		result2 error
	}
	ValidateStub        func(context.Context) error
	validateMutex       sync.RWMutex
	validateArgsForCall []struct {
		arg1 context.Context
	}
	validateReturns struct {
		result1 error
	}
	validateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeService) DescribeTable(arg1 context.Context, arg2 string, arg3 string, arg4 string) ([]snowflake.ColumnInfo, error) {
	fake.describeTableMutex.Lock()
	ret, specificReturn := fake.describeTableReturnsOnCall[len(fake.describeTableArgsForCall)]
	fake.describeTableArgsForCall = append(fake.describeTableArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.DescribeTableStub
	fakeReturns := fake.describeTableReturns
	fake.recordInvocation("DescribeTable", []interface{}{arg1, arg2, arg3, arg4})
	fake.describeTableMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) DescribeTableCallCount() int {
	fake.describeTableMutex.RLock()
	defer fake.describeTableMutex.RUnlock()
	return len(fake.describeTableArgsForCall)
}

func (fake *FakeService) DescribeTableCalls(stub func(context.Context, string, string, string) ([]snowflake.ColumnInfo, error)) {
	fake.describeTableMutex.Lock()
	defer fake.describeTableMutex.Unlock()
	fake.DescribeTableStub = stub
}

func (fake *FakeService) DescribeTableArgsForCall(i int) (context.Context, string, string, string) {
	fake.describeTableMutex.RLock()
	defer fake.describeTableMutex.RUnlock()
	argsForCall := fake.describeTableArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeService) DescribeTableReturns(result1 []snowflake.ColumnInfo, result2 error) {
	fake.describeTableMutex.Lock()
	defer fake.describeTableMutex.Unlock()
	fake.DescribeTableStub = nil
	fake.describeTableReturns = struct {
		result1 []snowflake.ColumnInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeService) DescribeTableReturnsOnCall(i int, result1 []snowflake.ColumnInfo, result2 error) {
	fake.describeTableMutex.Lock()
	defer fake.describeTableMutex.Unlock()
	fake.DescribeTableStub = nil
	if fake.describeTableReturnsOnCall == nil {
		fake.describeTableReturnsOnCall = make(map[int]struct {
			result1 []snowflake.ColumnInfo
			result2 error
		})
	}
	fake.describeTableReturnsOnCall[i] = struct {
		result1 []snowflake.ColumnInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListDatabases(arg1 context.Context) ([]string, error) {
	fake.listDatabasesMutex.Lock()
	ret, specificReturn := fake.listDatabasesReturnsOnCall[len(fake.listDatabasesArgsForCall)]
	fake.listDatabasesArgsForCall = append(fake.listDatabasesArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ListDatabasesStub
	fakeReturns := fake.listDatabasesReturns
	fake.recordInvocation("ListDatabases", []interface{}{arg1})
	fake.listDatabasesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ListDatabasesCallCount() int {
	fake.listDatabasesMutex.RLock()
	defer fake.listDatabasesMutex.RUnlock()
	return len(fake.listDatabasesArgsForCall)
}

func (fake *FakeService) ListDatabasesCalls(stub func(context.Context) ([]string, error)) {
	fake.listDatabasesMutex.Lock()
	defer fake.listDatabasesMutex.Unlock()
	fake.ListDatabasesStub = stub
}

func (fake *FakeService) ListDatabasesArgsForCall(i int) context.Context {
	fake.listDatabasesMutex.RLock()
	defer fake.listDatabasesMutex.RUnlock()
	argsForCall := fake.listDatabasesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) ListDatabasesReturns(result1 []string, result2 error) {
	fake.listDatabasesMutex.Lock()
	defer fake.listDatabasesMutex.Unlock()
	fake.ListDatabasesStub = nil
	fake.listDatabasesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListDatabasesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.listDatabasesMutex.Lock()
	defer fake.listDatabasesMutex.Unlock()
	fake.ListDatabasesStub = nil
	if fake.listDatabasesReturnsOnCall == nil {
		fake.listDatabasesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.listDatabasesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListSchemas(arg1 context.Context, arg2 string) ([]string, error) {
	fake.listSchemasMutex.Lock()
	ret, specificReturn := fake.listSchemasReturnsOnCall[len(fake.listSchemasArgsForCall)]
	fake.listSchemasArgsForCall = append(fake.listSchemasArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ListSchemasStub
	fakeReturns := fake.listSchemasReturns
	fake.recordInvocation("ListSchemas", []interface{}{arg1, arg2})
	fake.listSchemasMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ListSchemasCallCount() int {
	fake.listSchemasMutex.RLock()
	defer fake.listSchemasMutex.RUnlock()
	return len(fake.listSchemasArgsForCall)
}

func (fake *FakeService) ListSchemasCalls(stub func(context.Context, string) ([]string, error)) {
	fake.listSchemasMutex.Lock()
	defer fake.listSchemasMutex.Unlock()
	fake.ListSchemasStub = stub
}

func (fake *FakeService) ListSchemasArgsForCall(i int) (context.Context, string) {
	fake.listSchemasMutex.RLock()
	defer fake.listSchemasMutex.RUnlock()
	argsForCall := fake.listSchemasArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) ListSchemasReturns(result1 []string, result2 error) {
	fake.listSchemasMutex.Lock()
	defer fake.listSchemasMutex.Unlock()
	fake.ListSchemasStub = nil
	fake.listSchemasReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListSchemasReturnsOnCall(i int, result1 []string, result2 error) {
	fake.listSchemasMutex.Lock()
	defer fake.listSchemasMutex.Unlock()
	fake.ListSchemasStub = nil
	if fake.listSchemasReturnsOnCall == nil {
		fake.listSchemasReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.listSchemasReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListTables(arg1 context.Context, arg2 string, arg3 string) ([]snowflake.TableInfo, error) {
	fake.listTablesMutex.Lock()
	ret, specificReturn := fake.listTablesReturnsOnCall[len(fake.listTablesArgsForCall)]
	fake.listTablesArgsForCall = append(fake.listTablesArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ListTablesStub
	fakeReturns := fake.listTablesReturns
	fake.recordInvocation("ListTables", []interface{}{arg1, arg2, arg3})
	fake.listTablesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ListTablesCallCount() int {
	fake.listTablesMutex.RLock()
	defer fake.listTablesMutex.RUnlock()
	return len(fake.listTablesArgsForCall)
}

func (fake *FakeService) ListTablesCalls(stub func(context.Context, string, string) ([]snowflake.TableInfo, error)) {
	fake.listTablesMutex.Lock()
	defer fake.listTablesMutex.Unlock()
	fake.ListTablesStub = stub
}

func (fake *FakeService) ListTablesArgsForCall(i int) (context.Context, string, string) {
	fake.listTablesMutex.RLock()
	defer fake.listTablesMutex.RUnlock()
	argsForCall := fake.listTablesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) ListTablesReturns(result1 []snowflake.TableInfo, result2 error) {
	fake.listTablesMutex.Lock()
	defer fake.listTablesMutex.Unlock()
	fake.ListTablesStub = nil
	fake.listTablesReturns = struct {
		result1 []snowflake.TableInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListTablesReturnsOnCall(i int, result1 []snowflake.TableInfo, result2 error) {
	fake.listTablesMutex.Lock()
	defer fake.listTablesMutex.Unlock()
	fake.ListTablesStub = nil
	if fake.listTablesReturnsOnCall == nil {
		fake.listTablesReturnsOnCall = make(map[int]struct {
			result1 []snowflake.TableInfo
			result2 error
		})
	}
	fake.listTablesReturnsOnCall[i] = struct {
		result1 []snowflake.TableInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeService) Query(arg1 context.Context, arg2 string) (*snowflake.QueryResult, error) {
	fake.queryMutex.Lock()
	ret, specificReturn := fake.queryReturnsOnCall[len(fake.queryArgsForCall)]
	fake.queryArgsForCall = append(fake.queryArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.QueryStub
	fakeReturns := fake.queryReturns
	fake.recordInvocation("Query", []interface{}{arg1, arg2})
	fake.queryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) QueryCallCount() int {
	fake.queryMutex.RLock()
	defer fake.queryMutex.RUnlock()
	return len(fake.queryArgsForCall)
}

func (fake *FakeService) QueryCalls(stub func(context.Context, string) (*snowflake.QueryResult, error)) {
	fake.queryMutex.Lock()
	defer fake.queryMutex.Unlock()
	fake.QueryStub = stub
}

func (fake *FakeService) QueryArgsForCall(i int) (context.Context, string) {
	fake.queryMutex.RLock()
	defer fake.queryMutex.RUnlock()
	argsForCall := fake.queryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) QueryReturns(result1 *snowflake.QueryResult, result2 error) {
	fake.queryMutex.Lock()
	defer fake.queryMutex.Unlock()
	fake.QueryStub = nil
	fake.queryReturns = struct {
		result1 *snowflake.QueryResult
		result2 error
	}{result1, result2}
}

func (fake *FakeService) QueryReturnsOnCall(i int, result1 *snowflake.QueryResult, result2 error) {
	fake.queryMutex.Lock()
	defer fake.queryMutex.Unlock()
	fake.QueryStub = nil
	if fake.queryReturnsOnCall == nil {
		fake.queryReturnsOnCall = make(map[int]struct {
			result1 *snowflake.QueryResult
			result2 error
		})
	}
	fake.queryReturnsOnCall[i] = struct {
		result1 *snowflake.QueryResult
		result2 error
	}{result1, result2}
}

func (fake *FakeService) Validate(arg1 context.Context) error {
	fake.validateMutex.Lock()
	ret, specificReturn := fake.validateReturnsOnCall[len(fake.validateArgsForCall)]
	fake.validateArgsForCall = append(fake.validateArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ValidateStub
	fakeReturns := fake.validateReturns
	fake.recordInvocation("Validate", []interface{}{arg1})
	fake.validateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) ValidateCallCount() int {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	return len(fake.validateArgsForCall)
}

func (fake *FakeService) ValidateCalls(stub func(context.Context) error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = stub
}

func (fake *FakeService) ValidateArgsForCall(i int) context.Context {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	argsForCall := fake.validateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) ValidateReturns(result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	fake.validateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) ValidateReturnsOnCall(i int, result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	if fake.validateReturnsOnCall == nil {
		fake.validateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ snowflake.Service = new(FakeService)
