// Code generated by counterfeiter. DO NOT EDIT.
package learningfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/learning"
)

type FakeILearner struct {
	LearnStub        func(context.Context, learning.LearnRequest) error
	learnMutex       sync.RWMutex
	learnArgsForCall []struct {
		arg1 context.Context
		arg2 learning.LearnRequest
	}
	learnReturns struct {
		result1 error
	}
	learnReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeILearner) Learn(arg1 context.Context, arg2 learning.LearnRequest) error {
	fake.learnMutex.Lock()
	ret, specificReturn := fake.learnReturnsOnCall[len(fake.learnArgsForCall)]
	fake.learnArgsForCall = append(fake.learnArgsForCall, struct {
		arg1 context.Context
		arg2 learning.LearnRequest
	}{arg1, arg2})
	stub := fake.LearnStub
	fakeReturns := fake.learnReturns
	fake.recordInvocation("Learn", []interface{}{arg1, arg2})
	fake.learnMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeILearner) LearnCallCount() int {
	fake.learnMutex.RLock()
	defer fake.learnMutex.RUnlock()
	return len(fake.learnArgsForCall)
}

func (fake *FakeILearner) LearnCalls(stub func(context.Context, learning.LearnRequest) error) {
	fake.learnMutex.Lock()
	defer fake.learnMutex.Unlock()
	fake.LearnStub = stub
}

func (fake *FakeILearner) LearnArgsForCall(i int) (context.Context, learning.LearnRequest) {
	fake.learnMutex.RLock()
	defer fake.learnMutex.RUnlock()
	argsForCall := fake.learnArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeILearner) LearnReturns(result1 error) {
	fake.learnMutex.Lock()
	defer fake.learnMutex.Unlock()
	fake.LearnStub = nil
	fake.learnReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeILearner) LearnReturnsOnCall(i int, result1 error) {
	fake.learnMutex.Lock()
	defer fake.learnMutex.Unlock()
	fake.LearnStub = nil
	if fake.learnReturnsOnCall == nil {
		fake.learnReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.learnReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeILearner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeILearner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ learning.ILearner = new(FakeILearner)
