// Copyright (C) StackGen, Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by counterfeiter. DO NOT EDIT.
package datasourcefakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/datasource"
)

type FakeDataSource struct {
	ListItemsStub        func(context.Context, datasource.Scope) ([]datasource.NormalizedItem, error)
	listItemsMutex       sync.RWMutex
	listItemsArgsForCall []struct {
		arg1 context.Context
		arg2 datasource.Scope
	}
	listItemsReturns struct {
		result1 []datasource.NormalizedItem
		result2 error
	}
	listItemsReturnsOnCall map[int]struct {
		result1 []datasource.NormalizedItem
		result2 error
	}
	NameStub        func() string
	nameMutex       sync.RWMutex
	nameArgsForCall []struct {
	}
	nameReturns struct {
		result1 string
	}
	nameReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDataSource) ListItems(arg1 context.Context, arg2 datasource.Scope) ([]datasource.NormalizedItem, error) {
	fake.listItemsMutex.Lock()
	ret, specificReturn := fake.listItemsReturnsOnCall[len(fake.listItemsArgsForCall)]
	fake.listItemsArgsForCall = append(fake.listItemsArgsForCall, struct {
		arg1 context.Context
		arg2 datasource.Scope
	}{arg1, arg2})
	stub := fake.ListItemsStub
	fakeReturns := fake.listItemsReturns
	fake.recordInvocation("ListItems", []interface{}{arg1, arg2})
	fake.listItemsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDataSource) ListItemsCallCount() int {
	fake.listItemsMutex.RLock()
	defer fake.listItemsMutex.RUnlock()
	return len(fake.listItemsArgsForCall)
}

func (fake *FakeDataSource) ListItemsCalls(stub func(context.Context, datasource.Scope) ([]datasource.NormalizedItem, error)) {
	fake.listItemsMutex.Lock()
	defer fake.listItemsMutex.Unlock()
	fake.ListItemsStub = stub
}

func (fake *FakeDataSource) ListItemsArgsForCall(i int) (context.Context, datasource.Scope) {
	fake.listItemsMutex.RLock()
	defer fake.listItemsMutex.RUnlock()
	argsForCall := fake.listItemsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDataSource) ListItemsReturns(result1 []datasource.NormalizedItem, result2 error) {
	fake.listItemsMutex.Lock()
	defer fake.listItemsMutex.Unlock()
	fake.ListItemsStub = nil
	fake.listItemsReturns = struct {
		result1 []datasource.NormalizedItem
		result2 error
	}{result1, result2}
}

func (fake *FakeDataSource) ListItemsReturnsOnCall(i int, result1 []datasource.NormalizedItem, result2 error) {
	fake.listItemsMutex.Lock()
	defer fake.listItemsMutex.Unlock()
	fake.ListItemsStub = nil
	if fake.listItemsReturnsOnCall == nil {
		fake.listItemsReturnsOnCall = make(map[int]struct {
			result1 []datasource.NormalizedItem
			result2 error
		})
	}
	fake.listItemsReturnsOnCall[i] = struct {
		result1 []datasource.NormalizedItem
		result2 error
	}{result1, result2}
}

func (fake *FakeDataSource) Name() string {
	fake.nameMutex.Lock()
	ret, specificReturn := fake.nameReturnsOnCall[len(fake.nameArgsForCall)]
	fake.nameArgsForCall = append(fake.nameArgsForCall, struct {
	}{})
	stub := fake.NameStub
	fakeReturns := fake.nameReturns
	fake.recordInvocation("Name", []interface{}{})
	fake.nameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDataSource) NameCallCount() int {
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	return len(fake.nameArgsForCall)
}

func (fake *FakeDataSource) NameCalls(stub func() string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = stub
}

func (fake *FakeDataSource) NameReturns(result1 string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	fake.nameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeDataSource) NameReturnsOnCall(i int, result1 string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	if fake.nameReturnsOnCall == nil {
		fake.nameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.nameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeDataSource) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDataSource) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ datasource.DataSource = new(FakeDataSource)
