// Code generated by counterfeiter. DO NOT EDIT.
package authfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/security/auth"
)

type FakeIdentityResolver struct {
	ResolveStub        func(context.Context, auth.ResolveRequest) (auth.EnterpriseUser, error)
	resolveMutex       sync.RWMutex
	resolveArgsForCall []struct {
		arg1 context.Context
		arg2 auth.ResolveRequest
	}
	resolveReturns struct {
		result1 auth.EnterpriseUser
		result2 error
	}
	resolveReturnsOnCall map[int]struct {
		result1 auth.EnterpriseUser
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeIdentityResolver) Resolve(arg1 context.Context, arg2 auth.ResolveRequest) (auth.EnterpriseUser, error) {
	fake.resolveMutex.Lock()
	ret, specificReturn := fake.resolveReturnsOnCall[len(fake.resolveArgsForCall)]
	fake.resolveArgsForCall = append(fake.resolveArgsForCall, struct {
		arg1 context.Context
		arg2 auth.ResolveRequest
	}{arg1, arg2})
	stub := fake.ResolveStub
	fakeReturns := fake.resolveReturns
	fake.recordInvocation("Resolve", []interface{}{arg1, arg2})
	fake.resolveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeIdentityResolver) ResolveCallCount() int {
	fake.resolveMutex.RLock()
	defer fake.resolveMutex.RUnlock()
	return len(fake.resolveArgsForCall)
}

func (fake *FakeIdentityResolver) ResolveCalls(stub func(context.Context, auth.ResolveRequest) (auth.EnterpriseUser, error)) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = stub
}

func (fake *FakeIdentityResolver) ResolveArgsForCall(i int) (context.Context, auth.ResolveRequest) {
	fake.resolveMutex.RLock()
	defer fake.resolveMutex.RUnlock()
	argsForCall := fake.resolveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeIdentityResolver) ResolveReturns(result1 auth.EnterpriseUser, result2 error) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = nil
	fake.resolveReturns = struct {
		result1 auth.EnterpriseUser
		result2 error
	}{result1, result2}
}

func (fake *FakeIdentityResolver) ResolveReturnsOnCall(i int, result1 auth.EnterpriseUser, result2 error) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = nil
	if fake.resolveReturnsOnCall == nil {
		fake.resolveReturnsOnCall = make(map[int]struct {
			result1 auth.EnterpriseUser
			result2 error
		})
	}
	fake.resolveReturnsOnCall[i] = struct {
		result1 auth.EnterpriseUser
		result2 error
	}{result1, result2}
}

func (fake *FakeIdentityResolver) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeIdentityResolver) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ auth.IdentityResolver = new(FakeIdentityResolver)
