// Code generated by counterfeiter. DO NOT EDIT.
package atlassianfakes

import (
	"context"
	"sync"

	"github.com/appcd-dev/genie/pkg/tools/atlassian"
)

type FakeService struct {
	ConfluenceCreatePageStub        func(context.Context, atlassian.CreatePageInput) (*atlassian.PageSummary, error)
	confluenceCreatePageMutex       sync.RWMutex
	confluenceCreatePageArgsForCall []struct {
		arg1 context.Context
		arg2 atlassian.CreatePageInput
	}
	confluenceCreatePageReturns struct {
		result1 *atlassian.PageSummary
		result2 error
	}
	confluenceCreatePageReturnsOnCall map[int]struct {
		result1 *atlassian.PageSummary
		result2 error
	}
	ConfluenceGetPageStub        func(context.Context, string) (*atlassian.PageDetail, error)
	confluenceGetPageMutex       sync.RWMutex
	confluenceGetPageArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	confluenceGetPageReturns struct {
		result1 *atlassian.PageDetail
		result2 error
	}
	confluenceGetPageReturnsOnCall map[int]struct {
		result1 *atlassian.PageDetail
		result2 error
	}
	ConfluenceSearchStub        func(context.Context, string, int) ([]atlassian.PageSummary, error)
	confluenceSearchMutex       sync.RWMutex
	confluenceSearchArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}
	confluenceSearchReturns struct {
		result1 []atlassian.PageSummary
		result2 error
	}
	confluenceSearchReturnsOnCall map[int]struct {
		result1 []atlassian.PageSummary
		result2 error
	}
	ConfluenceUpdatePageStub        func(context.Context, string, atlassian.UpdatePageInput) error
	confluenceUpdatePageMutex       sync.RWMutex
	confluenceUpdatePageArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 atlassian.UpdatePageInput
	}
	confluenceUpdatePageReturns struct {
		result1 error
	}
	confluenceUpdatePageReturnsOnCall map[int]struct {
		result1 error
	}
	JiraAddCommentStub        func(context.Context, string, string) error
	jiraAddCommentMutex       sync.RWMutex
	jiraAddCommentArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	jiraAddCommentReturns struct {
		result1 error
	}
	jiraAddCommentReturnsOnCall map[int]struct {
		result1 error
	}
	JiraCreateIssueStub        func(context.Context, atlassian.CreateIssueInput) (*atlassian.IssueSummary, error)
	jiraCreateIssueMutex       sync.RWMutex
	jiraCreateIssueArgsForCall []struct {
		arg1 context.Context
		arg2 atlassian.CreateIssueInput
	}
	jiraCreateIssueReturns struct {
		result1 *atlassian.IssueSummary
		result2 error
	}
	jiraCreateIssueReturnsOnCall map[int]struct {
		result1 *atlassian.IssueSummary
		result2 error
	}
	JiraGetIssueStub        func(context.Context, string) (*atlassian.IssueDetail, error)
	jiraGetIssueMutex       sync.RWMutex
	jiraGetIssueArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	jiraGetIssueReturns struct {
		result1 *atlassian.IssueDetail
		result2 error
	}
	jiraGetIssueReturnsOnCall map[int]struct {
		result1 *atlassian.IssueDetail
		result2 error
	}
	JiraListTransitionsStub        func(context.Context, string) ([]atlassian.Transition, error)
	jiraListTransitionsMutex       sync.RWMutex
	jiraListTransitionsArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	jiraListTransitionsReturns struct {
		result1 []atlassian.Transition
		result2 error
	}
	jiraListTransitionsReturnsOnCall map[int]struct {
		result1 []atlassian.Transition
		result2 error
	}
	JiraSearchIssuesStub        func(context.Context, string, int) ([]atlassian.IssueSummary, error)
	jiraSearchIssuesMutex       sync.RWMutex
	jiraSearchIssuesArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}
	jiraSearchIssuesReturns struct {
		result1 []atlassian.IssueSummary
		result2 error
	}
	jiraSearchIssuesReturnsOnCall map[int]struct {
		result1 []atlassian.IssueSummary
		result2 error
	}
	JiraTransitionIssueStub        func(context.Context, string, string) error
	jiraTransitionIssueMutex       sync.RWMutex
	jiraTransitionIssueArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	jiraTransitionIssueReturns struct {
		result1 error
	}
	jiraTransitionIssueReturnsOnCall map[int]struct {
		result1 error
	}
	JiraUpdateIssueStub        func(context.Context, string, atlassian.UpdateIssueInput) error
	jiraUpdateIssueMutex       sync.RWMutex
	jiraUpdateIssueArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 atlassian.UpdateIssueInput
	}
	jiraUpdateIssueReturns struct {
		result1 error
	}
	jiraUpdateIssueReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateStub        func(context.Context) error
	validateMutex       sync.RWMutex
	validateArgsForCall []struct {
		arg1 context.Context
	}
	validateReturns struct {
		result1 error
	}
	validateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeService) ConfluenceCreatePage(arg1 context.Context, arg2 atlassian.CreatePageInput) (*atlassian.PageSummary, error) {
	fake.confluenceCreatePageMutex.Lock()
	ret, specificReturn := fake.confluenceCreatePageReturnsOnCall[len(fake.confluenceCreatePageArgsForCall)]
	fake.confluenceCreatePageArgsForCall = append(fake.confluenceCreatePageArgsForCall, struct {
		arg1 context.Context
		arg2 atlassian.CreatePageInput
	}{arg1, arg2})
	stub := fake.ConfluenceCreatePageStub
	fakeReturns := fake.confluenceCreatePageReturns
	fake.recordInvocation("ConfluenceCreatePage", []interface{}{arg1, arg2})
	fake.confluenceCreatePageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ConfluenceCreatePageCallCount() int {
	fake.confluenceCreatePageMutex.RLock()
	defer fake.confluenceCreatePageMutex.RUnlock()
	return len(fake.confluenceCreatePageArgsForCall)
}

func (fake *FakeService) ConfluenceCreatePageCalls(stub func(context.Context, atlassian.CreatePageInput) (*atlassian.PageSummary, error)) {
	fake.confluenceCreatePageMutex.Lock()
	defer fake.confluenceCreatePageMutex.Unlock()
	fake.ConfluenceCreatePageStub = stub
}

func (fake *FakeService) ConfluenceCreatePageArgsForCall(i int) (context.Context, atlassian.CreatePageInput) {
	fake.confluenceCreatePageMutex.RLock()
	defer fake.confluenceCreatePageMutex.RUnlock()
	argsForCall := fake.confluenceCreatePageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) ConfluenceCreatePageReturns(result1 *atlassian.PageSummary, result2 error) {
	fake.confluenceCreatePageMutex.Lock()
	defer fake.confluenceCreatePageMutex.Unlock()
	fake.ConfluenceCreatePageStub = nil
	fake.confluenceCreatePageReturns = struct {
		result1 *atlassian.PageSummary
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ConfluenceCreatePageReturnsOnCall(i int, result1 *atlassian.PageSummary, result2 error) {
	fake.confluenceCreatePageMutex.Lock()
	defer fake.confluenceCreatePageMutex.Unlock()
	fake.ConfluenceCreatePageStub = nil
	if fake.confluenceCreatePageReturnsOnCall == nil {
		fake.confluenceCreatePageReturnsOnCall = make(map[int]struct {
			result1 *atlassian.PageSummary
			result2 error
		})
	}
	fake.confluenceCreatePageReturnsOnCall[i] = struct {
		result1 *atlassian.PageSummary
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ConfluenceGetPage(arg1 context.Context, arg2 string) (*atlassian.PageDetail, error) {
	fake.confluenceGetPageMutex.Lock()
	ret, specificReturn := fake.confluenceGetPageReturnsOnCall[len(fake.confluenceGetPageArgsForCall)]
	fake.confluenceGetPageArgsForCall = append(fake.confluenceGetPageArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ConfluenceGetPageStub
	fakeReturns := fake.confluenceGetPageReturns
	fake.recordInvocation("ConfluenceGetPage", []interface{}{arg1, arg2})
	fake.confluenceGetPageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ConfluenceGetPageCallCount() int {
	fake.confluenceGetPageMutex.RLock()
	defer fake.confluenceGetPageMutex.RUnlock()
	return len(fake.confluenceGetPageArgsForCall)
}

func (fake *FakeService) ConfluenceGetPageCalls(stub func(context.Context, string) (*atlassian.PageDetail, error)) {
	fake.confluenceGetPageMutex.Lock()
	defer fake.confluenceGetPageMutex.Unlock()
	fake.ConfluenceGetPageStub = stub
}

func (fake *FakeService) ConfluenceGetPageArgsForCall(i int) (context.Context, string) {
	fake.confluenceGetPageMutex.RLock()
	defer fake.confluenceGetPageMutex.RUnlock()
	argsForCall := fake.confluenceGetPageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) ConfluenceGetPageReturns(result1 *atlassian.PageDetail, result2 error) {
	fake.confluenceGetPageMutex.Lock()
	defer fake.confluenceGetPageMutex.Unlock()
	fake.ConfluenceGetPageStub = nil
	fake.confluenceGetPageReturns = struct {
		result1 *atlassian.PageDetail
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ConfluenceGetPageReturnsOnCall(i int, result1 *atlassian.PageDetail, result2 error) {
	fake.confluenceGetPageMutex.Lock()
	defer fake.confluenceGetPageMutex.Unlock()
	fake.ConfluenceGetPageStub = nil
	if fake.confluenceGetPageReturnsOnCall == nil {
		fake.confluenceGetPageReturnsOnCall = make(map[int]struct {
			result1 *atlassian.PageDetail
			result2 error
		})
	}
	fake.confluenceGetPageReturnsOnCall[i] = struct {
		result1 *atlassian.PageDetail
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ConfluenceSearch(arg1 context.Context, arg2 string, arg3 int) ([]atlassian.PageSummary, error) {
	fake.confluenceSearchMutex.Lock()
	ret, specificReturn := fake.confluenceSearchReturnsOnCall[len(fake.confluenceSearchArgsForCall)]
	fake.confluenceSearchArgsForCall = append(fake.confluenceSearchArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.ConfluenceSearchStub
	fakeReturns := fake.confluenceSearchReturns
	fake.recordInvocation("ConfluenceSearch", []interface{}{arg1, arg2, arg3})
	fake.confluenceSearchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ConfluenceSearchCallCount() int {
	fake.confluenceSearchMutex.RLock()
	defer fake.confluenceSearchMutex.RUnlock()
	return len(fake.confluenceSearchArgsForCall)
}

func (fake *FakeService) ConfluenceSearchCalls(stub func(context.Context, string, int) ([]atlassian.PageSummary, error)) {
	fake.confluenceSearchMutex.Lock()
	defer fake.confluenceSearchMutex.Unlock()
	fake.ConfluenceSearchStub = stub
}

func (fake *FakeService) ConfluenceSearchArgsForCall(i int) (context.Context, string, int) {
	fake.confluenceSearchMutex.RLock()
	defer fake.confluenceSearchMutex.RUnlock()
	argsForCall := fake.confluenceSearchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) ConfluenceSearchReturns(result1 []atlassian.PageSummary, result2 error) {
	fake.confluenceSearchMutex.Lock()
	defer fake.confluenceSearchMutex.Unlock()
	fake.ConfluenceSearchStub = nil
	fake.confluenceSearchReturns = struct {
		result1 []atlassian.PageSummary
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ConfluenceSearchReturnsOnCall(i int, result1 []atlassian.PageSummary, result2 error) {
	fake.confluenceSearchMutex.Lock()
	defer fake.confluenceSearchMutex.Unlock()
	fake.ConfluenceSearchStub = nil
	if fake.confluenceSearchReturnsOnCall == nil {
		fake.confluenceSearchReturnsOnCall = make(map[int]struct {
			result1 []atlassian.PageSummary
			result2 error
		})
	}
	fake.confluenceSearchReturnsOnCall[i] = struct {
		result1 []atlassian.PageSummary
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ConfluenceUpdatePage(arg1 context.Context, arg2 string, arg3 atlassian.UpdatePageInput) error {
	fake.confluenceUpdatePageMutex.Lock()
	ret, specificReturn := fake.confluenceUpdatePageReturnsOnCall[len(fake.confluenceUpdatePageArgsForCall)]
	fake.confluenceUpdatePageArgsForCall = append(fake.confluenceUpdatePageArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 atlassian.UpdatePageInput
	}{arg1, arg2, arg3})
	stub := fake.ConfluenceUpdatePageStub
	fakeReturns := fake.confluenceUpdatePageReturns
	fake.recordInvocation("ConfluenceUpdatePage", []interface{}{arg1, arg2, arg3})
	fake.confluenceUpdatePageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) ConfluenceUpdatePageCallCount() int {
	fake.confluenceUpdatePageMutex.RLock()
	defer fake.confluenceUpdatePageMutex.RUnlock()
	return len(fake.confluenceUpdatePageArgsForCall)
}

func (fake *FakeService) ConfluenceUpdatePageCalls(stub func(context.Context, string, atlassian.UpdatePageInput) error) {
	fake.confluenceUpdatePageMutex.Lock()
	defer fake.confluenceUpdatePageMutex.Unlock()
	fake.ConfluenceUpdatePageStub = stub
}

func (fake *FakeService) ConfluenceUpdatePageArgsForCall(i int) (context.Context, string, atlassian.UpdatePageInput) {
	fake.confluenceUpdatePageMutex.RLock()
	defer fake.confluenceUpdatePageMutex.RUnlock()
	argsForCall := fake.confluenceUpdatePageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) ConfluenceUpdatePageReturns(result1 error) {
	fake.confluenceUpdatePageMutex.Lock()
	defer fake.confluenceUpdatePageMutex.Unlock()
	fake.ConfluenceUpdatePageStub = nil
	fake.confluenceUpdatePageReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) ConfluenceUpdatePageReturnsOnCall(i int, result1 error) {
	fake.confluenceUpdatePageMutex.Lock()
	defer fake.confluenceUpdatePageMutex.Unlock()
	fake.ConfluenceUpdatePageStub = nil
	if fake.confluenceUpdatePageReturnsOnCall == nil {
		fake.confluenceUpdatePageReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.confluenceUpdatePageReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) JiraAddComment(arg1 context.Context, arg2 string, arg3 string) error {
	fake.jiraAddCommentMutex.Lock()
	ret, specificReturn := fake.jiraAddCommentReturnsOnCall[len(fake.jiraAddCommentArgsForCall)]
	fake.jiraAddCommentArgsForCall = append(fake.jiraAddCommentArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.JiraAddCommentStub
	fakeReturns := fake.jiraAddCommentReturns
	fake.recordInvocation("JiraAddComment", []interface{}{arg1, arg2, arg3})
	fake.jiraAddCommentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) JiraAddCommentCallCount() int {
	fake.jiraAddCommentMutex.RLock()
	defer fake.jiraAddCommentMutex.RUnlock()
	return len(fake.jiraAddCommentArgsForCall)
}

func (fake *FakeService) JiraAddCommentCalls(stub func(context.Context, string, string) error) {
	fake.jiraAddCommentMutex.Lock()
	defer fake.jiraAddCommentMutex.Unlock()
	fake.JiraAddCommentStub = stub
}

func (fake *FakeService) JiraAddCommentArgsForCall(i int) (context.Context, string, string) {
	fake.jiraAddCommentMutex.RLock()
	defer fake.jiraAddCommentMutex.RUnlock()
	argsForCall := fake.jiraAddCommentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) JiraAddCommentReturns(result1 error) {
	fake.jiraAddCommentMutex.Lock()
	defer fake.jiraAddCommentMutex.Unlock()
	fake.JiraAddCommentStub = nil
	fake.jiraAddCommentReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) JiraAddCommentReturnsOnCall(i int, result1 error) {
	fake.jiraAddCommentMutex.Lock()
	defer fake.jiraAddCommentMutex.Unlock()
	fake.JiraAddCommentStub = nil
	if fake.jiraAddCommentReturnsOnCall == nil {
		fake.jiraAddCommentReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.jiraAddCommentReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) JiraCreateIssue(arg1 context.Context, arg2 atlassian.CreateIssueInput) (*atlassian.IssueSummary, error) {
	fake.jiraCreateIssueMutex.Lock()
	ret, specificReturn := fake.jiraCreateIssueReturnsOnCall[len(fake.jiraCreateIssueArgsForCall)]
	fake.jiraCreateIssueArgsForCall = append(fake.jiraCreateIssueArgsForCall, struct {
		arg1 context.Context
		arg2 atlassian.CreateIssueInput
	}{arg1, arg2})
	stub := fake.JiraCreateIssueStub
	fakeReturns := fake.jiraCreateIssueReturns
	fake.recordInvocation("JiraCreateIssue", []interface{}{arg1, arg2})
	fake.jiraCreateIssueMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) JiraCreateIssueCallCount() int {
	fake.jiraCreateIssueMutex.RLock()
	defer fake.jiraCreateIssueMutex.RUnlock()
	return len(fake.jiraCreateIssueArgsForCall)
}

func (fake *FakeService) JiraCreateIssueCalls(stub func(context.Context, atlassian.CreateIssueInput) (*atlassian.IssueSummary, error)) {
	fake.jiraCreateIssueMutex.Lock()
	defer fake.jiraCreateIssueMutex.Unlock()
	fake.JiraCreateIssueStub = stub
}

func (fake *FakeService) JiraCreateIssueArgsForCall(i int) (context.Context, atlassian.CreateIssueInput) {
	fake.jiraCreateIssueMutex.RLock()
	defer fake.jiraCreateIssueMutex.RUnlock()
	argsForCall := fake.jiraCreateIssueArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) JiraCreateIssueReturns(result1 *atlassian.IssueSummary, result2 error) {
	fake.jiraCreateIssueMutex.Lock()
	defer fake.jiraCreateIssueMutex.Unlock()
	fake.JiraCreateIssueStub = nil
	fake.jiraCreateIssueReturns = struct {
		result1 *atlassian.IssueSummary
		result2 error
	}{result1, result2}
}

func (fake *FakeService) JiraCreateIssueReturnsOnCall(i int, result1 *atlassian.IssueSummary, result2 error) {
	fake.jiraCreateIssueMutex.Lock()
	defer fake.jiraCreateIssueMutex.Unlock()
	fake.JiraCreateIssueStub = nil
	if fake.jiraCreateIssueReturnsOnCall == nil {
		fake.jiraCreateIssueReturnsOnCall = make(map[int]struct {
			result1 *atlassian.IssueSummary
			result2 error
		})
	}
	fake.jiraCreateIssueReturnsOnCall[i] = struct {
		result1 *atlassian.IssueSummary
		result2 error
	}{result1, result2}
}

func (fake *FakeService) JiraGetIssue(arg1 context.Context, arg2 string) (*atlassian.IssueDetail, error) {
	fake.jiraGetIssueMutex.Lock()
	ret, specificReturn := fake.jiraGetIssueReturnsOnCall[len(fake.jiraGetIssueArgsForCall)]
	fake.jiraGetIssueArgsForCall = append(fake.jiraGetIssueArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.JiraGetIssueStub
	fakeReturns := fake.jiraGetIssueReturns
	fake.recordInvocation("JiraGetIssue", []interface{}{arg1, arg2})
	fake.jiraGetIssueMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) JiraGetIssueCallCount() int {
	fake.jiraGetIssueMutex.RLock()
	defer fake.jiraGetIssueMutex.RUnlock()
	return len(fake.jiraGetIssueArgsForCall)
}

func (fake *FakeService) JiraGetIssueCalls(stub func(context.Context, string) (*atlassian.IssueDetail, error)) {
	fake.jiraGetIssueMutex.Lock()
	defer fake.jiraGetIssueMutex.Unlock()
	fake.JiraGetIssueStub = stub
}

func (fake *FakeService) JiraGetIssueArgsForCall(i int) (context.Context, string) {
	fake.jiraGetIssueMutex.RLock()
	defer fake.jiraGetIssueMutex.RUnlock()
	argsForCall := fake.jiraGetIssueArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) JiraGetIssueReturns(result1 *atlassian.IssueDetail, result2 error) {
	fake.jiraGetIssueMutex.Lock()
	defer fake.jiraGetIssueMutex.Unlock()
	fake.JiraGetIssueStub = nil
	fake.jiraGetIssueReturns = struct {
		result1 *atlassian.IssueDetail
		result2 error
	}{result1, result2}
}

func (fake *FakeService) JiraGetIssueReturnsOnCall(i int, result1 *atlassian.IssueDetail, result2 error) {
	fake.jiraGetIssueMutex.Lock()
	defer fake.jiraGetIssueMutex.Unlock()
	fake.JiraGetIssueStub = nil
	if fake.jiraGetIssueReturnsOnCall == nil {
		fake.jiraGetIssueReturnsOnCall = make(map[int]struct {
			result1 *atlassian.IssueDetail
			result2 error
		})
	}
	fake.jiraGetIssueReturnsOnCall[i] = struct {
		result1 *atlassian.IssueDetail
		result2 error
	}{result1, result2}
}

func (fake *FakeService) JiraListTransitions(arg1 context.Context, arg2 string) ([]atlassian.Transition, error) {
	fake.jiraListTransitionsMutex.Lock()
	ret, specificReturn := fake.jiraListTransitionsReturnsOnCall[len(fake.jiraListTransitionsArgsForCall)]
	fake.jiraListTransitionsArgsForCall = append(fake.jiraListTransitionsArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.JiraListTransitionsStub
	fakeReturns := fake.jiraListTransitionsReturns
	fake.recordInvocation("JiraListTransitions", []interface{}{arg1, arg2})
	fake.jiraListTransitionsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) JiraListTransitionsCallCount() int {
	fake.jiraListTransitionsMutex.RLock()
	defer fake.jiraListTransitionsMutex.RUnlock()
	return len(fake.jiraListTransitionsArgsForCall)
}

func (fake *FakeService) JiraListTransitionsCalls(stub func(context.Context, string) ([]atlassian.Transition, error)) {
	fake.jiraListTransitionsMutex.Lock()
	defer fake.jiraListTransitionsMutex.Unlock()
	fake.JiraListTransitionsStub = stub
}

func (fake *FakeService) JiraListTransitionsArgsForCall(i int) (context.Context, string) {
	fake.jiraListTransitionsMutex.RLock()
	defer fake.jiraListTransitionsMutex.RUnlock()
	argsForCall := fake.jiraListTransitionsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) JiraListTransitionsReturns(result1 []atlassian.Transition, result2 error) {
	fake.jiraListTransitionsMutex.Lock()
	defer fake.jiraListTransitionsMutex.Unlock()
	fake.JiraListTransitionsStub = nil
	fake.jiraListTransitionsReturns = struct {
		result1 []atlassian.Transition
		result2 error
	}{result1, result2}
}

func (fake *FakeService) JiraListTransitionsReturnsOnCall(i int, result1 []atlassian.Transition, result2 error) {
	fake.jiraListTransitionsMutex.Lock()
	defer fake.jiraListTransitionsMutex.Unlock()
	fake.JiraListTransitionsStub = nil
	if fake.jiraListTransitionsReturnsOnCall == nil {
		fake.jiraListTransitionsReturnsOnCall = make(map[int]struct {
			result1 []atlassian.Transition
			result2 error
		})
	}
	fake.jiraListTransitionsReturnsOnCall[i] = struct {
		result1 []atlassian.Transition
		result2 error
	}{result1, result2}
}

func (fake *FakeService) JiraSearchIssues(arg1 context.Context, arg2 string, arg3 int) ([]atlassian.IssueSummary, error) {
	fake.jiraSearchIssuesMutex.Lock()
	ret, specificReturn := fake.jiraSearchIssuesReturnsOnCall[len(fake.jiraSearchIssuesArgsForCall)]
	fake.jiraSearchIssuesArgsForCall = append(fake.jiraSearchIssuesArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.JiraSearchIssuesStub
	fakeReturns := fake.jiraSearchIssuesReturns
	fake.recordInvocation("JiraSearchIssues", []interface{}{arg1, arg2, arg3})
	fake.jiraSearchIssuesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) JiraSearchIssuesCallCount() int {
	fake.jiraSearchIssuesMutex.RLock()
	defer fake.jiraSearchIssuesMutex.RUnlock()
	return len(fake.jiraSearchIssuesArgsForCall)
}

func (fake *FakeService) JiraSearchIssuesCalls(stub func(context.Context, string, int) ([]atlassian.IssueSummary, error)) {
	fake.jiraSearchIssuesMutex.Lock()
	defer fake.jiraSearchIssuesMutex.Unlock()
	fake.JiraSearchIssuesStub = stub
}

func (fake *FakeService) JiraSearchIssuesArgsForCall(i int) (context.Context, string, int) {
	fake.jiraSearchIssuesMutex.RLock()
	defer fake.jiraSearchIssuesMutex.RUnlock()
	argsForCall := fake.jiraSearchIssuesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) JiraSearchIssuesReturns(result1 []atlassian.IssueSummary, result2 error) {
	fake.jiraSearchIssuesMutex.Lock()
	defer fake.jiraSearchIssuesMutex.Unlock()
	fake.JiraSearchIssuesStub = nil
	fake.jiraSearchIssuesReturns = struct {
		result1 []atlassian.IssueSummary
		result2 error
	}{result1, result2}
}

func (fake *FakeService) JiraSearchIssuesReturnsOnCall(i int, result1 []atlassian.IssueSummary, result2 error) {
	fake.jiraSearchIssuesMutex.Lock()
	defer fake.jiraSearchIssuesMutex.Unlock()
	fake.JiraSearchIssuesStub = nil
	if fake.jiraSearchIssuesReturnsOnCall == nil {
		fake.jiraSearchIssuesReturnsOnCall = make(map[int]struct {
			result1 []atlassian.IssueSummary
			result2 error
		})
	}
	fake.jiraSearchIssuesReturnsOnCall[i] = struct {
		result1 []atlassian.IssueSummary
		result2 error
	}{result1, result2}
}

func (fake *FakeService) JiraTransitionIssue(arg1 context.Context, arg2 string, arg3 string) error {
	fake.jiraTransitionIssueMutex.Lock()
	ret, specificReturn := fake.jiraTransitionIssueReturnsOnCall[len(fake.jiraTransitionIssueArgsForCall)]
	fake.jiraTransitionIssueArgsForCall = append(fake.jiraTransitionIssueArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.JiraTransitionIssueStub
	fakeReturns := fake.jiraTransitionIssueReturns
	fake.recordInvocation("JiraTransitionIssue", []interface{}{arg1, arg2, arg3})
	fake.jiraTransitionIssueMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) JiraTransitionIssueCallCount() int {
	fake.jiraTransitionIssueMutex.RLock()
	defer fake.jiraTransitionIssueMutex.RUnlock()
	return len(fake.jiraTransitionIssueArgsForCall)
}

func (fake *FakeService) JiraTransitionIssueCalls(stub func(context.Context, string, string) error) {
	fake.jiraTransitionIssueMutex.Lock()
	defer fake.jiraTransitionIssueMutex.Unlock()
	fake.JiraTransitionIssueStub = stub
}

func (fake *FakeService) JiraTransitionIssueArgsForCall(i int) (context.Context, string, string) {
	fake.jiraTransitionIssueMutex.RLock()
	defer fake.jiraTransitionIssueMutex.RUnlock()
	argsForCall := fake.jiraTransitionIssueArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) JiraTransitionIssueReturns(result1 error) {
	fake.jiraTransitionIssueMutex.Lock()
	defer fake.jiraTransitionIssueMutex.Unlock()
	fake.JiraTransitionIssueStub = nil
	fake.jiraTransitionIssueReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) JiraTransitionIssueReturnsOnCall(i int, result1 error) {
	fake.jiraTransitionIssueMutex.Lock()
	defer fake.jiraTransitionIssueMutex.Unlock()
	fake.JiraTransitionIssueStub = nil
	if fake.jiraTransitionIssueReturnsOnCall == nil {
		fake.jiraTransitionIssueReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.jiraTransitionIssueReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) JiraUpdateIssue(arg1 context.Context, arg2 string, arg3 atlassian.UpdateIssueInput) error {
	fake.jiraUpdateIssueMutex.Lock()
	ret, specificReturn := fake.jiraUpdateIssueReturnsOnCall[len(fake.jiraUpdateIssueArgsForCall)]
	fake.jiraUpdateIssueArgsForCall = append(fake.jiraUpdateIssueArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 atlassian.UpdateIssueInput
	}{arg1, arg2, arg3})
	stub := fake.JiraUpdateIssueStub
	fakeReturns := fake.jiraUpdateIssueReturns
	fake.recordInvocation("JiraUpdateIssue", []interface{}{arg1, arg2, arg3})
	fake.jiraUpdateIssueMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) JiraUpdateIssueCallCount() int {
	fake.jiraUpdateIssueMutex.RLock()
	defer fake.jiraUpdateIssueMutex.RUnlock()
	return len(fake.jiraUpdateIssueArgsForCall)
}

func (fake *FakeService) JiraUpdateIssueCalls(stub func(context.Context, string, atlassian.UpdateIssueInput) error) {
	fake.jiraUpdateIssueMutex.Lock()
	defer fake.jiraUpdateIssueMutex.Unlock()
	fake.JiraUpdateIssueStub = stub
}

func (fake *FakeService) JiraUpdateIssueArgsForCall(i int) (context.Context, string, atlassian.UpdateIssueInput) {
	fake.jiraUpdateIssueMutex.RLock()
	defer fake.jiraUpdateIssueMutex.RUnlock()
	argsForCall := fake.jiraUpdateIssueArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) JiraUpdateIssueReturns(result1 error) {
	fake.jiraUpdateIssueMutex.Lock()
	defer fake.jiraUpdateIssueMutex.Unlock()
	fake.JiraUpdateIssueStub = nil
	fake.jiraUpdateIssueReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) JiraUpdateIssueReturnsOnCall(i int, result1 error) {
	fake.jiraUpdateIssueMutex.Lock()
	defer fake.jiraUpdateIssueMutex.Unlock()
	fake.JiraUpdateIssueStub = nil
	if fake.jiraUpdateIssueReturnsOnCall == nil {
		fake.jiraUpdateIssueReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.jiraUpdateIssueReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) Validate(arg1 context.Context) error {
	fake.validateMutex.Lock()
	ret, specificReturn := fake.validateReturnsOnCall[len(fake.validateArgsForCall)]
	fake.validateArgsForCall = append(fake.validateArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ValidateStub
	fakeReturns := fake.validateReturns
	fake.recordInvocation("Validate", []interface{}{arg1})
	fake.validateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) ValidateCallCount() int {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	return len(fake.validateArgsForCall)
}

func (fake *FakeService) ValidateCalls(stub func(context.Context) error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = stub
}

func (fake *FakeService) ValidateArgsForCall(i int) context.Context {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	argsForCall := fake.validateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) ValidateReturns(result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	fake.validateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) ValidateReturnsOnCall(i int, result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	if fake.validateReturnsOnCall == nil {
		fake.validateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ atlassian.Service = new(FakeService)
