// Code generated by counterfeiter. DO NOT EDIT.
package reactreefakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/reactree"
)

type FakeActionReflector struct {
	ReflectStub        func(context.Context, reactree.ReflectionRequest) (reactree.ReflectionResult, error)
	reflectMutex       sync.RWMutex
	reflectArgsForCall []struct {
		arg1 context.Context
		arg2 reactree.ReflectionRequest
	}
	reflectReturns struct {
		result1 reactree.ReflectionResult
		result2 error
	}
	reflectReturnsOnCall map[int]struct {
		result1 reactree.ReflectionResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeActionReflector) Reflect(arg1 context.Context, arg2 reactree.ReflectionRequest) (reactree.ReflectionResult, error) {
	fake.reflectMutex.Lock()
	ret, specificReturn := fake.reflectReturnsOnCall[len(fake.reflectArgsForCall)]
	fake.reflectArgsForCall = append(fake.reflectArgsForCall, struct {
		arg1 context.Context
		arg2 reactree.ReflectionRequest
	}{arg1, arg2})
	stub := fake.ReflectStub
	fakeReturns := fake.reflectReturns
	fake.recordInvocation("Reflect", []interface{}{arg1, arg2})
	fake.reflectMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeActionReflector) ReflectCallCount() int {
	fake.reflectMutex.RLock()
	defer fake.reflectMutex.RUnlock()
	return len(fake.reflectArgsForCall)
}

func (fake *FakeActionReflector) ReflectCalls(stub func(context.Context, reactree.ReflectionRequest) (reactree.ReflectionResult, error)) {
	fake.reflectMutex.Lock()
	defer fake.reflectMutex.Unlock()
	fake.ReflectStub = stub
}

func (fake *FakeActionReflector) ReflectArgsForCall(i int) (context.Context, reactree.ReflectionRequest) {
	fake.reflectMutex.RLock()
	defer fake.reflectMutex.RUnlock()
	argsForCall := fake.reflectArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeActionReflector) ReflectReturns(result1 reactree.ReflectionResult, result2 error) {
	fake.reflectMutex.Lock()
	defer fake.reflectMutex.Unlock()
	fake.ReflectStub = nil
	fake.reflectReturns = struct {
		result1 reactree.ReflectionResult
		result2 error
	}{result1, result2}
}

func (fake *FakeActionReflector) ReflectReturnsOnCall(i int, result1 reactree.ReflectionResult, result2 error) {
	fake.reflectMutex.Lock()
	defer fake.reflectMutex.Unlock()
	fake.ReflectStub = nil
	if fake.reflectReturnsOnCall == nil {
		fake.reflectReturnsOnCall = make(map[int]struct {
			result1 reactree.ReflectionResult
			result2 error
		})
	}
	fake.reflectReturnsOnCall[i] = struct {
		result1 reactree.ReflectionResult
		result2 error
	}{result1, result2}
}

func (fake *FakeActionReflector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeActionReflector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ reactree.ActionReflector = new(FakeActionReflector)
