// Code generated by counterfeiter. DO NOT EDIT.
package gdrivefakes

import (
	"context"
	"sync"
	"time"

	"github.com/stackgenhq/genie/pkg/tools/google/gdrive"
)

type FakeService struct {
	GetFileStub        func(context.Context, string) (*gdrive.FileDetail, error)
	getFileMutex       sync.RWMutex
	getFileArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getFileReturns struct {
		result1 *gdrive.FileDetail
		result2 error
	}
	getFileReturnsOnCall map[int]struct {
		result1 *gdrive.FileDetail
		result2 error
	}
	ListFolderStub        func(context.Context, string, int) ([]gdrive.FileInfo, error)
	listFolderMutex       sync.RWMutex
	listFolderArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}
	listFolderReturns struct {
		result1 []gdrive.FileInfo
		result2 error
	}
	listFolderReturnsOnCall map[int]struct {
		result1 []gdrive.FileInfo
		result2 error
	}
	ListFolderModifiedSinceStub        func(context.Context, string, time.Time, int) ([]gdrive.FileInfo, error)
	listFolderModifiedSinceMutex       sync.RWMutex
	listFolderModifiedSinceArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 time.Time
		arg4 int
	}
	listFolderModifiedSinceReturns struct {
		result1 []gdrive.FileInfo
		result2 error
	}
	listFolderModifiedSinceReturnsOnCall map[int]struct {
		result1 []gdrive.FileInfo
		result2 error
	}
	ReadFileStub        func(context.Context, string) (string, error)
	readFileMutex       sync.RWMutex
	readFileArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	readFileReturns struct {
		result1 string
		result2 error
	}
	readFileReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	SearchStub        func(context.Context, string, int) ([]gdrive.FileInfo, error)
	searchMutex       sync.RWMutex
	searchArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}
	searchReturns struct {
		result1 []gdrive.FileInfo
		result2 error
	}
	searchReturnsOnCall map[int]struct {
		result1 []gdrive.FileInfo
		result2 error
	}
	ValidateStub        func(context.Context) error
	validateMutex       sync.RWMutex
	validateArgsForCall []struct {
		arg1 context.Context
	}
	validateReturns struct {
		result1 error
	}
	validateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeService) GetFile(arg1 context.Context, arg2 string) (*gdrive.FileDetail, error) {
	fake.getFileMutex.Lock()
	ret, specificReturn := fake.getFileReturnsOnCall[len(fake.getFileArgsForCall)]
	fake.getFileArgsForCall = append(fake.getFileArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetFileStub
	fakeReturns := fake.getFileReturns
	fake.recordInvocation("GetFile", []interface{}{arg1, arg2})
	fake.getFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) GetFileCallCount() int {
	fake.getFileMutex.RLock()
	defer fake.getFileMutex.RUnlock()
	return len(fake.getFileArgsForCall)
}

func (fake *FakeService) GetFileCalls(stub func(context.Context, string) (*gdrive.FileDetail, error)) {
	fake.getFileMutex.Lock()
	defer fake.getFileMutex.Unlock()
	fake.GetFileStub = stub
}

func (fake *FakeService) GetFileArgsForCall(i int) (context.Context, string) {
	fake.getFileMutex.RLock()
	defer fake.getFileMutex.RUnlock()
	argsForCall := fake.getFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) GetFileReturns(result1 *gdrive.FileDetail, result2 error) {
	fake.getFileMutex.Lock()
	defer fake.getFileMutex.Unlock()
	fake.GetFileStub = nil
	fake.getFileReturns = struct {
		result1 *gdrive.FileDetail
		result2 error
	}{result1, result2}
}

func (fake *FakeService) GetFileReturnsOnCall(i int, result1 *gdrive.FileDetail, result2 error) {
	fake.getFileMutex.Lock()
	defer fake.getFileMutex.Unlock()
	fake.GetFileStub = nil
	if fake.getFileReturnsOnCall == nil {
		fake.getFileReturnsOnCall = make(map[int]struct {
			result1 *gdrive.FileDetail
			result2 error
		})
	}
	fake.getFileReturnsOnCall[i] = struct {
		result1 *gdrive.FileDetail
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListFolder(arg1 context.Context, arg2 string, arg3 int) ([]gdrive.FileInfo, error) {
	fake.listFolderMutex.Lock()
	ret, specificReturn := fake.listFolderReturnsOnCall[len(fake.listFolderArgsForCall)]
	fake.listFolderArgsForCall = append(fake.listFolderArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.ListFolderStub
	fakeReturns := fake.listFolderReturns
	fake.recordInvocation("ListFolder", []interface{}{arg1, arg2, arg3})
	fake.listFolderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ListFolderCallCount() int {
	fake.listFolderMutex.RLock()
	defer fake.listFolderMutex.RUnlock()
	return len(fake.listFolderArgsForCall)
}

func (fake *FakeService) ListFolderCalls(stub func(context.Context, string, int) ([]gdrive.FileInfo, error)) {
	fake.listFolderMutex.Lock()
	defer fake.listFolderMutex.Unlock()
	fake.ListFolderStub = stub
}

func (fake *FakeService) ListFolderArgsForCall(i int) (context.Context, string, int) {
	fake.listFolderMutex.RLock()
	defer fake.listFolderMutex.RUnlock()
	argsForCall := fake.listFolderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) ListFolderReturns(result1 []gdrive.FileInfo, result2 error) {
	fake.listFolderMutex.Lock()
	defer fake.listFolderMutex.Unlock()
	fake.ListFolderStub = nil
	fake.listFolderReturns = struct {
		result1 []gdrive.FileInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListFolderReturnsOnCall(i int, result1 []gdrive.FileInfo, result2 error) {
	fake.listFolderMutex.Lock()
	defer fake.listFolderMutex.Unlock()
	fake.ListFolderStub = nil
	if fake.listFolderReturnsOnCall == nil {
		fake.listFolderReturnsOnCall = make(map[int]struct {
			result1 []gdrive.FileInfo
			result2 error
		})
	}
	fake.listFolderReturnsOnCall[i] = struct {
		result1 []gdrive.FileInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListFolderModifiedSince(arg1 context.Context, arg2 string, arg3 time.Time, arg4 int) ([]gdrive.FileInfo, error) {
	fake.listFolderModifiedSinceMutex.Lock()
	ret, specificReturn := fake.listFolderModifiedSinceReturnsOnCall[len(fake.listFolderModifiedSinceArgsForCall)]
	fake.listFolderModifiedSinceArgsForCall = append(fake.listFolderModifiedSinceArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 time.Time
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListFolderModifiedSinceStub
	fakeReturns := fake.listFolderModifiedSinceReturns
	fake.recordInvocation("ListFolderModifiedSince", []interface{}{arg1, arg2, arg3, arg4})
	fake.listFolderModifiedSinceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ListFolderModifiedSinceCallCount() int {
	fake.listFolderModifiedSinceMutex.RLock()
	defer fake.listFolderModifiedSinceMutex.RUnlock()
	return len(fake.listFolderModifiedSinceArgsForCall)
}

func (fake *FakeService) ListFolderModifiedSinceCalls(stub func(context.Context, string, time.Time, int) ([]gdrive.FileInfo, error)) {
	fake.listFolderModifiedSinceMutex.Lock()
	defer fake.listFolderModifiedSinceMutex.Unlock()
	fake.ListFolderModifiedSinceStub = stub
}

func (fake *FakeService) ListFolderModifiedSinceArgsForCall(i int) (context.Context, string, time.Time, int) {
	fake.listFolderModifiedSinceMutex.RLock()
	defer fake.listFolderModifiedSinceMutex.RUnlock()
	argsForCall := fake.listFolderModifiedSinceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeService) ListFolderModifiedSinceReturns(result1 []gdrive.FileInfo, result2 error) {
	fake.listFolderModifiedSinceMutex.Lock()
	defer fake.listFolderModifiedSinceMutex.Unlock()
	fake.ListFolderModifiedSinceStub = nil
	fake.listFolderModifiedSinceReturns = struct {
		result1 []gdrive.FileInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ListFolderModifiedSinceReturnsOnCall(i int, result1 []gdrive.FileInfo, result2 error) {
	fake.listFolderModifiedSinceMutex.Lock()
	defer fake.listFolderModifiedSinceMutex.Unlock()
	fake.ListFolderModifiedSinceStub = nil
	if fake.listFolderModifiedSinceReturnsOnCall == nil {
		fake.listFolderModifiedSinceReturnsOnCall = make(map[int]struct {
			result1 []gdrive.FileInfo
			result2 error
		})
	}
	fake.listFolderModifiedSinceReturnsOnCall[i] = struct {
		result1 []gdrive.FileInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ReadFile(arg1 context.Context, arg2 string) (string, error) {
	fake.readFileMutex.Lock()
	ret, specificReturn := fake.readFileReturnsOnCall[len(fake.readFileArgsForCall)]
	fake.readFileArgsForCall = append(fake.readFileArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ReadFileStub
	fakeReturns := fake.readFileReturns
	fake.recordInvocation("ReadFile", []interface{}{arg1, arg2})
	fake.readFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) ReadFileCallCount() int {
	fake.readFileMutex.RLock()
	defer fake.readFileMutex.RUnlock()
	return len(fake.readFileArgsForCall)
}

func (fake *FakeService) ReadFileCalls(stub func(context.Context, string) (string, error)) {
	fake.readFileMutex.Lock()
	defer fake.readFileMutex.Unlock()
	fake.ReadFileStub = stub
}

func (fake *FakeService) ReadFileArgsForCall(i int) (context.Context, string) {
	fake.readFileMutex.RLock()
	defer fake.readFileMutex.RUnlock()
	argsForCall := fake.readFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) ReadFileReturns(result1 string, result2 error) {
	fake.readFileMutex.Lock()
	defer fake.readFileMutex.Unlock()
	fake.ReadFileStub = nil
	fake.readFileReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeService) ReadFileReturnsOnCall(i int, result1 string, result2 error) {
	fake.readFileMutex.Lock()
	defer fake.readFileMutex.Unlock()
	fake.ReadFileStub = nil
	if fake.readFileReturnsOnCall == nil {
		fake.readFileReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.readFileReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeService) Search(arg1 context.Context, arg2 string, arg3 int) ([]gdrive.FileInfo, error) {
	fake.searchMutex.Lock()
	ret, specificReturn := fake.searchReturnsOnCall[len(fake.searchArgsForCall)]
	fake.searchArgsForCall = append(fake.searchArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.SearchStub
	fakeReturns := fake.searchReturns
	fake.recordInvocation("Search", []interface{}{arg1, arg2, arg3})
	fake.searchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeService) SearchCallCount() int {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	return len(fake.searchArgsForCall)
}

func (fake *FakeService) SearchCalls(stub func(context.Context, string, int) ([]gdrive.FileInfo, error)) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = stub
}

func (fake *FakeService) SearchArgsForCall(i int) (context.Context, string, int) {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	argsForCall := fake.searchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeService) SearchReturns(result1 []gdrive.FileInfo, result2 error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = nil
	fake.searchReturns = struct {
		result1 []gdrive.FileInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeService) SearchReturnsOnCall(i int, result1 []gdrive.FileInfo, result2 error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = nil
	if fake.searchReturnsOnCall == nil {
		fake.searchReturnsOnCall = make(map[int]struct {
			result1 []gdrive.FileInfo
			result2 error
		})
	}
	fake.searchReturnsOnCall[i] = struct {
		result1 []gdrive.FileInfo
		result2 error
	}{result1, result2}
}

func (fake *FakeService) Validate(arg1 context.Context) error {
	fake.validateMutex.Lock()
	ret, specificReturn := fake.validateReturnsOnCall[len(fake.validateArgsForCall)]
	fake.validateArgsForCall = append(fake.validateArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ValidateStub
	fakeReturns := fake.validateReturns
	fake.recordInvocation("Validate", []interface{}{arg1})
	fake.validateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) ValidateCallCount() int {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	return len(fake.validateArgsForCall)
}

func (fake *FakeService) ValidateCalls(stub func(context.Context) error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = stub
}

func (fake *FakeService) ValidateArgsForCall(i int) context.Context {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	argsForCall := fake.validateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeService) ValidateReturns(result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	fake.validateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) ValidateReturnsOnCall(i int, result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	if fake.validateReturnsOnCall == nil {
		fake.validateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ gdrive.Service = new(FakeService)
