// Copyright (C) 2026 StackGen, Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by counterfeiter. DO NOT EDIT.
package modelproviderfakes

import (
	"context"
	"sync"

	"trpc.group/trpc-go/trpc-agent-go/model"
)

type FakeModel struct {
	GenerateContentStub        func(context.Context, *model.Request) (<-chan *model.Response, error)
	generateContentMutex       sync.RWMutex
	generateContentArgsForCall []struct {
		arg1 context.Context
		arg2 *model.Request
	}
	generateContentReturns struct {
		result1 <-chan *model.Response
		result2 error
	}
	generateContentReturnsOnCall map[int]struct {
		result1 <-chan *model.Response
		result2 error
	}
	InfoStub        func() model.Info
	infoMutex       sync.RWMutex
	infoArgsForCall []struct {
	}
	infoReturns struct {
		result1 model.Info
	}
	infoReturnsOnCall map[int]struct {
		result1 model.Info
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeModel) GenerateContent(arg1 context.Context, arg2 *model.Request) (<-chan *model.Response, error) {
	fake.generateContentMutex.Lock()
	ret, specificReturn := fake.generateContentReturnsOnCall[len(fake.generateContentArgsForCall)]
	fake.generateContentArgsForCall = append(fake.generateContentArgsForCall, struct {
		arg1 context.Context
		arg2 *model.Request
	}{arg1, arg2})
	stub := fake.GenerateContentStub
	fakeReturns := fake.generateContentReturns
	fake.recordInvocation("GenerateContent", []interface{}{arg1, arg2})
	fake.generateContentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeModel) GenerateContentCallCount() int {
	fake.generateContentMutex.RLock()
	defer fake.generateContentMutex.RUnlock()
	return len(fake.generateContentArgsForCall)
}

func (fake *FakeModel) GenerateContentCalls(stub func(context.Context, *model.Request) (<-chan *model.Response, error)) {
	fake.generateContentMutex.Lock()
	defer fake.generateContentMutex.Unlock()
	fake.GenerateContentStub = stub
}

func (fake *FakeModel) GenerateContentArgsForCall(i int) (context.Context, *model.Request) {
	fake.generateContentMutex.RLock()
	defer fake.generateContentMutex.RUnlock()
	argsForCall := fake.generateContentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeModel) GenerateContentReturns(result1 <-chan *model.Response, result2 error) {
	fake.generateContentMutex.Lock()
	defer fake.generateContentMutex.Unlock()
	fake.GenerateContentStub = nil
	fake.generateContentReturns = struct {
		result1 <-chan *model.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeModel) GenerateContentReturnsOnCall(i int, result1 <-chan *model.Response, result2 error) {
	fake.generateContentMutex.Lock()
	defer fake.generateContentMutex.Unlock()
	fake.GenerateContentStub = nil
	if fake.generateContentReturnsOnCall == nil {
		fake.generateContentReturnsOnCall = make(map[int]struct {
			result1 <-chan *model.Response
			result2 error
		})
	}
	fake.generateContentReturnsOnCall[i] = struct {
		result1 <-chan *model.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeModel) Info() model.Info {
	fake.infoMutex.Lock()
	ret, specificReturn := fake.infoReturnsOnCall[len(fake.infoArgsForCall)]
	fake.infoArgsForCall = append(fake.infoArgsForCall, struct {
	}{})
	stub := fake.InfoStub
	fakeReturns := fake.infoReturns
	fake.recordInvocation("Info", []interface{}{})
	fake.infoMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeModel) InfoCallCount() int {
	fake.infoMutex.RLock()
	defer fake.infoMutex.RUnlock()
	return len(fake.infoArgsForCall)
}

func (fake *FakeModel) InfoCalls(stub func() model.Info) {
	fake.infoMutex.Lock()
	defer fake.infoMutex.Unlock()
	fake.InfoStub = stub
}

func (fake *FakeModel) InfoReturns(result1 model.Info) {
	fake.infoMutex.Lock()
	defer fake.infoMutex.Unlock()
	fake.InfoStub = nil
	fake.infoReturns = struct {
		result1 model.Info
	}{result1}
}

func (fake *FakeModel) InfoReturnsOnCall(i int, result1 model.Info) {
	fake.infoMutex.Lock()
	defer fake.infoMutex.Unlock()
	fake.InfoStub = nil
	if fake.infoReturnsOnCall == nil {
		fake.infoReturnsOnCall = make(map[int]struct {
			result1 model.Info
		})
	}
	fake.infoReturnsOnCall[i] = struct {
		result1 model.Info
	}{result1}
}

func (fake *FakeModel) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeModel) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ model.Model = new(FakeModel)
