// Copyright (C) 2026 StackGen, Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by counterfeiter. DO NOT EDIT.
package modelproviderfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/expert/modelprovider"
)

type FakeModelProvider struct {
	GetModelStub        func(context.Context, modelprovider.TaskType) (modelprovider.ModelMap, error)
	getModelMutex       sync.RWMutex
	getModelArgsForCall []struct {
		arg1 context.Context
		arg2 modelprovider.TaskType
	}
	getModelReturns struct {
		result1 modelprovider.ModelMap
		result2 error
	}
	getModelReturnsOnCall map[int]struct {
		result1 modelprovider.ModelMap
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeModelProvider) GetModel(arg1 context.Context, arg2 modelprovider.TaskType) (modelprovider.ModelMap, error) {
	fake.getModelMutex.Lock()
	ret, specificReturn := fake.getModelReturnsOnCall[len(fake.getModelArgsForCall)]
	fake.getModelArgsForCall = append(fake.getModelArgsForCall, struct {
		arg1 context.Context
		arg2 modelprovider.TaskType
	}{arg1, arg2})
	stub := fake.GetModelStub
	fakeReturns := fake.getModelReturns
	fake.recordInvocation("GetModel", []interface{}{arg1, arg2})
	fake.getModelMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeModelProvider) GetModelCallCount() int {
	fake.getModelMutex.RLock()
	defer fake.getModelMutex.RUnlock()
	return len(fake.getModelArgsForCall)
}

func (fake *FakeModelProvider) GetModelCalls(stub func(context.Context, modelprovider.TaskType) (modelprovider.ModelMap, error)) {
	fake.getModelMutex.Lock()
	defer fake.getModelMutex.Unlock()
	fake.GetModelStub = stub
}

func (fake *FakeModelProvider) GetModelArgsForCall(i int) (context.Context, modelprovider.TaskType) {
	fake.getModelMutex.RLock()
	defer fake.getModelMutex.RUnlock()
	argsForCall := fake.getModelArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeModelProvider) GetModelReturns(result1 modelprovider.ModelMap, result2 error) {
	fake.getModelMutex.Lock()
	defer fake.getModelMutex.Unlock()
	fake.GetModelStub = nil
	fake.getModelReturns = struct {
		result1 modelprovider.ModelMap
		result2 error
	}{result1, result2}
}

func (fake *FakeModelProvider) GetModelReturnsOnCall(i int, result1 modelprovider.ModelMap, result2 error) {
	fake.getModelMutex.Lock()
	defer fake.getModelMutex.Unlock()
	fake.GetModelStub = nil
	if fake.getModelReturnsOnCall == nil {
		fake.getModelReturnsOnCall = make(map[int]struct {
			result1 modelprovider.ModelMap
			result2 error
		})
	}
	fake.getModelReturnsOnCall[i] = struct {
		result1 modelprovider.ModelMap
		result2 error
	}{result1, result2}
}

func (fake *FakeModelProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeModelProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ modelprovider.ModelProvider = new(FakeModelProvider)
