// Code generated by counterfeiter. DO NOT EDIT.
package agentutilsfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/agentutils"
)

type FakeSummarizer struct {
	SummarizeStub        func(context.Context, agentutils.SummarizeRequest) (string, error)
	summarizeMutex       sync.RWMutex
	summarizeArgsForCall []struct {
		arg1 context.Context
		arg2 agentutils.SummarizeRequest
	}
	summarizeReturns struct {
		result1 string
		result2 error
	}
	summarizeReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSummarizer) Summarize(arg1 context.Context, arg2 agentutils.SummarizeRequest) (string, error) {
	fake.summarizeMutex.Lock()
	ret, specificReturn := fake.summarizeReturnsOnCall[len(fake.summarizeArgsForCall)]
	fake.summarizeArgsForCall = append(fake.summarizeArgsForCall, struct {
		arg1 context.Context
		arg2 agentutils.SummarizeRequest
	}{arg1, arg2})
	stub := fake.SummarizeStub
	fakeReturns := fake.summarizeReturns
	fake.recordInvocation("Summarize", []interface{}{arg1, arg2})
	fake.summarizeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSummarizer) SummarizeCallCount() int {
	fake.summarizeMutex.RLock()
	defer fake.summarizeMutex.RUnlock()
	return len(fake.summarizeArgsForCall)
}

func (fake *FakeSummarizer) SummarizeCalls(stub func(context.Context, agentutils.SummarizeRequest) (string, error)) {
	fake.summarizeMutex.Lock()
	defer fake.summarizeMutex.Unlock()
	fake.SummarizeStub = stub
}

func (fake *FakeSummarizer) SummarizeArgsForCall(i int) (context.Context, agentutils.SummarizeRequest) {
	fake.summarizeMutex.RLock()
	defer fake.summarizeMutex.RUnlock()
	argsForCall := fake.summarizeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSummarizer) SummarizeReturns(result1 string, result2 error) {
	fake.summarizeMutex.Lock()
	defer fake.summarizeMutex.Unlock()
	fake.SummarizeStub = nil
	fake.summarizeReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeSummarizer) SummarizeReturnsOnCall(i int, result1 string, result2 error) {
	fake.summarizeMutex.Lock()
	defer fake.summarizeMutex.Unlock()
	fake.SummarizeStub = nil
	if fake.summarizeReturnsOnCall == nil {
		fake.summarizeReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.summarizeReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeSummarizer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSummarizer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ agentutils.Summarizer = new(FakeSummarizer)
