// Code generated by counterfeiter. DO NOT EDIT.
package graphfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/memory/graph"
)

type FakeIStore struct {
	AddEntityStub        func(context.Context, graph.Entity) error
	addEntityMutex       sync.RWMutex
	addEntityArgsForCall []struct {
		arg1 context.Context
		arg2 graph.Entity
	}
	addEntityReturns struct {
		result1 error
	}
	addEntityReturnsOnCall map[int]struct {
		result1 error
	}
	AddRelationStub        func(context.Context, graph.Relation) error
	addRelationMutex       sync.RWMutex
	addRelationArgsForCall []struct {
		arg1 context.Context
		arg2 graph.Relation
	}
	addRelationReturns struct {
		result1 error
	}
	addRelationReturnsOnCall map[int]struct {
		result1 error
	}
	CloseStub        func(context.Context) error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
		arg1 context.Context
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteAllStub        func(context.Context) error
	deleteAllMutex       sync.RWMutex
	deleteAllArgsForCall []struct {
		arg1 context.Context
	}
	deleteAllReturns struct {
		result1 error
	}
	deleteAllReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteEntityStub        func(context.Context, string) error
	deleteEntityMutex       sync.RWMutex
	deleteEntityArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	deleteEntityReturns struct {
		result1 error
	}
	deleteEntityReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteRelationStub        func(context.Context, graph.Relation) error
	deleteRelationMutex       sync.RWMutex
	deleteRelationArgsForCall []struct {
		arg1 context.Context
		arg2 graph.Relation
	}
	deleteRelationReturns struct {
		result1 error
	}
	deleteRelationReturnsOnCall map[int]struct {
		result1 error
	}
	GetEntityStub        func(context.Context, string) (*graph.Entity, error)
	getEntityMutex       sync.RWMutex
	getEntityArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getEntityReturns struct {
		result1 *graph.Entity
		result2 error
	}
	getEntityReturnsOnCall map[int]struct {
		result1 *graph.Entity
		result2 error
	}
	NeighborsStub        func(context.Context, string, int) ([]graph.Neighbor, error)
	neighborsMutex       sync.RWMutex
	neighborsArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}
	neighborsReturns struct {
		result1 []graph.Neighbor
		result2 error
	}
	neighborsReturnsOnCall map[int]struct {
		result1 []graph.Neighbor
		result2 error
	}
	RelationsInStub        func(context.Context, string) ([]graph.Relation, error)
	relationsInMutex       sync.RWMutex
	relationsInArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	relationsInReturns struct {
		result1 []graph.Relation
		result2 error
	}
	relationsInReturnsOnCall map[int]struct {
		result1 []graph.Relation
		result2 error
	}
	RelationsOutStub        func(context.Context, string) ([]graph.Relation, error)
	relationsOutMutex       sync.RWMutex
	relationsOutArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	relationsOutReturns struct {
		result1 []graph.Relation
		result2 error
	}
	relationsOutReturnsOnCall map[int]struct {
		result1 []graph.Relation
		result2 error
	}
	ShortestPathStub        func(context.Context, string, string) ([]string, error)
	shortestPathMutex       sync.RWMutex
	shortestPathArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	shortestPathReturns struct {
		result1 []string
		result2 error
	}
	shortestPathReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeIStore) AddEntity(arg1 context.Context, arg2 graph.Entity) error {
	fake.addEntityMutex.Lock()
	ret, specificReturn := fake.addEntityReturnsOnCall[len(fake.addEntityArgsForCall)]
	fake.addEntityArgsForCall = append(fake.addEntityArgsForCall, struct {
		arg1 context.Context
		arg2 graph.Entity
	}{arg1, arg2})
	stub := fake.AddEntityStub
	fakeReturns := fake.addEntityReturns
	fake.recordInvocation("AddEntity", []interface{}{arg1, arg2})
	fake.addEntityMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIStore) AddEntityCallCount() int {
	fake.addEntityMutex.RLock()
	defer fake.addEntityMutex.RUnlock()
	return len(fake.addEntityArgsForCall)
}

func (fake *FakeIStore) AddEntityCalls(stub func(context.Context, graph.Entity) error) {
	fake.addEntityMutex.Lock()
	defer fake.addEntityMutex.Unlock()
	fake.AddEntityStub = stub
}

func (fake *FakeIStore) AddEntityArgsForCall(i int) (context.Context, graph.Entity) {
	fake.addEntityMutex.RLock()
	defer fake.addEntityMutex.RUnlock()
	argsForCall := fake.addEntityArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeIStore) AddEntityReturns(result1 error) {
	fake.addEntityMutex.Lock()
	defer fake.addEntityMutex.Unlock()
	fake.AddEntityStub = nil
	fake.addEntityReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) AddEntityReturnsOnCall(i int, result1 error) {
	fake.addEntityMutex.Lock()
	defer fake.addEntityMutex.Unlock()
	fake.AddEntityStub = nil
	if fake.addEntityReturnsOnCall == nil {
		fake.addEntityReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addEntityReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) AddRelation(arg1 context.Context, arg2 graph.Relation) error {
	fake.addRelationMutex.Lock()
	ret, specificReturn := fake.addRelationReturnsOnCall[len(fake.addRelationArgsForCall)]
	fake.addRelationArgsForCall = append(fake.addRelationArgsForCall, struct {
		arg1 context.Context
		arg2 graph.Relation
	}{arg1, arg2})
	stub := fake.AddRelationStub
	fakeReturns := fake.addRelationReturns
	fake.recordInvocation("AddRelation", []interface{}{arg1, arg2})
	fake.addRelationMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIStore) AddRelationCallCount() int {
	fake.addRelationMutex.RLock()
	defer fake.addRelationMutex.RUnlock()
	return len(fake.addRelationArgsForCall)
}

func (fake *FakeIStore) AddRelationCalls(stub func(context.Context, graph.Relation) error) {
	fake.addRelationMutex.Lock()
	defer fake.addRelationMutex.Unlock()
	fake.AddRelationStub = stub
}

func (fake *FakeIStore) AddRelationArgsForCall(i int) (context.Context, graph.Relation) {
	fake.addRelationMutex.RLock()
	defer fake.addRelationMutex.RUnlock()
	argsForCall := fake.addRelationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeIStore) AddRelationReturns(result1 error) {
	fake.addRelationMutex.Lock()
	defer fake.addRelationMutex.Unlock()
	fake.AddRelationStub = nil
	fake.addRelationReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) AddRelationReturnsOnCall(i int, result1 error) {
	fake.addRelationMutex.Lock()
	defer fake.addRelationMutex.Unlock()
	fake.AddRelationStub = nil
	if fake.addRelationReturnsOnCall == nil {
		fake.addRelationReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addRelationReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) Close(arg1 context.Context) error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{arg1})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIStore) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeIStore) CloseCalls(stub func(context.Context) error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeIStore) CloseArgsForCall(i int) context.Context {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	argsForCall := fake.closeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeIStore) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) DeleteAll(arg1 context.Context) error {
	fake.deleteAllMutex.Lock()
	ret, specificReturn := fake.deleteAllReturnsOnCall[len(fake.deleteAllArgsForCall)]
	fake.deleteAllArgsForCall = append(fake.deleteAllArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.DeleteAllStub
	fakeReturns := fake.deleteAllReturns
	fake.recordInvocation("DeleteAll", []interface{}{arg1})
	fake.deleteAllMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIStore) DeleteAllCallCount() int {
	fake.deleteAllMutex.RLock()
	defer fake.deleteAllMutex.RUnlock()
	return len(fake.deleteAllArgsForCall)
}

func (fake *FakeIStore) DeleteAllCalls(stub func(context.Context) error) {
	fake.deleteAllMutex.Lock()
	defer fake.deleteAllMutex.Unlock()
	fake.DeleteAllStub = stub
}

func (fake *FakeIStore) DeleteAllArgsForCall(i int) context.Context {
	fake.deleteAllMutex.RLock()
	defer fake.deleteAllMutex.RUnlock()
	argsForCall := fake.deleteAllArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeIStore) DeleteAllReturns(result1 error) {
	fake.deleteAllMutex.Lock()
	defer fake.deleteAllMutex.Unlock()
	fake.DeleteAllStub = nil
	fake.deleteAllReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) DeleteAllReturnsOnCall(i int, result1 error) {
	fake.deleteAllMutex.Lock()
	defer fake.deleteAllMutex.Unlock()
	fake.DeleteAllStub = nil
	if fake.deleteAllReturnsOnCall == nil {
		fake.deleteAllReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteAllReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) DeleteEntity(arg1 context.Context, arg2 string) error {
	fake.deleteEntityMutex.Lock()
	ret, specificReturn := fake.deleteEntityReturnsOnCall[len(fake.deleteEntityArgsForCall)]
	fake.deleteEntityArgsForCall = append(fake.deleteEntityArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.DeleteEntityStub
	fakeReturns := fake.deleteEntityReturns
	fake.recordInvocation("DeleteEntity", []interface{}{arg1, arg2})
	fake.deleteEntityMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIStore) DeleteEntityCallCount() int {
	fake.deleteEntityMutex.RLock()
	defer fake.deleteEntityMutex.RUnlock()
	return len(fake.deleteEntityArgsForCall)
}

func (fake *FakeIStore) DeleteEntityCalls(stub func(context.Context, string) error) {
	fake.deleteEntityMutex.Lock()
	defer fake.deleteEntityMutex.Unlock()
	fake.DeleteEntityStub = stub
}

func (fake *FakeIStore) DeleteEntityArgsForCall(i int) (context.Context, string) {
	fake.deleteEntityMutex.RLock()
	defer fake.deleteEntityMutex.RUnlock()
	argsForCall := fake.deleteEntityArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeIStore) DeleteEntityReturns(result1 error) {
	fake.deleteEntityMutex.Lock()
	defer fake.deleteEntityMutex.Unlock()
	fake.DeleteEntityStub = nil
	fake.deleteEntityReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) DeleteEntityReturnsOnCall(i int, result1 error) {
	fake.deleteEntityMutex.Lock()
	defer fake.deleteEntityMutex.Unlock()
	fake.DeleteEntityStub = nil
	if fake.deleteEntityReturnsOnCall == nil {
		fake.deleteEntityReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteEntityReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) DeleteRelation(arg1 context.Context, arg2 graph.Relation) error {
	fake.deleteRelationMutex.Lock()
	ret, specificReturn := fake.deleteRelationReturnsOnCall[len(fake.deleteRelationArgsForCall)]
	fake.deleteRelationArgsForCall = append(fake.deleteRelationArgsForCall, struct {
		arg1 context.Context
		arg2 graph.Relation
	}{arg1, arg2})
	stub := fake.DeleteRelationStub
	fakeReturns := fake.deleteRelationReturns
	fake.recordInvocation("DeleteRelation", []interface{}{arg1, arg2})
	fake.deleteRelationMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIStore) DeleteRelationCallCount() int {
	fake.deleteRelationMutex.RLock()
	defer fake.deleteRelationMutex.RUnlock()
	return len(fake.deleteRelationArgsForCall)
}

func (fake *FakeIStore) DeleteRelationCalls(stub func(context.Context, graph.Relation) error) {
	fake.deleteRelationMutex.Lock()
	defer fake.deleteRelationMutex.Unlock()
	fake.DeleteRelationStub = stub
}

func (fake *FakeIStore) DeleteRelationArgsForCall(i int) (context.Context, graph.Relation) {
	fake.deleteRelationMutex.RLock()
	defer fake.deleteRelationMutex.RUnlock()
	argsForCall := fake.deleteRelationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeIStore) DeleteRelationReturns(result1 error) {
	fake.deleteRelationMutex.Lock()
	defer fake.deleteRelationMutex.Unlock()
	fake.DeleteRelationStub = nil
	fake.deleteRelationReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) DeleteRelationReturnsOnCall(i int, result1 error) {
	fake.deleteRelationMutex.Lock()
	defer fake.deleteRelationMutex.Unlock()
	fake.DeleteRelationStub = nil
	if fake.deleteRelationReturnsOnCall == nil {
		fake.deleteRelationReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteRelationReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) GetEntity(arg1 context.Context, arg2 string) (*graph.Entity, error) {
	fake.getEntityMutex.Lock()
	ret, specificReturn := fake.getEntityReturnsOnCall[len(fake.getEntityArgsForCall)]
	fake.getEntityArgsForCall = append(fake.getEntityArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetEntityStub
	fakeReturns := fake.getEntityReturns
	fake.recordInvocation("GetEntity", []interface{}{arg1, arg2})
	fake.getEntityMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeIStore) GetEntityCallCount() int {
	fake.getEntityMutex.RLock()
	defer fake.getEntityMutex.RUnlock()
	return len(fake.getEntityArgsForCall)
}

func (fake *FakeIStore) GetEntityCalls(stub func(context.Context, string) (*graph.Entity, error)) {
	fake.getEntityMutex.Lock()
	defer fake.getEntityMutex.Unlock()
	fake.GetEntityStub = stub
}

func (fake *FakeIStore) GetEntityArgsForCall(i int) (context.Context, string) {
	fake.getEntityMutex.RLock()
	defer fake.getEntityMutex.RUnlock()
	argsForCall := fake.getEntityArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeIStore) GetEntityReturns(result1 *graph.Entity, result2 error) {
	fake.getEntityMutex.Lock()
	defer fake.getEntityMutex.Unlock()
	fake.GetEntityStub = nil
	fake.getEntityReturns = struct {
		result1 *graph.Entity
		result2 error
	}{result1, result2}
}

func (fake *FakeIStore) GetEntityReturnsOnCall(i int, result1 *graph.Entity, result2 error) {
	fake.getEntityMutex.Lock()
	defer fake.getEntityMutex.Unlock()
	fake.GetEntityStub = nil
	if fake.getEntityReturnsOnCall == nil {
		fake.getEntityReturnsOnCall = make(map[int]struct {
			result1 *graph.Entity
			result2 error
		})
	}
	fake.getEntityReturnsOnCall[i] = struct {
		result1 *graph.Entity
		result2 error
	}{result1, result2}
}

func (fake *FakeIStore) Neighbors(arg1 context.Context, arg2 string, arg3 int) ([]graph.Neighbor, error) {
	fake.neighborsMutex.Lock()
	ret, specificReturn := fake.neighborsReturnsOnCall[len(fake.neighborsArgsForCall)]
	fake.neighborsArgsForCall = append(fake.neighborsArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.NeighborsStub
	fakeReturns := fake.neighborsReturns
	fake.recordInvocation("Neighbors", []interface{}{arg1, arg2, arg3})
	fake.neighborsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeIStore) NeighborsCallCount() int {
	fake.neighborsMutex.RLock()
	defer fake.neighborsMutex.RUnlock()
	return len(fake.neighborsArgsForCall)
}

func (fake *FakeIStore) NeighborsCalls(stub func(context.Context, string, int) ([]graph.Neighbor, error)) {
	fake.neighborsMutex.Lock()
	defer fake.neighborsMutex.Unlock()
	fake.NeighborsStub = stub
}

func (fake *FakeIStore) NeighborsArgsForCall(i int) (context.Context, string, int) {
	fake.neighborsMutex.RLock()
	defer fake.neighborsMutex.RUnlock()
	argsForCall := fake.neighborsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeIStore) NeighborsReturns(result1 []graph.Neighbor, result2 error) {
	fake.neighborsMutex.Lock()
	defer fake.neighborsMutex.Unlock()
	fake.NeighborsStub = nil
	fake.neighborsReturns = struct {
		result1 []graph.Neighbor
		result2 error
	}{result1, result2}
}

func (fake *FakeIStore) NeighborsReturnsOnCall(i int, result1 []graph.Neighbor, result2 error) {
	fake.neighborsMutex.Lock()
	defer fake.neighborsMutex.Unlock()
	fake.NeighborsStub = nil
	if fake.neighborsReturnsOnCall == nil {
		fake.neighborsReturnsOnCall = make(map[int]struct {
			result1 []graph.Neighbor
			result2 error
		})
	}
	fake.neighborsReturnsOnCall[i] = struct {
		result1 []graph.Neighbor
		result2 error
	}{result1, result2}
}

func (fake *FakeIStore) RelationsIn(arg1 context.Context, arg2 string) ([]graph.Relation, error) {
	fake.relationsInMutex.Lock()
	ret, specificReturn := fake.relationsInReturnsOnCall[len(fake.relationsInArgsForCall)]
	fake.relationsInArgsForCall = append(fake.relationsInArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.RelationsInStub
	fakeReturns := fake.relationsInReturns
	fake.recordInvocation("RelationsIn", []interface{}{arg1, arg2})
	fake.relationsInMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeIStore) RelationsInCallCount() int {
	fake.relationsInMutex.RLock()
	defer fake.relationsInMutex.RUnlock()
	return len(fake.relationsInArgsForCall)
}

func (fake *FakeIStore) RelationsInCalls(stub func(context.Context, string) ([]graph.Relation, error)) {
	fake.relationsInMutex.Lock()
	defer fake.relationsInMutex.Unlock()
	fake.RelationsInStub = stub
}

func (fake *FakeIStore) RelationsInArgsForCall(i int) (context.Context, string) {
	fake.relationsInMutex.RLock()
	defer fake.relationsInMutex.RUnlock()
	argsForCall := fake.relationsInArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeIStore) RelationsInReturns(result1 []graph.Relation, result2 error) {
	fake.relationsInMutex.Lock()
	defer fake.relationsInMutex.Unlock()
	fake.RelationsInStub = nil
	fake.relationsInReturns = struct {
		result1 []graph.Relation
		result2 error
	}{result1, result2}
}

func (fake *FakeIStore) RelationsInReturnsOnCall(i int, result1 []graph.Relation, result2 error) {
	fake.relationsInMutex.Lock()
	defer fake.relationsInMutex.Unlock()
	fake.RelationsInStub = nil
	if fake.relationsInReturnsOnCall == nil {
		fake.relationsInReturnsOnCall = make(map[int]struct {
			result1 []graph.Relation
			result2 error
		})
	}
	fake.relationsInReturnsOnCall[i] = struct {
		result1 []graph.Relation
		result2 error
	}{result1, result2}
}

func (fake *FakeIStore) RelationsOut(arg1 context.Context, arg2 string) ([]graph.Relation, error) {
	fake.relationsOutMutex.Lock()
	ret, specificReturn := fake.relationsOutReturnsOnCall[len(fake.relationsOutArgsForCall)]
	fake.relationsOutArgsForCall = append(fake.relationsOutArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.RelationsOutStub
	fakeReturns := fake.relationsOutReturns
	fake.recordInvocation("RelationsOut", []interface{}{arg1, arg2})
	fake.relationsOutMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeIStore) RelationsOutCallCount() int {
	fake.relationsOutMutex.RLock()
	defer fake.relationsOutMutex.RUnlock()
	return len(fake.relationsOutArgsForCall)
}

func (fake *FakeIStore) RelationsOutCalls(stub func(context.Context, string) ([]graph.Relation, error)) {
	fake.relationsOutMutex.Lock()
	defer fake.relationsOutMutex.Unlock()
	fake.RelationsOutStub = stub
}

func (fake *FakeIStore) RelationsOutArgsForCall(i int) (context.Context, string) {
	fake.relationsOutMutex.RLock()
	defer fake.relationsOutMutex.RUnlock()
	argsForCall := fake.relationsOutArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeIStore) RelationsOutReturns(result1 []graph.Relation, result2 error) {
	fake.relationsOutMutex.Lock()
	defer fake.relationsOutMutex.Unlock()
	fake.RelationsOutStub = nil
	fake.relationsOutReturns = struct {
		result1 []graph.Relation
		result2 error
	}{result1, result2}
}

func (fake *FakeIStore) RelationsOutReturnsOnCall(i int, result1 []graph.Relation, result2 error) {
	fake.relationsOutMutex.Lock()
	defer fake.relationsOutMutex.Unlock()
	fake.RelationsOutStub = nil
	if fake.relationsOutReturnsOnCall == nil {
		fake.relationsOutReturnsOnCall = make(map[int]struct {
			result1 []graph.Relation
			result2 error
		})
	}
	fake.relationsOutReturnsOnCall[i] = struct {
		result1 []graph.Relation
		result2 error
	}{result1, result2}
}

func (fake *FakeIStore) ShortestPath(arg1 context.Context, arg2 string, arg3 string) ([]string, error) {
	fake.shortestPathMutex.Lock()
	ret, specificReturn := fake.shortestPathReturnsOnCall[len(fake.shortestPathArgsForCall)]
	fake.shortestPathArgsForCall = append(fake.shortestPathArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.ShortestPathStub
	fakeReturns := fake.shortestPathReturns
	fake.recordInvocation("ShortestPath", []interface{}{arg1, arg2, arg3})
	fake.shortestPathMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeIStore) ShortestPathCallCount() int {
	fake.shortestPathMutex.RLock()
	defer fake.shortestPathMutex.RUnlock()
	return len(fake.shortestPathArgsForCall)
}

func (fake *FakeIStore) ShortestPathCalls(stub func(context.Context, string, string) ([]string, error)) {
	fake.shortestPathMutex.Lock()
	defer fake.shortestPathMutex.Unlock()
	fake.ShortestPathStub = stub
}

func (fake *FakeIStore) ShortestPathArgsForCall(i int) (context.Context, string, string) {
	fake.shortestPathMutex.RLock()
	defer fake.shortestPathMutex.RUnlock()
	argsForCall := fake.shortestPathArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeIStore) ShortestPathReturns(result1 []string, result2 error) {
	fake.shortestPathMutex.Lock()
	defer fake.shortestPathMutex.Unlock()
	fake.ShortestPathStub = nil
	fake.shortestPathReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeIStore) ShortestPathReturnsOnCall(i int, result1 []string, result2 error) {
	fake.shortestPathMutex.Lock()
	defer fake.shortestPathMutex.Unlock()
	fake.ShortestPathStub = nil
	if fake.shortestPathReturnsOnCall == nil {
		fake.shortestPathReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.shortestPathReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeIStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeIStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ graph.IStore = new(FakeIStore)
