// Code generated by counterfeiter. DO NOT EDIT.
package vectorfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/memory/vector"
)

type FakeMemoryImportanceScorer struct {
	ScoreTextStub        func(context.Context, string) int
	scoreTextMutex       sync.RWMutex
	scoreTextArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	scoreTextReturns struct {
		result1 int
	}
	scoreTextReturnsOnCall map[int]struct {
		result1 int
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMemoryImportanceScorer) ScoreText(arg1 context.Context, arg2 string) int {
	fake.scoreTextMutex.Lock()
	ret, specificReturn := fake.scoreTextReturnsOnCall[len(fake.scoreTextArgsForCall)]
	fake.scoreTextArgsForCall = append(fake.scoreTextArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ScoreTextStub
	fakeReturns := fake.scoreTextReturns
	fake.recordInvocation("ScoreText", []interface{}{arg1, arg2})
	fake.scoreTextMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeMemoryImportanceScorer) ScoreTextCallCount() int {
	fake.scoreTextMutex.RLock()
	defer fake.scoreTextMutex.RUnlock()
	return len(fake.scoreTextArgsForCall)
}

func (fake *FakeMemoryImportanceScorer) ScoreTextCalls(stub func(context.Context, string) int) {
	fake.scoreTextMutex.Lock()
	defer fake.scoreTextMutex.Unlock()
	fake.ScoreTextStub = stub
}

func (fake *FakeMemoryImportanceScorer) ScoreTextArgsForCall(i int) (context.Context, string) {
	fake.scoreTextMutex.RLock()
	defer fake.scoreTextMutex.RUnlock()
	argsForCall := fake.scoreTextArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMemoryImportanceScorer) ScoreTextReturns(result1 int) {
	fake.scoreTextMutex.Lock()
	defer fake.scoreTextMutex.Unlock()
	fake.ScoreTextStub = nil
	fake.scoreTextReturns = struct {
		result1 int
	}{result1}
}

func (fake *FakeMemoryImportanceScorer) ScoreTextReturnsOnCall(i int, result1 int) {
	fake.scoreTextMutex.Lock()
	defer fake.scoreTextMutex.Unlock()
	fake.ScoreTextStub = nil
	if fake.scoreTextReturnsOnCall == nil {
		fake.scoreTextReturnsOnCall = make(map[int]struct {
			result1 int
		})
	}
	fake.scoreTextReturnsOnCall[i] = struct {
		result1 int
	}{result1}
}

func (fake *FakeMemoryImportanceScorer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMemoryImportanceScorer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ vector.MemoryImportanceScorer = new(FakeMemoryImportanceScorer)
