// Copyright (C) 2026 StackGen, Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by counterfeiter. DO NOT EDIT.
package vectorfakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/memory/vector"
)

type FakeIStore struct {
	AddStub        func(context.Context, ...vector.BatchItem) error
	addMutex       sync.RWMutex
	addArgsForCall []struct {
		arg1 context.Context
		arg2 []vector.BatchItem
	}
	addReturns struct {
		result1 error
	}
	addReturnsOnCall map[int]struct {
		result1 error
	}
	CloseStub        func(context.Context) error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
		arg1 context.Context
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteStub        func(context.Context, ...string) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 context.Context
		arg2 []string
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	SearchStub        func(context.Context, string, int) ([]vector.SearchResult, error)
	searchMutex       sync.RWMutex
	searchArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}
	searchReturns struct {
		result1 []vector.SearchResult
		result2 error
	}
	searchReturnsOnCall map[int]struct {
		result1 []vector.SearchResult
		result2 error
	}
	SearchWithFilterStub        func(context.Context, string, int, map[string]string) ([]vector.SearchResult, error)
	searchWithFilterMutex       sync.RWMutex
	searchWithFilterArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 int
		arg4 map[string]string
	}
	searchWithFilterReturns struct {
		result1 []vector.SearchResult
		result2 error
	}
	searchWithFilterReturnsOnCall map[int]struct {
		result1 []vector.SearchResult
		result2 error
	}
	UpsertStub        func(context.Context, ...vector.BatchItem) error
	upsertMutex       sync.RWMutex
	upsertArgsForCall []struct {
		arg1 context.Context
		arg2 []vector.BatchItem
	}
	upsertReturns struct {
		result1 error
	}
	upsertReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeIStore) Add(arg1 context.Context, arg2 ...vector.BatchItem) error {
	fake.addMutex.Lock()
	ret, specificReturn := fake.addReturnsOnCall[len(fake.addArgsForCall)]
	fake.addArgsForCall = append(fake.addArgsForCall, struct {
		arg1 context.Context
		arg2 []vector.BatchItem
	}{arg1, arg2})
	stub := fake.AddStub
	fakeReturns := fake.addReturns
	fake.recordInvocation("Add", []interface{}{arg1, arg2})
	fake.addMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIStore) AddCallCount() int {
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	return len(fake.addArgsForCall)
}

func (fake *FakeIStore) AddCalls(stub func(context.Context, ...vector.BatchItem) error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = stub
}

func (fake *FakeIStore) AddArgsForCall(i int) (context.Context, []vector.BatchItem) {
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	argsForCall := fake.addArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeIStore) AddReturns(result1 error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = nil
	fake.addReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) AddReturnsOnCall(i int, result1 error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = nil
	if fake.addReturnsOnCall == nil {
		fake.addReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) Close(arg1 context.Context) error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{arg1})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIStore) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeIStore) CloseCalls(stub func(context.Context) error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeIStore) CloseArgsForCall(i int) context.Context {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	argsForCall := fake.closeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeIStore) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) Delete(arg1 context.Context, arg2 ...string) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 context.Context
		arg2 []string
	}{arg1, arg2})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1, arg2})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIStore) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeIStore) DeleteCalls(stub func(context.Context, ...string) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeIStore) DeleteArgsForCall(i int) (context.Context, []string) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeIStore) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) Search(arg1 context.Context, arg2 string, arg3 int) ([]vector.SearchResult, error) {
	fake.searchMutex.Lock()
	ret, specificReturn := fake.searchReturnsOnCall[len(fake.searchArgsForCall)]
	fake.searchArgsForCall = append(fake.searchArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
	}{arg1, arg2, arg3})
	stub := fake.SearchStub
	fakeReturns := fake.searchReturns
	fake.recordInvocation("Search", []interface{}{arg1, arg2, arg3})
	fake.searchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeIStore) SearchCallCount() int {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	return len(fake.searchArgsForCall)
}

func (fake *FakeIStore) SearchCalls(stub func(context.Context, string, int) ([]vector.SearchResult, error)) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = stub
}

func (fake *FakeIStore) SearchArgsForCall(i int) (context.Context, string, int) {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	argsForCall := fake.searchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeIStore) SearchReturns(result1 []vector.SearchResult, result2 error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = nil
	fake.searchReturns = struct {
		result1 []vector.SearchResult
		result2 error
	}{result1, result2}
}

func (fake *FakeIStore) SearchReturnsOnCall(i int, result1 []vector.SearchResult, result2 error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = nil
	if fake.searchReturnsOnCall == nil {
		fake.searchReturnsOnCall = make(map[int]struct {
			result1 []vector.SearchResult
			result2 error
		})
	}
	fake.searchReturnsOnCall[i] = struct {
		result1 []vector.SearchResult
		result2 error
	}{result1, result2}
}

func (fake *FakeIStore) SearchWithFilter(arg1 context.Context, arg2 string, arg3 int, arg4 map[string]string) ([]vector.SearchResult, error) {
	fake.searchWithFilterMutex.Lock()
	ret, specificReturn := fake.searchWithFilterReturnsOnCall[len(fake.searchWithFilterArgsForCall)]
	fake.searchWithFilterArgsForCall = append(fake.searchWithFilterArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 int
		arg4 map[string]string
	}{arg1, arg2, arg3, arg4})
	stub := fake.SearchWithFilterStub
	fakeReturns := fake.searchWithFilterReturns
	fake.recordInvocation("SearchWithFilter", []interface{}{arg1, arg2, arg3, arg4})
	fake.searchWithFilterMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeIStore) SearchWithFilterCallCount() int {
	fake.searchWithFilterMutex.RLock()
	defer fake.searchWithFilterMutex.RUnlock()
	return len(fake.searchWithFilterArgsForCall)
}

func (fake *FakeIStore) SearchWithFilterCalls(stub func(context.Context, string, int, map[string]string) ([]vector.SearchResult, error)) {
	fake.searchWithFilterMutex.Lock()
	defer fake.searchWithFilterMutex.Unlock()
	fake.SearchWithFilterStub = stub
}

func (fake *FakeIStore) SearchWithFilterArgsForCall(i int) (context.Context, string, int, map[string]string) {
	fake.searchWithFilterMutex.RLock()
	defer fake.searchWithFilterMutex.RUnlock()
	argsForCall := fake.searchWithFilterArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeIStore) SearchWithFilterReturns(result1 []vector.SearchResult, result2 error) {
	fake.searchWithFilterMutex.Lock()
	defer fake.searchWithFilterMutex.Unlock()
	fake.SearchWithFilterStub = nil
	fake.searchWithFilterReturns = struct {
		result1 []vector.SearchResult
		result2 error
	}{result1, result2}
}

func (fake *FakeIStore) SearchWithFilterReturnsOnCall(i int, result1 []vector.SearchResult, result2 error) {
	fake.searchWithFilterMutex.Lock()
	defer fake.searchWithFilterMutex.Unlock()
	fake.SearchWithFilterStub = nil
	if fake.searchWithFilterReturnsOnCall == nil {
		fake.searchWithFilterReturnsOnCall = make(map[int]struct {
			result1 []vector.SearchResult
			result2 error
		})
	}
	fake.searchWithFilterReturnsOnCall[i] = struct {
		result1 []vector.SearchResult
		result2 error
	}{result1, result2}
}

func (fake *FakeIStore) Upsert(arg1 context.Context, arg2 ...vector.BatchItem) error {
	fake.upsertMutex.Lock()
	ret, specificReturn := fake.upsertReturnsOnCall[len(fake.upsertArgsForCall)]
	fake.upsertArgsForCall = append(fake.upsertArgsForCall, struct {
		arg1 context.Context
		arg2 []vector.BatchItem
	}{arg1, arg2})
	stub := fake.UpsertStub
	fakeReturns := fake.upsertReturns
	fake.recordInvocation("Upsert", []interface{}{arg1, arg2})
	fake.upsertMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeIStore) UpsertCallCount() int {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	return len(fake.upsertArgsForCall)
}

func (fake *FakeIStore) UpsertCalls(stub func(context.Context, ...vector.BatchItem) error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = stub
}

func (fake *FakeIStore) UpsertArgsForCall(i int) (context.Context, []vector.BatchItem) {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	argsForCall := fake.upsertArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeIStore) UpsertReturns(result1 error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = nil
	fake.upsertReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) UpsertReturnsOnCall(i int, result1 error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = nil
	if fake.upsertReturnsOnCall == nil {
		fake.upsertReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.upsertReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeIStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ vector.IStore = new(FakeIStore)
