// Code generated by counterfeiter. DO NOT EDIT.
package credstorefakes

import (
	"context"
	"sync"

	"github.com/stackgenhq/genie/pkg/credstore"
)

type FakeStore struct {
	DeleteTokenStub        func(context.Context) error
	deleteTokenMutex       sync.RWMutex
	deleteTokenArgsForCall []struct {
		arg1 context.Context
	}
	deleteTokenReturns struct {
		result1 error
	}
	deleteTokenReturnsOnCall map[int]struct {
		result1 error
	}
	GetTokenStub        func(context.Context) (*credstore.Token, error)
	getTokenMutex       sync.RWMutex
	getTokenArgsForCall []struct {
		arg1 context.Context
	}
	getTokenReturns struct {
		result1 *credstore.Token
		result2 error
	}
	getTokenReturnsOnCall map[int]struct {
		result1 *credstore.Token
		result2 error
	}
	SaveTokenStub        func(context.Context, *credstore.Token) error
	saveTokenMutex       sync.RWMutex
	saveTokenArgsForCall []struct {
		arg1 context.Context
		arg2 *credstore.Token
	}
	saveTokenReturns struct {
		result1 error
	}
	saveTokenReturnsOnCall map[int]struct {
		result1 error
	}
	ServiceNameStub        func() string
	serviceNameMutex       sync.RWMutex
	serviceNameArgsForCall []struct {
	}
	serviceNameReturns struct {
		result1 string
	}
	serviceNameReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStore) DeleteToken(arg1 context.Context) error {
	fake.deleteTokenMutex.Lock()
	ret, specificReturn := fake.deleteTokenReturnsOnCall[len(fake.deleteTokenArgsForCall)]
	fake.deleteTokenArgsForCall = append(fake.deleteTokenArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.DeleteTokenStub
	fakeReturns := fake.deleteTokenReturns
	fake.recordInvocation("DeleteToken", []interface{}{arg1})
	fake.deleteTokenMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) DeleteTokenCallCount() int {
	fake.deleteTokenMutex.RLock()
	defer fake.deleteTokenMutex.RUnlock()
	return len(fake.deleteTokenArgsForCall)
}

func (fake *FakeStore) DeleteTokenCalls(stub func(context.Context) error) {
	fake.deleteTokenMutex.Lock()
	defer fake.deleteTokenMutex.Unlock()
	fake.DeleteTokenStub = stub
}

func (fake *FakeStore) DeleteTokenArgsForCall(i int) context.Context {
	fake.deleteTokenMutex.RLock()
	defer fake.deleteTokenMutex.RUnlock()
	argsForCall := fake.deleteTokenArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStore) DeleteTokenReturns(result1 error) {
	fake.deleteTokenMutex.Lock()
	defer fake.deleteTokenMutex.Unlock()
	fake.DeleteTokenStub = nil
	fake.deleteTokenReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) DeleteTokenReturnsOnCall(i int, result1 error) {
	fake.deleteTokenMutex.Lock()
	defer fake.deleteTokenMutex.Unlock()
	fake.DeleteTokenStub = nil
	if fake.deleteTokenReturnsOnCall == nil {
		fake.deleteTokenReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteTokenReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) GetToken(arg1 context.Context) (*credstore.Token, error) {
	fake.getTokenMutex.Lock()
	ret, specificReturn := fake.getTokenReturnsOnCall[len(fake.getTokenArgsForCall)]
	fake.getTokenArgsForCall = append(fake.getTokenArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetTokenStub
	fakeReturns := fake.getTokenReturns
	fake.recordInvocation("GetToken", []interface{}{arg1})
	fake.getTokenMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStore) GetTokenCallCount() int {
	fake.getTokenMutex.RLock()
	defer fake.getTokenMutex.RUnlock()
	return len(fake.getTokenArgsForCall)
}

func (fake *FakeStore) GetTokenCalls(stub func(context.Context) (*credstore.Token, error)) {
	fake.getTokenMutex.Lock()
	defer fake.getTokenMutex.Unlock()
	fake.GetTokenStub = stub
}

func (fake *FakeStore) GetTokenArgsForCall(i int) context.Context {
	fake.getTokenMutex.RLock()
	defer fake.getTokenMutex.RUnlock()
	argsForCall := fake.getTokenArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeStore) GetTokenReturns(result1 *credstore.Token, result2 error) {
	fake.getTokenMutex.Lock()
	defer fake.getTokenMutex.Unlock()
	fake.GetTokenStub = nil
	fake.getTokenReturns = struct {
		result1 *credstore.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) GetTokenReturnsOnCall(i int, result1 *credstore.Token, result2 error) {
	fake.getTokenMutex.Lock()
	defer fake.getTokenMutex.Unlock()
	fake.GetTokenStub = nil
	if fake.getTokenReturnsOnCall == nil {
		fake.getTokenReturnsOnCall = make(map[int]struct {
			result1 *credstore.Token
			result2 error
		})
	}
	fake.getTokenReturnsOnCall[i] = struct {
		result1 *credstore.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeStore) SaveToken(arg1 context.Context, arg2 *credstore.Token) error {
	fake.saveTokenMutex.Lock()
	ret, specificReturn := fake.saveTokenReturnsOnCall[len(fake.saveTokenArgsForCall)]
	fake.saveTokenArgsForCall = append(fake.saveTokenArgsForCall, struct {
		arg1 context.Context
		arg2 *credstore.Token
	}{arg1, arg2})
	stub := fake.SaveTokenStub
	fakeReturns := fake.saveTokenReturns
	fake.recordInvocation("SaveToken", []interface{}{arg1, arg2})
	fake.saveTokenMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) SaveTokenCallCount() int {
	fake.saveTokenMutex.RLock()
	defer fake.saveTokenMutex.RUnlock()
	return len(fake.saveTokenArgsForCall)
}

func (fake *FakeStore) SaveTokenCalls(stub func(context.Context, *credstore.Token) error) {
	fake.saveTokenMutex.Lock()
	defer fake.saveTokenMutex.Unlock()
	fake.SaveTokenStub = stub
}

func (fake *FakeStore) SaveTokenArgsForCall(i int) (context.Context, *credstore.Token) {
	fake.saveTokenMutex.RLock()
	defer fake.saveTokenMutex.RUnlock()
	argsForCall := fake.saveTokenArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStore) SaveTokenReturns(result1 error) {
	fake.saveTokenMutex.Lock()
	defer fake.saveTokenMutex.Unlock()
	fake.SaveTokenStub = nil
	fake.saveTokenReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) SaveTokenReturnsOnCall(i int, result1 error) {
	fake.saveTokenMutex.Lock()
	defer fake.saveTokenMutex.Unlock()
	fake.SaveTokenStub = nil
	if fake.saveTokenReturnsOnCall == nil {
		fake.saveTokenReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.saveTokenReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStore) ServiceName() string {
	fake.serviceNameMutex.Lock()
	ret, specificReturn := fake.serviceNameReturnsOnCall[len(fake.serviceNameArgsForCall)]
	fake.serviceNameArgsForCall = append(fake.serviceNameArgsForCall, struct {
	}{})
	stub := fake.ServiceNameStub
	fakeReturns := fake.serviceNameReturns
	fake.recordInvocation("ServiceName", []interface{}{})
	fake.serviceNameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStore) ServiceNameCallCount() int {
	fake.serviceNameMutex.RLock()
	defer fake.serviceNameMutex.RUnlock()
	return len(fake.serviceNameArgsForCall)
}

func (fake *FakeStore) ServiceNameCalls(stub func() string) {
	fake.serviceNameMutex.Lock()
	defer fake.serviceNameMutex.Unlock()
	fake.ServiceNameStub = stub
}

func (fake *FakeStore) ServiceNameReturns(result1 string) {
	fake.serviceNameMutex.Lock()
	defer fake.serviceNameMutex.Unlock()
	fake.ServiceNameStub = nil
	fake.serviceNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeStore) ServiceNameReturnsOnCall(i int, result1 string) {
	fake.serviceNameMutex.Lock()
	defer fake.serviceNameMutex.Unlock()
	fake.ServiceNameStub = nil
	if fake.serviceNameReturnsOnCall == nil {
		fake.serviceNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.serviceNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ credstore.Store = new(FakeStore)
