name: goreleaser

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

permissions:
  contents: write
  id-token: write
env:
  BUCKET: "appcd-public-releases"
  AWS_REGION: "us-east-2"
  AWS_ROLE_ARN: "arn:aws:iam::584974133937:role/GitHubActionsRole"

jobs:
  goreleaser:
    runs-on: arm-runner-v2
    container:
      image: goreleaser/goreleaser-cross:latest
    env:
      GOPRIVATE: "github.com/appcd-dev/go-lib"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            /root/go/pkg/mod
            /root/.cache/go-build
          key: go-${{ runner.arch }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.arch }}-
      - name: Setup Repo
        uses: ./.github/actions/setup
        with:
          GO_LIB_TOKEN: ${{ secrets.GO_LIB_TOKEN }}
      - name: Install quill
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/quill/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
      - name: Configure Git for private repos
        run: |
          git config --global url."https://${{ secrets.GO_LIB_TOKEN }}:x-oauth-basic@github.com".insteadOf "https://github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Run GoReleaser
        if: startsWith(github.ref, 'refs/tags/') && !contains(github.ref, '-rc.')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUILL_SIGN_P12: ${{ secrets.QUILL_SIGN_P12 }}
          QUILL_SIGN_PASSWORD: ${{ secrets.QUILL_SIGN_PASSWORD }}
          BREW_TOKEN: ${{ secrets.BREW_TOKEN }}
          FF_UNLEASH_API_KEY: ${{ secrets.FF_UNLEASH_API_KEY }}
          LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
        run: goreleaser release --clean
      - name: Run GoReleaser (on rc tag)
        if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-rc.')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUILL_SIGN_P12: ${{ secrets.QUILL_SIGN_P12 }}
          QUILL_SIGN_PASSWORD: ${{ secrets.QUILL_SIGN_PASSWORD }}
          BREW_TOKEN: ${{ secrets.BREW_TOKEN }}
          FF_UNLEASH_API_KEY: ${{ secrets.FF_UNLEASH_API_KEY }}
          LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
        run: goreleaser release --clean --config ./goreleaser-main.yaml
